using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using WC3ItemManager.Models;
using WC3ItemManager.Repositories;

namespace WC3ItemManager.Exporters
{
    /// <summary>
    /// Exports GatherNodes JASS definitions from database
    /// </summary>
    public class GatherNodeExporter
    {
        private readonly string _connectionString;
        private readonly GatherNodeRepository _repository;

        public GatherNodeExporter(string connectionString)
        {
            _connectionString = connectionString;
            _repository = new GatherNodeRepository(connectionString);
        }

        /// <summary>
        /// Export all gather node definitions to JASS
        /// </summary>
        public GatherNodeExportResult ExportAll(string outputFolder)
        {
            var result = new GatherNodeExportResult();
            
            try
            {
                // Ensure output folder exists
                if (!Directory.Exists(outputFolder))
                {
                    Directory.CreateDirectory(outputFolder);
                }

                // Timestamp for filenames
                string timestamp = DateTime.Now.ToString("yyyyMMdd_HHmmss");

                // Export definitions
                string definitionsPath = Path.Combine(outputFolder, $"GatherNodeDefinitions_{timestamp}.j");
                ExportDefinitions(definitionsPath, result);
                result.FilesExported.Add(definitionsPath);

                result.Success = true;
                Logger.Instance.Info($"Gather nodes exported: {result.ItemNodesExported} item nodes, {result.UnitNodesExported} unit nodes, {result.ZoneAssignmentsExported} zone assignments");
            }
            catch (Exception ex)
            {
                result.Success = false;
                result.ErrorMessage = ex.Message;
                Logger.Instance.Error("Failed to export gather nodes", ex);
            }

            return result;
        }

        /// <summary>
        /// Export gather node definitions
        /// </summary>
        private void ExportDefinitions(string outputPath, GatherNodeExportResult result)
        {
            var itemNodes = _repository.GetAllItemNodes().Where(n => n.Enabled).ToList();
            var unitNodes = _repository.GetAllUnitNodes().Where(n => n.Enabled).ToList();
            var categories = _repository.GetAllCategories();
            
            var sb = new StringBuilder();

            // Header
            sb.AppendLine("//===========================================================================");
            sb.AppendLine("// GatherNodeDefinitions.j");
            sb.AppendLine("// Generated by WC3ItemManager - DO NOT EDIT MANUALLY");
            sb.AppendLine($"// Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine("//===========================================================================");
            sb.AppendLine("//");
            sb.AppendLine("// This file contains all gather node definitions exported from the database.");
            sb.AppendLine("// Include this after GatherNodes.j, GatherNodeItems.j, and GatherNodeUnits.j");
            sb.AppendLine("//");
            sb.AppendLine("//===========================================================================");
            sb.AppendLine();
            sb.AppendLine("library GatherNodeDefinitions initializer Init requires GatherNodes, GatherNodeItems, GatherNodeUnits");
            sb.AppendLine();

            // Category constants
            sb.AppendLine("    //===========================================================================");
            sb.AppendLine("    // CATEGORY CONSTANTS");
            sb.AppendLine("    //===========================================================================");
            sb.AppendLine("    globals");
            
            foreach (var category in categories.Where(c => c.Enabled))
            {
                string constName = "GATHER_CAT_" + category.CategoryName.ToUpper().Replace(" ", "_");
                sb.AppendLine($"        constant integer {constName} = {category.Id}");
            }
            
            sb.AppendLine("    endglobals");
            sb.AppendLine();

            // RegisterItemNodes function
            sb.AppendLine("    //===========================================================================");
            sb.AppendLine("    // ITEM NODE DEFINITIONS (Herbs, Flowers, Mushrooms)");
            sb.AppendLine("    //===========================================================================");
            sb.AppendLine("    private function RegisterItemNodes takes nothing returns nothing");
            sb.AppendLine("        local integer defId");
            sb.AppendLine();

            // Group item nodes by category
            var itemsByCategory = itemNodes.GroupBy(n => n.CategoryName ?? "Uncategorized").OrderBy(g => g.Key);
            
            foreach (var categoryGroup in itemsByCategory)
            {
                sb.AppendLine($"        // === {categoryGroup.Key.ToUpper()} ===");
                
                foreach (var node in categoryGroup.OrderBy(n => n.NodeName))
                {
                    string glowEffect = node.GlowEffect ? "true" : "false";
                    string isRare = node.IsRare ? "true" : "false";
                    
                    sb.AppendLine($"        // {node.NodeName}");
                    sb.AppendLine($"        set defId = GNI_RegisterDefinition('{node.ItemCode}', \"{node.NodeName}\", {node.CategoryId ?? 0}, {node.SpawnWeight}, {node.RespawnTimeMin.ToString("F1", CultureInfo.InvariantCulture)}, {node.RespawnTimeMax.ToString("F1", CultureInfo.InvariantCulture)}, {node.MaxPerZone}, {node.SkillRequired}, {glowEffect}, {node.GlowColorR}, {node.GlowColorG}, {node.GlowColorB}, {node.GlowAlpha}, {isRare})");
                    
                    // Export zone assignments for this node
                    var zones = _repository.GetZoneAssignmentsByNode("item", node.Id).Where(z => z.Enabled).ToList();
                    foreach (var zone in zones)
                    {
                        int spawnModeInt = GetSpawnModeInt(zone.SpawnMode);
                        int weightOverride = zone.WeightOverride ?? -1;
                        int maxOverride = zone.MaxOverride ?? -1;
                        sb.AppendLine($"        call GNI_RegisterZoneAssignment(defId, {zone.ZoneId}, {spawnModeInt}, {weightOverride}, {maxOverride})  // {zone.ZoneName}");
                        result.ZoneAssignmentsExported++;
                    }
                    
                    sb.AppendLine();
                    result.ItemNodesExported++;
                }
            }
            
            sb.AppendLine("    endfunction");
            sb.AppendLine();

            // RegisterUnitNodes function
            sb.AppendLine("    //===========================================================================");
            sb.AppendLine("    // UNIT NODE DEFINITIONS (Ore Veins, Crystal Veins, Fish Pools, etc.)");
            sb.AppendLine("    //===========================================================================");
            sb.AppendLine("    private function RegisterUnitNodes takes nothing returns nothing");
            sb.AppendLine("        local integer defId");
            sb.AppendLine();

            // Group unit nodes by category
            var unitsByCategory = unitNodes.GroupBy(n => n.CategoryName ?? "Uncategorized").OrderBy(g => g.Key);
            
            foreach (var categoryGroup in unitsByCategory)
            {
                sb.AppendLine($"        // === {categoryGroup.Key.ToUpper()} ===");
                
                foreach (var node in categoryGroup.OrderBy(n => n.NodeName))
                {
                    string glowEffect = node.GlowEffect ? "true" : "false";
                    string isRare = node.IsRare ? "true" : "false";
                    
                    sb.AppendLine($"        // {node.NodeName}");
                    sb.AppendLine($"        set defId = GNU_RegisterDefinition('{node.UnitCode}', \"{node.NodeName}\", {node.CategoryId ?? 0}, {node.SpawnWeight}, {node.RespawnTimeMin.ToString("F1", CultureInfo.InvariantCulture)}, {node.RespawnTimeMax.ToString("F1", CultureInfo.InvariantCulture)}, {node.MaxPerZone}, {node.SkillRequired}, {node.OwnerPlayer}, {glowEffect}, {node.GlowColorR}, {node.GlowColorG}, {node.GlowColorB}, {node.GlowAlpha}, {node.GlowScale.ToString("F1", CultureInfo.InvariantCulture)}, {isRare})");
                    
                    // Export zone assignments for this node
                    var zones = _repository.GetZoneAssignmentsByNode("unit", node.Id).Where(z => z.Enabled).ToList();
                    foreach (var zone in zones)
                    {
                        int spawnModeInt = GetSpawnModeInt(zone.SpawnMode);
                        int weightOverride = zone.WeightOverride ?? -1;
                        int maxOverride = zone.MaxOverride ?? -1;
                        sb.AppendLine($"        call GNU_RegisterZoneAssignment(defId, {zone.ZoneId}, {spawnModeInt}, {weightOverride}, {maxOverride})  // {zone.ZoneName}");
                        result.ZoneAssignmentsExported++;
                    }
                    
                    sb.AppendLine();
                    result.UnitNodesExported++;
                }
            }
            
            sb.AppendLine("    endfunction");
            sb.AppendLine();

            // RegisterSpawnRegions function (placeholder for manual region integration)
            sb.AppendLine("    //===========================================================================");
            sb.AppendLine("    // SPAWN REGION REGISTRATION");
            sb.AppendLine("    // Add your spawn regions here - these must match gg_rct_ variables from map");
            sb.AppendLine("    //===========================================================================");
            sb.AppendLine("    private function RegisterSpawnRegions takes nothing returns nothing");
            sb.AppendLine("        // Example:");
            sb.AppendLine("        // call GNI_RegisterSpawnRegion(1, gg_rct_TwilightGrove_Herbs_01)");
            sb.AppendLine("        // call GNU_RegisterSpawnRegion(1, gg_rct_TwilightGrove_Veins_01)");
            sb.AppendLine();

            // Export spawn points from database
            var spawnPoints = _repository.GetAllSpawnPoints().Where(p => p.Enabled).ToList();
            if (spawnPoints.Any())
            {
                var pointsByZone = spawnPoints.GroupBy(p => p.ZoneId).OrderBy(g => g.Key);
                foreach (var zoneGroup in pointsByZone)
                {
                    var firstPoint = zoneGroup.First();
                    sb.AppendLine($"        // Zone {zoneGroup.Key}: {firstPoint.ZoneName}");
                    
                    foreach (var point in zoneGroup)
                    {
                        string nodeType = point.NodeType switch
                        {
                            "item" => "GNI_RegisterSpawnRegion",
                            "unit" => "GNU_RegisterSpawnRegion",
                            _ => "GNI_RegisterSpawnRegion"
                        };
                        
                        sb.AppendLine($"        call {nodeType}({point.ZoneId}, {point.RegionVariable})  // {point.PointName}");
                        result.SpawnPointsExported++;
                    }
                    sb.AppendLine();
                }
            }
            
            sb.AppendLine("    endfunction");
            sb.AppendLine();

            // Init function
            sb.AppendLine("    //===========================================================================");
            sb.AppendLine("    // INITIALIZATION");
            sb.AppendLine("    //===========================================================================");
            sb.AppendLine("    private function DelayedInit takes nothing returns nothing");
            sb.AppendLine("        call DestroyTimer(GetExpiredTimer())");
            sb.AppendLine();
            sb.AppendLine("        // Register all definitions");
            sb.AppendLine("        call RegisterItemNodes()");
            sb.AppendLine("        call RegisterUnitNodes()");
            sb.AppendLine("        call RegisterSpawnRegions()");
            sb.AppendLine();
            sb.AppendLine("        // Spawn initial nodes in all zones");
            sb.AppendLine("        call GNI_SpawnInitialAll()");
            sb.AppendLine("        call GNU_SpawnInitialAll()");
            sb.AppendLine();
            sb.AppendLine("        if GN_IsDebugMode() then");
            sb.AppendLine("            call BJDebugMsg(\"|cff00ff00[GatherNodeDefinitions]|r All nodes registered and spawned\")");
            sb.AppendLine("        endif");
            sb.AppendLine("    endfunction");
            sb.AppendLine();
            sb.AppendLine("    private function Init takes nothing returns nothing");
            sb.AppendLine("        // Use timer to delay registration until after map init");
            sb.AppendLine("        call TimerStart(CreateTimer(), 0.1, false, function DelayedInit)");
            sb.AppendLine("    endfunction");
            sb.AppendLine();
            sb.AppendLine("endlibrary");

            // Write to file
            File.WriteAllText(outputPath, sb.ToString());
        }

        /// <summary>
        /// Convert spawn mode string to integer
        /// </summary>
        private int GetSpawnModeInt(string spawnMode)
        {
            return spawnMode?.ToLower() switch
            {
                "random" => 0,
                "fixed" => 1,
                "both" => 2,
                _ => 0
            };
        }
    }

    /// <summary>
    /// Result of gather node export operation
    /// </summary>
    public class GatherNodeExportResult
    {
        public bool Success { get; set; }
        public string ErrorMessage { get; set; }
        public List<string> FilesExported { get; set; } = new List<string>();
        public int ItemNodesExported { get; set; }
        public int UnitNodesExported { get; set; }
        public int ZoneAssignmentsExported { get; set; }
        public int SpawnPointsExported { get; set; }
    }
}
