using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using WC3ItemManager.Models;
using WC3ItemManager.Repositories;

namespace WC3ItemManager.Exporters
{
    /// <summary>
    /// Exports GatherNodes JASS definitions from database
    /// </summary>
    public class GatherNodeExporter
    {
        private readonly string _connectionString;
        private readonly GatherNodeRepository _repository;

        public GatherNodeExporter(string connectionString)
        {
            _connectionString = connectionString;
            _repository = new GatherNodeRepository(connectionString);
        }

        /// <summary>
        /// Export all gather node definitions to JASS
        /// </summary>
        public GatherNodeExportResult ExportAll(string outputFolder)
        {
            var result = new GatherNodeExportResult();
            
            try
            {
                // Ensure output folder exists
                if (!Directory.Exists(outputFolder))
                {
                    Directory.CreateDirectory(outputFolder);
                }

                // Timestamp for filenames
                string timestamp = DateTime.Now.ToString("yyyyMMdd_HHmmss");

                // Export definitions
                string definitionsPath = Path.Combine(outputFolder, $"GatherNodeDefinitions_{timestamp}.j");
                ExportDefinitions(definitionsPath, result);
                result.FilesExported.Add(definitionsPath);

                result.Success = true;
                Logger.Instance.Info($"Gather nodes exported: {result.ItemNodesExported} item nodes, {result.UnitNodesExported} unit nodes, {result.ZoneAssignmentsExported} zone assignments");
            }
            catch (Exception ex)
            {
                result.Success = false;
                result.ErrorMessage = ex.Message;
                Logger.Instance.Error("Failed to export gather nodes", ex);
            }

            return result;
        }

        /// <summary>
        /// Export gather node definitions
        /// </summary>
        private void ExportDefinitions(string outputPath, GatherNodeExportResult result)
        {
            var itemNodes = _repository.GetAllItemNodes().Where(n => n.Enabled).ToList();
            var unitNodes = _repository.GetAllUnitNodes().Where(n => n.Enabled).ToList();
            var categories = _repository.GetAllCategories();
            var unitCategoryLookup = BuildUnitCategoryLookup(categories);
            
            var sb = new StringBuilder();

            // Header
            sb.AppendLine("//===========================================================================");
            sb.AppendLine("// GatherNodeDefinitions.j");
            sb.AppendLine("// Generated by WC3ItemManager - DO NOT EDIT MANUALLY");
            sb.AppendLine($"// Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine("//===========================================================================");
            sb.AppendLine("//");
            sb.AppendLine("// This file contains all gather node definitions exported from the database.");
            sb.AppendLine("// Include this after GatherNodes.j, GatherNodeItems.j, and GatherNodeUnits.j");
            sb.AppendLine("// Random In Zone placements use ZonesCore zone rects at runtime.");
            sb.AppendLine("// Only spawn-group placements need explicit gather spawn-group registrations here.");
            sb.AppendLine("//");
            sb.AppendLine("//===========================================================================");
            sb.AppendLine();
            sb.AppendLine("library GatherNodeDefinitions initializer Init requires GatherNodes, GatherNodeItems, GatherNodeUnits");
            sb.AppendLine();

            // Category constants
            sb.AppendLine("    //===========================================================================");
            sb.AppendLine("    // CATEGORY CONSTANTS");
            sb.AppendLine("    //===========================================================================");
            sb.AppendLine("    globals");
            
            foreach (var category in categories.Where(c => c.Enabled))
            {
                string constName = "GATHER_CAT_" + category.CategoryName.ToUpper().Replace(" ", "_");
                sb.AppendLine($"        constant integer {constName} = {category.Id}");
            }
            sb.AppendLine("        private trigger GND_InitTrigger = null");
            sb.AppendLine("        private trigger GND_SpawnTrigger = null");
            sb.AppendLine("    endglobals");
            sb.AppendLine();

            // RegisterItemNodes function
            sb.AppendLine("    //===========================================================================");
            sb.AppendLine("    // ITEM NODE DEFINITIONS (Herbs, Flowers, Mushrooms)");
            sb.AppendLine("    //===========================================================================");
            sb.AppendLine("    private function RegisterItemNodes takes nothing returns nothing");
            sb.AppendLine("        local integer defId");
            sb.AppendLine();

            var orderedItemCategories = categories
                .Where(c => c.Enabled && c.NodeType == "item")
                .OrderBy(c => c.DisplayOrder)
                .ThenBy(c => c.CategoryName)
                .ToList();

            foreach (var category in orderedItemCategories)
            {
                var categoryNodes = itemNodes
                    .Where(n => n.CategoryId == category.Id)
                    .OrderBy(n => n.DisplayOrder)
                    .ThenBy(n => n.NodeName)
                    .ToList();

                if (!categoryNodes.Any())
                {
                    continue;
                }

                sb.AppendLine($"        // === {category.CategoryName.ToUpper()} ===");
                
                foreach (var node in categoryNodes)
                {
                    string glowEffect = node.GlowEffect ? "true" : "false";
                    string preventWaterSpawn = node.PreventWaterSpawn ? "true" : "false";
                    string isRare = node.IsRare ? "true" : "false";
                    
                    sb.AppendLine($"        // {node.NodeName}");
                    sb.AppendLine($"        set defId = GNI_RegisterDefinition('{node.ItemCode}', \"{node.NodeName}\", {node.CategoryId ?? 0}, {node.SpawnWeight}, {node.RespawnTimeMin.ToString("F1", CultureInfo.InvariantCulture)}, {node.RespawnTimeMax.ToString("F1", CultureInfo.InvariantCulture)}, {node.MaxPerZone}, {node.SkillRequired}, {node.ProfessionId}, {preventWaterSpawn}, {glowEffect}, {node.GlowColorR}, {node.GlowColorG}, {node.GlowColorB}, {node.GlowAlpha}, {node.GlowScale.ToString("F1", CultureInfo.InvariantCulture)}, {node.GlowHeight.ToString("F1", CultureInfo.InvariantCulture)}, {isRare})");
                    
                    // Export zone assignments for this node
                    var zones = _repository.GetZoneAssignmentsByNode("item", node.Id).Where(z => z.Enabled).ToList();
                    foreach (var zone in zones)
                    {
                        int spawnModeInt = GetSpawnModeInt(zone.SpawnMode);
                        int weightOverride = zone.WeightOverride ?? -1;
                        int maxOverride = zone.MaxOverride ?? -1;
                        int sharedMaxOverride = zone.SharedMaxOverride ?? -1;
                        int spawnGroupId = zone.SpawnGroupId ?? -1;
                        sb.AppendLine($"        call GNI_RegisterZoneAssignment(defId, {zone.ZoneId}, {spawnModeInt}, {spawnGroupId}, {weightOverride}, {maxOverride}, {sharedMaxOverride})  // {zone.ZoneName}");
                        result.ZoneAssignmentsExported++;
                    }
                    
                    sb.AppendLine();
                    result.ItemNodesExported++;
                }
            }

            var uncategorizedItems = itemNodes
                .Where(n => !n.CategoryId.HasValue)
                .OrderBy(n => n.DisplayOrder)
                .ThenBy(n => n.NodeName)
                .ToList();

            if (uncategorizedItems.Any())
            {
                sb.AppendLine("        // === UNCATEGORIZED ===");
                foreach (var node in uncategorizedItems)
                {
                    string glowEffect = node.GlowEffect ? "true" : "false";
                    string preventWaterSpawn = node.PreventWaterSpawn ? "true" : "false";
                    string isRare = node.IsRare ? "true" : "false";

                    sb.AppendLine($"        // {node.NodeName}");
                    sb.AppendLine($"        set defId = GNI_RegisterDefinition('{node.ItemCode}', \"{node.NodeName}\", {node.CategoryId ?? 0}, {node.SpawnWeight}, {node.RespawnTimeMin.ToString("F1", CultureInfo.InvariantCulture)}, {node.RespawnTimeMax.ToString("F1", CultureInfo.InvariantCulture)}, {node.MaxPerZone}, {node.SkillRequired}, {node.ProfessionId}, {preventWaterSpawn}, {glowEffect}, {node.GlowColorR}, {node.GlowColorG}, {node.GlowColorB}, {node.GlowAlpha}, {node.GlowScale.ToString("F1", CultureInfo.InvariantCulture)}, {node.GlowHeight.ToString("F1", CultureInfo.InvariantCulture)}, {isRare})");

                    var zones = _repository.GetZoneAssignmentsByNode("item", node.Id).Where(z => z.Enabled).ToList();
                    foreach (var zone in zones)
                    {
                        int spawnModeInt = GetSpawnModeInt(zone.SpawnMode);
                        int weightOverride = zone.WeightOverride ?? -1;
                        int maxOverride = zone.MaxOverride ?? -1;
                        int sharedMaxOverride = zone.SharedMaxOverride ?? -1;
                        int spawnGroupId = zone.SpawnGroupId ?? -1;
                        sb.AppendLine($"        call GNI_RegisterZoneAssignment(defId, {zone.ZoneId}, {spawnModeInt}, {spawnGroupId}, {weightOverride}, {maxOverride}, {sharedMaxOverride})  // {zone.ZoneName}");
                        result.ZoneAssignmentsExported++;
                    }

                    sb.AppendLine();
                    result.ItemNodesExported++;
                }
            }
            
            sb.AppendLine("    endfunction");
            sb.AppendLine();

            // RegisterUnitNodes function
            sb.AppendLine("    //===========================================================================");
            sb.AppendLine("    // UNIT NODE DEFINITIONS (Ore Veins, Crystal Veins, Fish Pools, etc.)");
            sb.AppendLine("    //===========================================================================");
            sb.AppendLine("    private function RegisterUnitNodes takes nothing returns nothing");
            sb.AppendLine("        local integer defId");
            sb.AppendLine();

            var orderedUnitCategories = categories
                .Where(c => c.Enabled && c.NodeType == "unit")
                .OrderBy(c => c.DisplayOrder)
                .ThenBy(c => c.CategoryName)
                .ToList();

            foreach (var category in orderedUnitCategories)
            {
                var categoryNodes = unitNodes
                    .Where(n => n.CategoryId == category.Id)
                    .OrderBy(n => n.DisplayOrder)
                    .ThenBy(n => n.NodeName)
                    .ToList();

                if (!categoryNodes.Any())
                {
                    continue;
                }

                sb.AppendLine($"        // === {category.CategoryName.ToUpper()} ===");
                
                foreach (var node in categoryNodes)
                {
                    string glowEffect = node.GlowEffect ? "true" : "false";
                    string preventWaterSpawn = node.PreventWaterSpawn ? "true" : "false";
                    string isRare = node.IsRare ? "true" : "false";
                    
                    sb.AppendLine($"        // {node.NodeName}");
                    sb.AppendLine($"        set defId = GNU_RegisterDefinition('{node.UnitCode}', \"{node.NodeName}\", {node.CategoryId ?? 0}, {node.SpawnWeight}, {node.RespawnTimeMin.ToString("F1", CultureInfo.InvariantCulture)}, {node.RespawnTimeMax.ToString("F1", CultureInfo.InvariantCulture)}, {node.MaxPerZone}, {node.SkillRequired}, {node.ProfessionId}, {node.HarvestYieldMin}, {node.HarvestYieldMax}, {node.GatherSuccessChancePercent}, {node.MainDropGroupChancePercent}, {node.SecondaryDropGroupChancePercent}, {node.SpecialBehaviorId}, {node.SpecialBehaviorChancePercent}, {node.OwnerPlayer}, {preventWaterSpawn}, {glowEffect}, {node.GlowColorR}, {node.GlowColorG}, {node.GlowColorB}, {node.GlowAlpha}, {node.GlowScale.ToString("F1", CultureInfo.InvariantCulture)}, {node.GlowHeight.ToString("F1", CultureInfo.InvariantCulture)}, {isRare})");
                    
                    // Export zone assignments for this node
                    var zones = _repository.GetZoneAssignmentsByNode("unit", node.Id).Where(z => z.Enabled).ToList();
                    foreach (var zone in zones)
                    {
                        int spawnModeInt = GetSpawnModeInt(zone.SpawnMode);
                        int weightOverride = zone.WeightOverride ?? -1;
                        int maxOverride = zone.MaxOverride ?? -1;
                        int sharedMaxOverride = zone.SharedMaxOverride ?? -1;
                        int spawnGroupId = zone.SpawnGroupId ?? -1;
                        sb.AppendLine($"        call GNU_RegisterZoneAssignment(defId, {zone.ZoneId}, {spawnModeInt}, {spawnGroupId}, {weightOverride}, {maxOverride}, {sharedMaxOverride})  // {zone.ZoneName}");
                        result.ZoneAssignmentsExported++;
                    }
                    
                    sb.AppendLine();
                    result.UnitNodesExported++;
                }
            }

            var uncategorizedUnits = unitNodes
                .Where(n => !n.CategoryId.HasValue)
                .OrderBy(n => n.DisplayOrder)
                .ThenBy(n => n.NodeName)
                .ToList();

            if (uncategorizedUnits.Any())
            {
                sb.AppendLine("        // === UNCATEGORIZED ===");
                foreach (var node in uncategorizedUnits)
                {
                    string glowEffect = node.GlowEffect ? "true" : "false";
                    string preventWaterSpawn = node.PreventWaterSpawn ? "true" : "false";
                    string isRare = node.IsRare ? "true" : "false";

                    sb.AppendLine($"        // {node.NodeName}");
                    sb.AppendLine($"        set defId = GNU_RegisterDefinition('{node.UnitCode}', \"{node.NodeName}\", {node.CategoryId ?? 0}, {node.SpawnWeight}, {node.RespawnTimeMin.ToString("F1", CultureInfo.InvariantCulture)}, {node.RespawnTimeMax.ToString("F1", CultureInfo.InvariantCulture)}, {node.MaxPerZone}, {node.SkillRequired}, {node.ProfessionId}, {node.HarvestYieldMin}, {node.HarvestYieldMax}, {node.GatherSuccessChancePercent}, {node.MainDropGroupChancePercent}, {node.SecondaryDropGroupChancePercent}, {node.SpecialBehaviorId}, {node.SpecialBehaviorChancePercent}, {node.OwnerPlayer}, {preventWaterSpawn}, {glowEffect}, {node.GlowColorR}, {node.GlowColorG}, {node.GlowColorB}, {node.GlowAlpha}, {node.GlowScale.ToString("F1", CultureInfo.InvariantCulture)}, {node.GlowHeight.ToString("F1", CultureInfo.InvariantCulture)}, {isRare})");

                    var zones = _repository.GetZoneAssignmentsByNode("unit", node.Id).Where(z => z.Enabled).ToList();
                    foreach (var zone in zones)
                    {
                        int spawnModeInt = GetSpawnModeInt(zone.SpawnMode);
                        int weightOverride = zone.WeightOverride ?? -1;
                        int maxOverride = zone.MaxOverride ?? -1;
                        int sharedMaxOverride = zone.SharedMaxOverride ?? -1;
                        int spawnGroupId = zone.SpawnGroupId ?? -1;
                        sb.AppendLine($"        call GNU_RegisterZoneAssignment(defId, {zone.ZoneId}, {spawnModeInt}, {spawnGroupId}, {weightOverride}, {maxOverride}, {sharedMaxOverride})  // {zone.ZoneName}");
                        result.ZoneAssignmentsExported++;
                    }

                    sb.AppendLine();
                    result.UnitNodesExported++;
                }
            }
            
            sb.AppendLine("    endfunction");
            sb.AppendLine();

            sb.AppendLine("    private function RegisterUnitNodeDrops takes nothing returns nothing");
            sb.AppendLine("        local integer defId");
            sb.AppendLine();
            foreach (var category in orderedUnitCategories)
            {
                var categoryNodes = unitNodes
                    .Where(n => n.CategoryId == category.Id)
                    .OrderBy(n => n.DisplayOrder)
                    .ThenBy(n => n.NodeName)
                    .ToList();

                foreach (var node in categoryNodes)
                {
                    var drops = _repository.GetUnitNodeDrops(node.Id).Where(d => d.Enabled).OrderBy(d => d.DisplayOrder).ThenBy(d => d.ItemName).ToList();
                    if (!drops.Any())
                    {
                        continue;
                    }

                    sb.AppendLine($"        // Rewards: {node.NodeName}");
                    sb.AppendLine($"        set defId = GNU_GetDefinitionIdByUnitCode('{node.UnitCode}')");
                    foreach (var drop in drops)
                    {
                        sb.AppendLine($"        call GNU_RegisterDrop(defId, \"{EscapeString(drop.GroupName)}\", '{drop.ItemCode}', {drop.DropChancePercent}, {drop.Weight}, {drop.MinQuantity}, {drop.MaxQuantity}, true)");
                    }
                    sb.AppendLine();
                }
            }

            foreach (var node in uncategorizedUnits)
            {
                var drops = _repository.GetUnitNodeDrops(node.Id).Where(d => d.Enabled).OrderBy(d => d.DisplayOrder).ThenBy(d => d.ItemName).ToList();
                if (!drops.Any())
                {
                    continue;
                }

                sb.AppendLine($"        // Rewards: {node.NodeName}");
                sb.AppendLine($"        set defId = GNU_GetDefinitionIdByUnitCode('{node.UnitCode}')");
                foreach (var drop in drops)
                {
                    sb.AppendLine($"        call GNU_RegisterDrop(defId, \"{EscapeString(drop.GroupName)}\", '{drop.ItemCode}', {drop.DropChancePercent}, {drop.Weight}, {drop.MinQuantity}, {drop.MaxQuantity}, true)");
                }
                sb.AppendLine();
            }
            sb.AppendLine("    endfunction");
            sb.AppendLine();

            sb.AppendLine("    private function RegisterSpawnGroups takes nothing returns nothing");
            var spawnGroups = _repository.GetAllSpawnPointGroups().Where(g => g.Enabled).OrderBy(g => g.ZoneId).ThenBy(g => g.GroupName).ToList();
            var spawnPoints = _repository.GetAllSpawnPoints().Where(p => p.Enabled).ToList();
            if (spawnGroups.Any())
            {
                foreach (var group in spawnGroups)
                {
                    var groupPoints = spawnPoints
                        .Where(p => p.SpawnGroupId == group.Id)
                        .OrderBy(p => p.SpawnPointIndex ?? int.MaxValue)
                        .ThenBy(p => p.PointName)
                        .ToList();

                    sb.AppendLine($"        // Group {group.Id}: {group.GroupName} ({group.ZoneName})");
                    foreach (var point in groupPoints)
                    {
                        if (IsExplicitItemPoint(point))
                        {
                            sb.AppendLine($"        call GNI_RegisterGroupRegion({group.Id}, {point.RegionVariable})  // {point.PointName}");
                            result.SpawnPointsExported++;
                        }

                        if (point.NodeType == "unit" || point.NodeType == "both")
                        {
                            sb.AppendLine($"        call GNU_RegisterSpawnPoint({group.Id}, {point.ZoneId}, GetRectCenterX({point.RegionVariable}), GetRectCenterY({point.RegionVariable}), 270.0, -1, {InferUnitSpawnCategoryFilter(point, unitCategoryLookup)})  // {point.PointName}");
                            result.SpawnPointsExported++;
                        }
                    }
                    sb.AppendLine();
                }
            }
            sb.AppendLine("    endfunction");
            sb.AppendLine();

            sb.AppendLine("    //===========================================================================");
            sb.AppendLine("    // RANDOM IN ZONE");
            sb.AppendLine("    // Random zone placements use ZonesCore zone rects at runtime.");
            sb.AppendLine("    // No extra gather-zone rect registration is exported here.");
            sb.AppendLine("    //===========================================================================");
            sb.AppendLine("    private function RegisterSpawnRegions takes nothing returns nothing");
            sb.AppendLine("        // Intentionally empty.");
            sb.AppendLine("    endfunction");
            sb.AppendLine();

            // Init function
            sb.AppendLine("    //===========================================================================");
            sb.AppendLine("    // INITIALIZATION");
            sb.AppendLine("    //===========================================================================");
            sb.AppendLine("    private function DelayedSpawn takes nothing returns nothing");
            sb.AppendLine("        // Spawn initial nodes after definitions and rect-backed registrations are in place");
            sb.AppendLine("        call GNI_SpawnInitialAll()");
            sb.AppendLine("        call GNU_SpawnInitialAll()");
            sb.AppendLine();
            sb.AppendLine("        if GN_IsDebugMode() then");
            sb.AppendLine("            call BJDebugMsg(\"|cff00ff00[GatherNodeDefinitions]|r All nodes spawned\")");
            sb.AppendLine("        endif");
            sb.AppendLine("    endfunction");
            sb.AppendLine();
            sb.AppendLine("    private function DelayedInit takes nothing returns nothing");
            sb.AppendLine("        // Register all definitions");
            sb.AppendLine("        call RegisterItemNodes()");
            sb.AppendLine("        call RegisterUnitNodes()");
            sb.AppendLine("        call RegisterUnitNodeDrops()");
            sb.AppendLine("        call RegisterSpawnRegions()");
            sb.AppendLine("        call RegisterSpawnGroups()");
            sb.AppendLine();
            sb.AppendLine("        set GND_SpawnTrigger = CreateTrigger()");
            sb.AppendLine("        call TriggerRegisterTimerEvent(GND_SpawnTrigger, 0.10, false)");
            sb.AppendLine("        call TriggerAddAction(GND_SpawnTrigger, function DelayedSpawn)");
            sb.AppendLine();
            sb.AppendLine("        if GN_IsDebugMode() then");
            sb.AppendLine("            call BJDebugMsg(\"|cff00ff00[GatherNodeDefinitions]|r All nodes registered\")");
            sb.AppendLine("        endif");
            sb.AppendLine("    endfunction");
            sb.AppendLine();
            sb.AppendLine("    private function Init takes nothing returns nothing");
            sb.AppendLine("        set GND_InitTrigger = CreateTrigger()");
            sb.AppendLine("        call TriggerRegisterTimerEvent(GND_InitTrigger, 0.00, false)");
            sb.AppendLine("        call TriggerAddAction(GND_InitTrigger, function DelayedInit)");
            sb.AppendLine("    endfunction");
            sb.AppendLine();
            sb.AppendLine("endlibrary");

            // Write to file
            File.WriteAllText(outputPath, sb.ToString());
        }

        /// <summary>
        /// Convert spawn mode string to integer
        /// </summary>
        private int GetSpawnModeInt(string spawnMode)
        {
            return NormalizeSpawnMode(spawnMode) switch
            {
                "random" => 0,
                "fixed" => 1,
                "both" => 2,
                _ => 0
            };
        }

        private bool IsExplicitItemPoint(GatherSpawnPoint point)
        {
            return string.Equals(point?.NodeType, "item", StringComparison.OrdinalIgnoreCase)
                || string.Equals(point?.NodeType, "both", StringComparison.OrdinalIgnoreCase);
        }

        private string NormalizeSpawnMode(string spawnMode)
        {
            return spawnMode?.Trim().ToLowerInvariant() switch
            {
                "random" => "random",
                "random in zone" => "random",
                "random in zone (zonescore)" => "random",
                "fixed" => "fixed",
                "spawn group" => "fixed",
                "both" => "both",
                "spawn group + random" => "both",
                "spawn group + zone random fallback" => "both",
                _ => "random"
            };
        }

        private string EscapeString(string value)
        {
            return (value ?? string.Empty).Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        private Dictionary<string, int> BuildUnitCategoryLookup(IEnumerable<GatherNodeCategory> categories)
        {
            return categories
                .Where(c => c.Enabled && string.Equals(c.NodeType, "unit", StringComparison.OrdinalIgnoreCase))
                .GroupBy(c => NormalizeCategoryName(c.CategoryName))
                .ToDictionary(g => g.Key, g => g.First().Id);
        }

        private int InferUnitSpawnCategoryFilter(GatherSpawnPoint point, IReadOnlyDictionary<string, int> unitCategoryLookup)
        {
            string combined = ((point?.PointName ?? string.Empty) + " " + (point?.RegionVariable ?? string.Empty)).ToLowerInvariant();

            if (combined.Contains("crystal"))
            {
                return GetCategoryId(unitCategoryLookup, "Crystal Veins");
            }

            if (combined.Contains("ore") || combined.Contains("vein"))
            {
                return GetCategoryId(unitCategoryLookup, "Ore Veins");
            }

            if (combined.Contains("fish") || combined.Contains("pool"))
            {
                return GetCategoryId(unitCategoryLookup, "Fish Pools");
            }

            if (combined.Contains("treasure") || combined.Contains("chest"))
            {
                return GetCategoryId(unitCategoryLookup, "Treasure Chests");
            }

            return -1;
        }

        private int GetCategoryId(IReadOnlyDictionary<string, int> unitCategoryLookup, string categoryName)
        {
            if (unitCategoryLookup.TryGetValue(NormalizeCategoryName(categoryName), out int categoryId))
            {
                return categoryId;
            }

            return -1;
        }

        private string NormalizeCategoryName(string value)
        {
            return (value ?? string.Empty).Trim().ToLowerInvariant();
        }
    }

    /// <summary>
    /// Result of gather node export operation
    /// </summary>
    public class GatherNodeExportResult
    {
        public bool Success { get; set; }
        public string ErrorMessage { get; set; }
        public List<string> FilesExported { get; set; } = new List<string>();
        public int ItemNodesExported { get; set; }
        public int UnitNodesExported { get; set; }
        public int ZoneAssignmentsExported { get; set; }
        public int SpawnPointsExported { get; set; }
    }
}
