using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Npgsql;
using WC3ItemManager.Models;
using WC3ItemManager.Repositories;

namespace WC3ItemManager.Exporters
{
    /// <summary>
    /// Exports ItemLootSystem JASS libraries from database
    /// </summary>
    public class LootSystemExporter
    {
        private readonly string _connectionString;
        private readonly LootTierRepository _tierRepo;
        private readonly UnitSpecificDropRepository _dropRepo;
        private readonly DestructibleSpecificDropRepository _destDropRepo;
        private readonly DestructibleTypeRepository _destTypeRepo;
        private readonly LootTableRepository _tableRepo;
        private readonly LootTableItemRepository _tableItemRepo;

        public LootSystemExporter(string connectionString)
        {
            _connectionString = connectionString;
            _tierRepo = new LootTierRepository(connectionString);
            _dropRepo = new UnitSpecificDropRepository(connectionString);
            _destDropRepo = new DestructibleSpecificDropRepository(connectionString);
            _destTypeRepo = new DestructibleTypeRepository(connectionString);
            _tableRepo = new LootTableRepository(connectionString);
            _tableItemRepo = new LootTableItemRepository(connectionString);
        }

        /// <summary>
        /// Export all loot system JASS files
        /// </summary>
        public ExportResult ExportAll(string outputFolder)
        {
            var result = new ExportResult();
            
            try
            {
                // Ensure output folder exists
                if (!Directory.Exists(outputFolder))
                {
                    Directory.CreateDirectory(outputFolder);
                }

                // Timestamp for filenames
                string timestamp = DateTime.Now.ToString("yyyyMMdd_HHmmss");

                // Export generic definitions (tiers + item pools)
                string genericPath = Path.Combine(outputFolder, $"ItemLootDefinitionsGeneric_{timestamp}.j");
                ExportGenericDefinitions(genericPath);
                result.FilesExported.Add(genericPath);

                // Export specific definitions (boss drops)
                string specificPath = Path.Combine(outputFolder, $"ItemLootDefinitionsSpecific_{timestamp}.j");
                int bossCount = ExportSpecificDefinitions(specificPath);
                result.FilesExported.Add(specificPath);

                // Export destructible definitions
                string destructiblePath = Path.Combine(outputFolder, $"ItemLootDefinitionsDestructible_{timestamp}.j");
                int destCount = ExportDestructibleDefinitions(destructiblePath);
                result.FilesExported.Add(destructiblePath);

                result.Success = true;
                result.TiersExported = _tierRepo.GetAll().Count;
                result.SpecificDropsExported = bossCount;
                result.DestructibleDropsExported = destCount;

                Logger.Instance.Info($"Loot system exported: {result.TiersExported} tiers, {result.SpecificDropsExported} specific drops, {result.DestructibleDropsExported} destructible drops");
            }
            catch (Exception ex)
            {
                result.Success = false;
                result.ErrorMessage = ex.Message;
                Logger.Instance.Error("Failed to export loot system", ex);
            }

            return result;
        }

        /// <summary>
        /// Export generic loot definitions (tiers and item level configuration)
        /// </summary>
        private void ExportGenericDefinitions(string outputPath)
        {
            var tiers = _tierRepo.GetAll().Where(t => t.Enabled).ToList();
            var sb = new StringBuilder();

            // Header
            sb.AppendLine("//===========================================================================");
            sb.AppendLine("// ItemLootDefinitionsGeneric.j");
            sb.AppendLine("// Generated by WC3ItemManager - DO NOT EDIT MANUALLY");
            sb.AppendLine($"// Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine("//===========================================================================");
            sb.AppendLine();
            sb.AppendLine("library ItemLootDefinitionsGeneric initializer Init requires ItemLootSystem");
            sb.AppendLine();

            // ============================================================
            // JASS requires functions to be defined BEFORE they are called
            // Order: RegisterItemPools -> RegisterAllTiers -> Init
            // ============================================================

            // RegisterItemPools function - loads items from database (must be defined first)
            sb.AppendLine("    private function RegisterItemPools takes nothing returns nothing");
            sb.AppendLine("        // RegisterItemToPool(itemTypeId, itemLevel, rarityId, weight, isUnique)");
            sb.AppendLine();

            // Get all items that can drop
            var items = GetDroppableItems();
            var itemsByRarity = items.GroupBy(i => i.RarityId).OrderBy(g => g.Key);

            foreach (var rarityGroup in itemsByRarity)
            {
                string rarityName = GetRarityConstant(rarityGroup.Key);
                sb.AppendLine($"        // === {rarityName} ITEMS ===");
                
                var itemsByLevel = rarityGroup.GroupBy(i => i.ItemLevel).OrderBy(g => g.Key);
                foreach (var levelGroup in itemsByLevel)
                {
                    sb.AppendLine($"        // Level {levelGroup.Key}");
                    foreach (var item in levelGroup)
                    {
                        string isUnique = item.IsUnique ? "true" : "false";
                        sb.AppendLine($"        call RegisterItemToPool('{item.ItemCode}', {item.ItemLevel}, {rarityName}, 100, {isUnique})  // {item.ItemName}");
                    }
                }
                sb.AppendLine();
            }

            sb.AppendLine("    endfunction");
            sb.AppendLine();

            // RegisterAllTiers function (calls RegisterItemPools, so must be defined after it)
            sb.AppendLine("    private function RegisterAllTiers takes nothing returns nothing");
            sb.AppendLine("        call DestroyTimer(GetExpiredTimer())");
            sb.AppendLine();

            // Register tiers
            sb.AppendLine("        // === LOOT TIER DEFINITIONS ===");
            sb.AppendLine("        // RegisterLootTier(tierId, minLevel, maxLevel, dropChance)");
            sb.AppendLine("        // RegisterTierRarity(tierId, rarityId, itemLevel, weight)");
            sb.AppendLine();

            int tierId = 1;
            foreach (var tier in tiers)
            {
                sb.AppendLine($"        // {tier.TierName}: Units level {tier.MinUnitLevel}-{tier.MaxUnitLevel}");
                sb.AppendLine($"        call RegisterLootTier({tierId}, {tier.MinUnitLevel}, {tier.MaxUnitLevel}, {(int)(tier.DropChanceBase * 100)})");
                
                // Register each rarity with weight > 0 (use ITEM_RARITY_* to avoid Blizzard common.j collision)
                if (tier.CommonWeight > 0 && tier.CommonItemLevel.HasValue)
                    sb.AppendLine($"        call RegisterTierRarity({tierId}, ITEM_RARITY_COMMON, {tier.CommonItemLevel}, {tier.CommonWeight})");
                if (tier.UncommonWeight > 0 && tier.UncommonItemLevel.HasValue)
                    sb.AppendLine($"        call RegisterTierRarity({tierId}, ITEM_RARITY_UNCOMMON, {tier.UncommonItemLevel}, {tier.UncommonWeight})");
                if (tier.RareWeight > 0 && tier.RareItemLevel.HasValue)
                    sb.AppendLine($"        call RegisterTierRarity({tierId}, ITEM_RARITY_RARE, {tier.RareItemLevel}, {tier.RareWeight})");
                if (tier.EpicWeight > 0 && tier.EpicItemLevel.HasValue)
                    sb.AppendLine($"        call RegisterTierRarity({tierId}, ITEM_RARITY_EPIC, {tier.EpicItemLevel}, {tier.EpicWeight})");
                if (tier.LegendaryWeight > 0 && tier.LegendaryItemLevel.HasValue)
                    sb.AppendLine($"        call RegisterTierRarity({tierId}, ITEM_RARITY_LEGENDARY, {tier.LegendaryItemLevel}, {tier.LegendaryWeight})");
                if (tier.ArtifactWeight > 0 && tier.ArtifactItemLevel.HasValue)
                    sb.AppendLine($"        call RegisterTierRarity({tierId}, ITEM_RARITY_ARTIFACT, {tier.ArtifactItemLevel}, {tier.ArtifactWeight})");
                
                sb.AppendLine();
                tierId++;
            }

            // Register item pools from database
            sb.AppendLine("        // === ITEM POOL REGISTRATION ===");
            sb.AppendLine("        call RegisterItemPools()");
            sb.AppendLine("    endfunction");
            sb.AppendLine();

            // Init function (uses timer callback to RegisterAllTiers, must be defined last)
            sb.AppendLine("    private function Init takes nothing returns nothing");
            sb.AppendLine("        // Tier registration delayed to allow ItemLootSystem to initialize");
            sb.AppendLine("        call TimerStart(CreateTimer(), 0.01, false, function RegisterAllTiers)");
            sb.AppendLine("    endfunction");
            sb.AppendLine();
            sb.AppendLine("endlibrary");

            File.WriteAllText(outputPath, sb.ToString(), Encoding.UTF8);
        }

        /// <summary>
        /// Export specific (boss) drop definitions
        /// </summary>
        private int ExportSpecificDefinitions(string outputPath)
        {
            var drops = _dropRepo.GetAllEnabled();
            var sb = new StringBuilder();

            // Header
            sb.AppendLine("//===========================================================================");
            sb.AppendLine("// ItemLootDefinitionsSpecific.j");
            sb.AppendLine("// Generated by WC3ItemManager - DO NOT EDIT MANUALLY");
            sb.AppendLine($"// Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine("//===========================================================================");
            sb.AppendLine();
            sb.AppendLine("library ItemLootDefinitionsSpecific initializer Init requires ItemLootSystem");
            sb.AppendLine();

            // ============================================================
            // JASS requires functions to be defined BEFORE they are called
            // Order: RegisterAllSpecificDrops -> Init
            // ============================================================

            // RegisterAllSpecificDrops function (must be defined before Init references it)
            sb.AppendLine("    private function RegisterAllSpecificDrops takes nothing returns nothing");
            sb.AppendLine("        call DestroyTimer(GetExpiredTimer())");
            sb.AppendLine();
            sb.AppendLine("        // === SPECIFIC/BOSS DROP DEFINITIONS ===");
            sb.AppendLine("        // RegisterSpecificDrop(unitTypeId, itemTypeId, dropChance, isGuaranteed, weight)");
            sb.AppendLine();

            // Group by unit
            var dropsByUnit = drops.GroupBy(d => d.UnitCode);
            
            foreach (var unitGroup in dropsByUnit)
            {
                var firstDrop = unitGroup.First();
                sb.AppendLine($"        // {firstDrop.UnitName} ('{unitGroup.Key}')");
                
                foreach (var drop in unitGroup)
                {
                    string isGuaranteed = drop.IsGuaranteed ? "true" : "false";
                    int dropChance = (int)(drop.DropChance * 100);
                    sb.AppendLine($"        call RegisterSpecificDrop('{drop.UnitCode}', '{drop.ItemCode}', {dropChance}, {isGuaranteed}, {drop.Weight})  // {drop.ItemName}");
                }
                sb.AppendLine();
            }

            sb.AppendLine("    endfunction");
            sb.AppendLine();

            // Init function (uses timer callback to RegisterAllSpecificDrops, must be defined last)
            sb.AppendLine("    private function Init takes nothing returns nothing");
            sb.AppendLine("        // Specific drop registration delayed to allow ItemLootSystem to initialize");
            sb.AppendLine("        call TimerStart(CreateTimer(), 0.02, false, function RegisterAllSpecificDrops)");
            sb.AppendLine("    endfunction");
            sb.AppendLine();
            sb.AppendLine("endlibrary");

            File.WriteAllText(outputPath, sb.ToString(), Encoding.UTF8);
            
            return drops.Count;
        }

        /// <summary>
        /// Export destructible-specific drop definitions and levels for generic drops
        /// </summary>
        private int ExportDestructibleDefinitions(string outputPath)
        {
            var drops = _destDropRepo.GetAllEnabled();
            var destructibles = _destTypeRepo.GetAll().Where(d => d.Enabled).ToList();
            var lootTables = _tableRepo.GetAll().ToDictionary(t => t.Id);
            var sb = new StringBuilder();

            // Header
            sb.AppendLine("//===========================================================================");
            sb.AppendLine("// ItemLootDefinitionsDestructible.j");
            sb.AppendLine("// Generated by WC3ItemManager - DO NOT EDIT MANUALLY");
            sb.AppendLine($"// Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine("//===========================================================================");
            sb.AppendLine();
            sb.AppendLine("library ItemLootDefinitionsDestructible initializer Init requires ItemLootDestructibles");
            sb.AppendLine();

            // ============================================================
            // JASS requires functions to be defined BEFORE they are called
            // Order: RegisterAllDestructibleDrops -> Init
            // ============================================================

            // RegisterAllDestructibleDrops function (must be defined before Init references it)
            sb.AppendLine("    private function RegisterAllDestructibleDrops takes nothing returns nothing");
            sb.AppendLine("        call DestroyTimer(GetExpiredTimer())");
            sb.AppendLine();

            // Export destructible levels for Generic and Both modes
            var genericDestructibles = destructibles
                .Where(d => d.LootMode == LootMode.Generic || d.LootMode == LootMode.Both)
                .OrderBy(d => d.DestructibleLevel)
                .ThenBy(d => d.DestructibleCode)
                .ToList();

            if (genericDestructibles.Any())
            {
                sb.AppendLine("        // === DESTRUCTIBLE LEVELS (for Generic drops) ===");
                sb.AppendLine("        // RegisterDestructibleLevel(destructibleTypeId, level)");
                sb.AppendLine();

                foreach (var dest in genericDestructibles)
                {
                    sb.AppendLine($"        call RegisterDestructibleLevel('{dest.DestructibleCode}', {dest.DestructibleLevel})  // {dest.DisplayName}");
                }
                sb.AppendLine();
            }

            var tableAssignedDestructibles = destructibles
                .Where(d => (d.LootMode == LootMode.Specific || d.LootMode == LootMode.Both) && d.LootTableId.HasValue)
                .OrderBy(d => d.DestructibleCode)
                .ToList();

            if (tableAssignedDestructibles.Any())
            {
                sb.AppendLine("        // === DESTRUCTIBLE LOOT TABLE SETTINGS ===");
                sb.AppendLine("        // RegisterDestructibleTable(destructibleTypeId, dropChance, dropCountMin, dropCountMax)");
                sb.AppendLine();

                foreach (var dest in tableAssignedDestructibles)
                {
                    if (!lootTables.TryGetValue(dest.LootTableId!.Value, out var lootTable) || !lootTable.Enabled)
                    {
                        continue;
                    }

                    int dropChance = dest.DropChanceOverride.HasValue
                        ? (int)(dest.DropChanceOverride.Value * 100)
                        : lootTable.DropChance;
                    int dropCountMin = dest.DropCountMin;
                    int dropCountMax = dest.DropCountMax;

                    sb.AppendLine($"        call RegisterDestructibleTable('{dest.DestructibleCode}', {dropChance}, {dropCountMin}, {dropCountMax})  // {lootTable.Name}");
                }
                sb.AppendLine();
            }

            // Export specific drops for Specific and Both modes
            sb.AppendLine("        // === DESTRUCTIBLE SPECIFIC DROPS ===");
            sb.AppendLine("        // RegisterDestructibleDropEx(destructibleTypeId, itemTypeId, dropChance, isGuaranteed, weight, quantityMin, quantityMax)");
            sb.AppendLine();

            foreach (var dest in tableAssignedDestructibles)
            {
                if (!lootTables.TryGetValue(dest.LootTableId!.Value, out var lootTable) || !lootTable.Enabled)
                {
                    continue;
                }

                var tableItems = _tableItemRepo.GetByLootTableId(dest.LootTableId.Value);
                if (tableItems.Count == 0)
                {
                    continue;
                }

                sb.AppendLine($"        // {dest.DisplayName} -> loot table '{lootTable.Name}'");

                foreach (var item in tableItems)
                {
                    string isGuaranteed = item.IsGuaranteed ? "true" : "false";
                    sb.AppendLine($"        call RegisterDestructibleDropEx('{dest.DestructibleCode}', '{item.ItemCode}', {item.DropChance}, {isGuaranteed}, {item.Weight}, {item.QuantityMin}, {item.QuantityMax})  // {item.ItemName}");
                }
                sb.AppendLine();
            }

            // Group by destructible
            var tableAssignedCodes = new HashSet<string>(tableAssignedDestructibles.Select(d => d.DestructibleCode));
            var dropsByDestructible = drops
                .Where(d => !tableAssignedCodes.Contains(d.DestructibleCode))
                .GroupBy(d => d.DestructibleCode);
            
            foreach (var destGroup in dropsByDestructible)
            {
                sb.AppendLine($"        // Destructible '{destGroup.Key}'");
                
                foreach (var drop in destGroup)
                {
                    string isGuaranteed = drop.IsGuaranteed ? "true" : "false";
                    int dropChance = (int)(drop.DropChance * 100);
                    sb.AppendLine($"        call RegisterDestructibleDropEx('{drop.DestructibleCode}', '{drop.ItemCode}', {dropChance}, {isGuaranteed}, {drop.Weight}, {drop.MinQuantity}, {drop.MaxQuantity})");
                }
                sb.AppendLine();
            }

            sb.AppendLine("    endfunction");
            sb.AppendLine();

            // Init function (uses timer callback to RegisterAllDestructibleDrops, must be defined last)
            sb.AppendLine("    private function Init takes nothing returns nothing");
            sb.AppendLine("        // Destructible drop registration delayed to allow ItemLootDestructibles to initialize");
            sb.AppendLine("        call TimerStart(CreateTimer(), 0.03, false, function RegisterAllDestructibleDrops)");
            sb.AppendLine("    endfunction");
            sb.AppendLine();
            sb.AppendLine("endlibrary");

            File.WriteAllText(outputPath, sb.ToString(), Encoding.UTF8);
            
            int tableItemCount = tableAssignedDestructibles
                .Where(d => d.LootTableId.HasValue && lootTables.ContainsKey(d.LootTableId.Value) && lootTables[d.LootTableId.Value].Enabled)
                .Sum(d => _tableItemRepo.GetByLootTableId(d.LootTableId!.Value).Count);

            return genericDestructibles.Count + drops.Count + tableItemCount;
        }

        /// <summary>
        /// Get all items that can drop (have item_level and rarity set, not specific_drop_only)
        /// </summary>
        private List<DroppableItem> GetDroppableItems()
        {
            var items = new List<DroppableItem>();
            
            using (var conn = new NpgsqlConnection(_connectionString))
            {
                conn.Open();
                using (var cmd = new NpgsqlCommand(@"
                    SELECT i.item_code, i.item_name, 
                           COALESCE(i.item_level_unclassified, i.item_level) as item_level,
                           i.rarity_id, COALESCE(i.is_unique, false) as is_unique
                    FROM items i
                    WHERE i.rarity_id IS NOT NULL 
                      AND (i.item_level IS NOT NULL OR i.item_level_unclassified IS NOT NULL)
                      AND COALESCE(i.specific_drop_only, false) = false
                    ORDER BY i.rarity_id, COALESCE(i.item_level_unclassified, i.item_level)", conn))
                {
                    using (var reader = cmd.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            items.Add(new DroppableItem
                            {
                                ItemCode = reader.GetString(0),
                                ItemName = reader.GetString(1),
                                ItemLevel = reader.GetInt32(2),
                                RarityId = reader.GetInt32(3),
                                IsUnique = reader.GetBoolean(4)
                            });
                        }
                    }
                }
            }
            
            return items;
        }

        private string GetRarityConstant(int rarityId)
        {
            // Use ITEM_RARITY_* to avoid conflict with Blizzard's RARITY_RARE
            return rarityId switch
            {
                0 => "ITEM_RARITY_COMMON",
                1 => "ITEM_RARITY_UNCOMMON",
                2 => "ITEM_RARITY_RARE",
                3 => "ITEM_RARITY_EPIC",
                4 => "ITEM_RARITY_LEGENDARY",
                5 => "ITEM_RARITY_ARTIFACT",
                _ => "ITEM_RARITY_COMMON"
            };
        }

        private class DroppableItem
        {
            public string ItemCode { get; set; }
            public string ItemName { get; set; }
            public int ItemLevel { get; set; }
            public int RarityId { get; set; }
            public bool IsUnique { get; set; }
        }
    }

    /// <summary>
    /// Result of loot system export operation
    /// </summary>
    public class ExportResult
    {
        public bool Success { get; set; }
        public string ErrorMessage { get; set; }
        public List<string> FilesExported { get; set; } = new List<string>();
        public int TiersExported { get; set; }
        public int SpecificDropsExported { get; set; }
        public int DestructibleDropsExported { get; set; }
    }
}
