//===========================================================================
// ItemLootDefinitionsGeneric.j
// Generated by WC3ItemManager - DO NOT EDIT MANUALLY
// Generated: 2026-04-13 02.19.43
//===========================================================================

library ItemLootDefinitionsGeneric initializer Init requires ItemLootSystem

    private function RegisterItemPools takes nothing returns nothing
        // RegisterItemToPool(itemTypeId, itemLevel, rarityId, weight, isUnique)

        // === ITEM_RARITY_UNCOMMON ITEMS ===
        // Level 0
        call RegisterItemToPool('I013', 0, ITEM_RARITY_UNCOMMON, 100, false)  // |cffffff00Tel’anor Rod|r
        // Level 1
        call RegisterItemToPool('I6A2', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Reincarnation
        call RegisterItemToPool('I6A3', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Stoneskin Totem
        call RegisterItemToPool('I6A4', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Gnoll Pillage
        call RegisterItemToPool('I6A5', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Orb of Lifesteal
        call RegisterItemToPool('I6AC', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Frost Shock
        call RegisterItemToPool('I6AD', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Nature Shock
        call RegisterItemToPool('I6AF', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Rejuvenation
        call RegisterItemToPool('I6AG', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Totemic Resurgence
        call RegisterItemToPool('I6AH', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Totemist
        call RegisterItemToPool('I6A0', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Feral Spirits
        call RegisterItemToPool('I65I', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Astral Ebon Mantle
        call RegisterItemToPool('I65J', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Rusty Dagger
        call RegisterItemToPool('I65P', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Mystic Orb
        call RegisterItemToPool('I65Q', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Shadow Cloak
        call RegisterItemToPool('I65R', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Hammer of the Ancients
        call RegisterItemToPool('I65S', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Gleaming Plate Armor
        call RegisterItemToPool('I65T', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Arcane Staff of Elements
        call RegisterItemToPool('I65U', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Celestial Gauntlets
        call RegisterItemToPool('I65V', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Celestial Robes
        call RegisterItemToPool('I65W', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Swift Boots of Agility
        call RegisterItemToPool('I663', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Crown of Celestial Mastery
        call RegisterItemToPool('I664', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Starforged Battleaxe
        call RegisterItemToPool('I665', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Dragonhide Cloak of the Serpent
        call RegisterItemToPool('I666', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Blade of the Eternal
        call RegisterItemToPool('I667', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Phoenix Feather Talisman
        call RegisterItemToPool('I668', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Tattered Leather Boots
        call RegisterItemToPool('I669', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Tattered Leather Gloves
        call RegisterItemToPool('I66A', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Tattered Leather Shoulderpads
        call RegisterItemToPool('I66B', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Tattered Leather Chestpiece
        call RegisterItemToPool('I66C', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Tattered Leather Helmet
        call RegisterItemToPool('I66D', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Tattered Leather Belt
        call RegisterItemToPool('I016', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Large Bag
        call RegisterItemToPool('I015', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Medium Bag
        call RegisterItemToPool('I014', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Small Bag
        call RegisterItemToPool('I66H', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Critmaster
        call RegisterItemToPool('I66I', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Sargoth's Ichor
        call RegisterItemToPool('I66J', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Venomweave Flask
        call RegisterItemToPool('I012', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Safety Instructions
        call RegisterItemToPool('I66O', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Disgusting Slime
        call RegisterItemToPool('I66P', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Rotten Part
        call RegisterItemToPool('I00Z', 1, ITEM_RARITY_UNCOMMON, 100, false)  // |cff0000ffHeart of the Ocean|r
        call RegisterItemToPool('I00T', 1, ITEM_RARITY_UNCOMMON, 100, false)  // |cff0000ffScale of Mordrax|r
        call RegisterItemToPool('I00M', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Kribug's Satchel
        call RegisterItemToPool('I00L', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Old Sandwich
        call RegisterItemToPool('I00J', 1, ITEM_RARITY_UNCOMMON, 100, false)  // The One Ring
        call RegisterItemToPool('I00I', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Dust Collector M25
        call RegisterItemToPool('I00H', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Vent-o-Matic Blower R200
        call RegisterItemToPool('I67C', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Utilities
        call RegisterItemToPool('I67D', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Utilities 2
        call RegisterItemToPool('I00D', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Frost Protection Potion
        call RegisterItemToPool('I00G', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Dustfilter 9000-BA
        call RegisterItemToPool('I00B', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Wind Shear
        call RegisterItemToPool('I00A', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Primal Force
        call RegisterItemToPool('I009', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Spirit Link
        call RegisterItemToPool('I004', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Wind Crystal
        call RegisterItemToPool('I002', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Fire Crystal
        call RegisterItemToPool('I001', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Earth Crystal
        call RegisterItemToPool('I000', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Scout's Report
        call RegisterItemToPool('I6CL', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Traveler's Journal
        call RegisterItemToPool('I6CK', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Whirlwind
        call RegisterItemToPool('I6CG', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Belt03
        call RegisterItemToPool('I6BW', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (I6BW)
        call RegisterItemToPool('I68N', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Bronze Belt
        call RegisterItemToPool('I68O', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Bronze Boots
        call RegisterItemToPool('I6BV', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (I6BV)
        call RegisterItemToPool('I68P', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Bronze Helmet
        call RegisterItemToPool('I68Q', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Bronze Gauntlets
        call RegisterItemToPool('I68R', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Bronze Chestpiece
        call RegisterItemToPool('I68S', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Bronze Leggings
        call RegisterItemToPool('I68T', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Bronze Shoulders
        call RegisterItemToPool('I68U', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Silvered Bronze Helmet
        call RegisterItemToPool('I68V', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Silvered Bronze Breastplate
        call RegisterItemToPool('I68W', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Iron Helmet
        call RegisterItemToPool('I68X', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Iron Shoulders
        call RegisterItemToPool('I68Y', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Iron Breastplate
        call RegisterItemToPool('I68Z', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Iron Bracers
        call RegisterItemToPool('I690', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Iron Gauntlets
        call RegisterItemToPool('I691', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Iron Belt
        call RegisterItemToPool('I692', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Iron Leggings
        call RegisterItemToPool('I693', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Iron Boots
        call RegisterItemToPool('I6BU', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (I6BU)
        call RegisterItemToPool('I69D', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Healing Rain
        call RegisterItemToPool('I69E', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Chain Heal
        call RegisterItemToPool('I69F', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Healing Wave
        call RegisterItemToPool('I69G', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Lightning Bolt
        call RegisterItemToPool('I69H', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Lightning Strike
        call RegisterItemToPool('I69I', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Fire Shock
        call RegisterItemToPool('I69J', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Summon Elemental
        call RegisterItemToPool('I69K', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Chain Lightning
        call RegisterItemToPool('I69L', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Earth Totem
        call RegisterItemToPool('I69N', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Fire Totem
        call RegisterItemToPool('I69O', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Wind Totem
        call RegisterItemToPool('I69P', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Earthbind Totem
        call RegisterItemToPool('I69Q', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Skyfury Totem
        call RegisterItemToPool('I69R', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Windfury Totem
        call RegisterItemToPool('I69S', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Stormstrike
        call RegisterItemToPool('I69T', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Bloodlust
        call RegisterItemToPool('I69U', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Ghost Wolf
        call RegisterItemToPool('I69V', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Hex
        call RegisterItemToPool('I69W', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Voodoo Spirits
        call RegisterItemToPool('I69X', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Voodoo Curse
        call RegisterItemToPool('I69Y', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Lightning Shield
        call RegisterItemToPool('I69Z', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Flurry
        call RegisterItemToPool('I6A1', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Reset Abilities
        call RegisterItemToPool('I6AI', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Spiritmender
        call RegisterItemToPool('I6AJ', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Stormcaller
        call RegisterItemToPool('I6AK', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Earthwarden
        call RegisterItemToPool('I6AL', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Seeds of Life
        call RegisterItemToPool('I6AM', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Ancestral Ward
        call RegisterItemToPool('I6AN', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Supply Crate
        call RegisterItemToPool('I6AO', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Totem Master
        call RegisterItemToPool('I6AP', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Spiritual Healing
        call RegisterItemToPool('I6AQ', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Cleansing Totem
        call RegisterItemToPool('ofro', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (ofro)
        call RegisterItemToPool('modt', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (modt)
        call RegisterItemToPool('sror', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (sror)
        call RegisterItemToPool('ankh', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (ankh)
        call RegisterItemToPool('fgsk', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (fgsk)
        call RegisterItemToPool('clfm', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (clfm)
        call RegisterItemToPool('clsd', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (clsd)
        call RegisterItemToPool('rst1', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (rst1)
        call RegisterItemToPool('gcel', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (gcel)
        call RegisterItemToPool('I00N', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Gutcleanser Elixir
        call RegisterItemToPool('rin1', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (rin1)
        call RegisterItemToPool('I003', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Water Crystal
        call RegisterItemToPool('belv', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (belv)
        call RegisterItemToPool('olig', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (olig)
        call RegisterItemToPool('I6C3', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Water Shield
        call RegisterItemToPool('odef', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (odef)
        call RegisterItemToPool('plcl', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (plcl)
        call RegisterItemToPool('oli2', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (oli2)
        call RegisterItemToPool('I69M', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Water Totem
        call RegisterItemToPool('vddl', 1, ITEM_RARITY_UNCOMMON, 100, false)  // |c00A9A9A9Voodoo Doll|r
        call RegisterItemToPool('tgxp', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (tgxp)
        call RegisterItemToPool('rde4', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (rde4)
        call RegisterItemToPool('I600', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Rol'jin's Head
        call RegisterItemToPool('I601', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Eye of Mur'gal
        call RegisterItemToPool('I602', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Light Boots
        call RegisterItemToPool('I611', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Camp Fire
        call RegisterItemToPool('I60C', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Tome of Eternal Strength
        call RegisterItemToPool('I60B', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Tome of Eternal Intelligence
        call RegisterItemToPool('I60A', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Tome of Eternal Agility
        call RegisterItemToPool('I609', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Manual of Eternal
        call RegisterItemToPool('I608', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Tome of God
        call RegisterItemToPool('rej2', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Lesser Replenishment Potion (old)
        call RegisterItemToPool('I60D', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (I60D)
        call RegisterItemToPool('I60G', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (I60G)
        call RegisterItemToPool('I60H', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (I60H)
        call RegisterItemToPool('rej6', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Greater Scroll of Replenishment (old)
        call RegisterItemToPool('I60J', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Margul's Claw
        call RegisterItemToPool('I60L', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Useless Cloak
        call RegisterItemToPool('I60M', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Rusty Kitchen Knive
        call RegisterItemToPool('wneu', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (wneu)
        call RegisterItemToPool('I60P', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Worn Gloves
        call RegisterItemToPool('wneg', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (wneg)
        call RegisterItemToPool('tret', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (tret)
        call RegisterItemToPool('ssan', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (ssan)
        call RegisterItemToPool('I60V', 1, ITEM_RARITY_UNCOMMON, 100, false)  // |CFFFF8C00Helm of Arenamaster|r
        call RegisterItemToPool('ofir', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (ofir)
        call RegisterItemToPool('sneg', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (sneg)
        call RegisterItemToPool('silk', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (silk)
        call RegisterItemToPool('I613', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Mount Reins
        call RegisterItemToPool('I616', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Tame Beast I
        call RegisterItemToPool('I617', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Tame Beast II
        call RegisterItemToPool('I618', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Tame Beast III
        call RegisterItemToPool('rnec', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (rnec)
        call RegisterItemToPool('moon', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (moon)
        call RegisterItemToPool('I61L', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Nazgrek's Flask
        call RegisterItemToPool('oven', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (oven)
        call RegisterItemToPool('ocor', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (ocor)
        call RegisterItemToPool('asbl', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (asbl)
        call RegisterItemToPool('shen', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (shen)
        call RegisterItemToPool('frhg', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (frhg)
        call RegisterItemToPool('frgd', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (frgd)
        call RegisterItemToPool('hbth', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (hbth)
        call RegisterItemToPool('klmm', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (klmm)
        call RegisterItemToPool('oslo', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (oslo)
        call RegisterItemToPool('rugt', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (rugt)
        call RegisterItemToPool('srbd', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (srbd)
        call RegisterItemToPool('srtl', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (srtl)
        call RegisterItemToPool('rump', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (rump)
        call RegisterItemToPool('I625', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Blood Signed Summon Letter
        call RegisterItemToPool('I626', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Gloves of Strength
        call RegisterItemToPool('I628', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Boots of Strength
        call RegisterItemToPool('I629', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Chestpiece of Strength
        call RegisterItemToPool('I62A', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Helm of Strength
        call RegisterItemToPool('I62B', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Necklace of Strength
        call RegisterItemToPool('I62C', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Ring of Strength
        call RegisterItemToPool('I62D', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Shield of Strength
        call RegisterItemToPool('I62E', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Axe of Strength
        call RegisterItemToPool('I62F', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Staff of Strength
        call RegisterItemToPool('I62G', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Sword of Strength
        call RegisterItemToPool('I62H', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Chestpiece of Intelligence
        call RegisterItemToPool('I62I', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Belt of Intelligence
        call RegisterItemToPool('I62J', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Boots of Intelligence
        call RegisterItemToPool('I62K', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Gloves of Intelligence
        call RegisterItemToPool('I62L', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Helm of Intelligence
        call RegisterItemToPool('I62M', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Necklace of Intelligence
        call RegisterItemToPool('I62N', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Ring of Intelligence
        call RegisterItemToPool('I62P', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Frostward Shield
        call RegisterItemToPool('I62Q', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Celestial Aegis
        call RegisterItemToPool('I62R', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Embersteel Bulwark
        call RegisterItemToPool('I62S', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Thunderstrike Defender
        call RegisterItemToPool('I62T', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Venomspine Ward
        call RegisterItemToPool('I62U', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Runebound Shield
        call RegisterItemToPool('I62V', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Crystaline Guardian
        call RegisterItemToPool('I62W', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Shadowbane Barrier
        call RegisterItemToPool('I62X', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Ironwood Protector
        call RegisterItemToPool('I62Y', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Arcane Ward
        call RegisterItemToPool('I62Z', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Dragonhide Shield
        call RegisterItemToPool('I630', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Radiant Crest
        call RegisterItemToPool('I631', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Gloomsteel Shield
        call RegisterItemToPool('I632', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Phoenixguard Shield
        call RegisterItemToPool('I633', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Astral Sentinel
        call RegisterItemToPool('I634', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Frostbite Ward
        call RegisterItemToPool('I635', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Luminous Ward
        call RegisterItemToPool('I636', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Bloodforged Bulwark
        call RegisterItemToPool('I637', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Serpent Scale Shield
        call RegisterItemToPool('I638', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Arcane Scepter
        call RegisterItemToPool('I639', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Celestial Staff
        call RegisterItemToPool('I63A', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Emberflare Rod
        call RegisterItemToPool('I63B', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Frostbinder Wand
        call RegisterItemToPool('I63C', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Thunderstruck Staff
        call RegisterItemToPool('I63D', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Venomspire Staff
        call RegisterItemToPool('I63E', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Runeblade Staff
        call RegisterItemToPool('I63F', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Enigma Arcanum
        call RegisterItemToPool('I63G', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Moonlit Rod
        call RegisterItemToPool('I63H', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Inferno Scepter
        call RegisterItemToPool('I63I', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Doomblade
        call RegisterItemToPool('I63J', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Shadowstrike Dagger
        call RegisterItemToPool('I63K', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Thunderfury Sword
        call RegisterItemToPool('I63L', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Frostbite Axe
        call RegisterItemToPool('I63M', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Emberforged Spear
        call RegisterItemToPool('I63O', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Venomfang Scimitar
        call RegisterItemToPool('I63P', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Runeblade Longsword
        call RegisterItemToPool('I63Q', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Serpent's Bite Dagger
        call RegisterItemToPool('I63S', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Dragonfang Katana
        call RegisterItemToPool('I63T', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Soulreaper Halberd
        call RegisterItemToPool('I63U', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Infernal Flare Wand
        call RegisterItemToPool('I63V', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Frostshard Greatsword
        call RegisterItemToPool('I63W', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Runebound War Axe
        call RegisterItemToPool('I63X', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Celestial Crescent Blade
        call RegisterItemToPool('I63Y', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Shadowmeld Shiv
        call RegisterItemToPool('I63Z', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Flamestrike Lance
        call RegisterItemToPool('I640', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Bloodfang Cleaver
        call RegisterItemToPool('I641', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Ironjaw Warblade
        call RegisterItemToPool('I642', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Skullcrusher Maul
        call RegisterItemToPool('I643', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Raging Blade of Doom
        call RegisterItemToPool('I644', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Thunderhorn Warhammer
        call RegisterItemToPool('I645', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Talisman of Arcane Resonance
        call RegisterItemToPool('I646', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Moonlit Amulet
        call RegisterItemToPool('I647', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Frostbound Pendant
        call RegisterItemToPool('I648', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Thunderheart Medallion
        call RegisterItemToPool('I649', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Celestial Harmony Necklace
        call RegisterItemToPool('I64A', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Emberflare Charm
        call RegisterItemToPool('I64B', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Venomweave Locket
        call RegisterItemToPool('I64C', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Rune-etched Collar
        call RegisterItemToPool('I64D', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Shadowcloak Talisman
        call RegisterItemToPool('I64E', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Serpent's Coil Necklace
        call RegisterItemToPool('I64F', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Ring of Eternal Frost
        call RegisterItemToPool('I64G', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Thunderforged Band
        call RegisterItemToPool('I64H', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Emberstone Loop
        call RegisterItemToPool('I64I', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Celestial Halo
        call RegisterItemToPool('I64J', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Runebound Circlet
        call RegisterItemToPool('I64K', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Shadowweaver Ring
        call RegisterItemToPool('I64L', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Serpent's Coil Ring
        call RegisterItemToPool('I64M', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Bloodfire Signet
        call RegisterItemToPool('I64N', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Moonstone Seal
        call RegisterItemToPool('I64O', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Ironheart Ring
        call RegisterItemToPool('I64P', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Dragonscale Chestplate
        call RegisterItemToPool('I64Q', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Thunderforged Breastplate
        call RegisterItemToPool('I64R', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Celestial Mail
        call RegisterItemToPool('I64S', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Emberheart Cuirass
        call RegisterItemToPool('I64T', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Runebound Hauberk
        call RegisterItemToPool('stwp', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (stwp)
        call RegisterItemToPool('I64V', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Frostbitten Plate
        call RegisterItemToPool('I64W', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Serpent's Scale Vest
        call RegisterItemToPool('I64X', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Obsidian Warplate
        call RegisterItemToPool('I64Y', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Moonshadow Robes
        call RegisterItemToPool('I64Z', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Silks of Celestial Harmony
        call RegisterItemToPool('I650', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Emberweave Robes
        call RegisterItemToPool('I651', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Frostshroud Vestments
        call RegisterItemToPool('I652', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Thunderfall Raiment
        call RegisterItemToPool('I653', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Runebound Silk Tunic
        call RegisterItemToPool('I654', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Shadowcloak Mantle
        call RegisterItemToPool('I655', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Serpent's Whispering Garb
        call RegisterItemToPool('I656', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Moonlight Veil
        call RegisterItemToPool('I657', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Ethereal Frostcloth Wrap
        call RegisterItemToPool('I658', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Astral Silken Robe
        call RegisterItemToPool('I659', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Cloak of Shadowsong
        call RegisterItemToPool('I65A', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Frostweave Mantle
        call RegisterItemToPool('I65B', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Thunderfall Shroud
        call RegisterItemToPool('I65C', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Celestial Veil
        call RegisterItemToPool('I65D', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Emberwind Wrap
        call RegisterItemToPool('I65F', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Shadowshroud Drape
        call RegisterItemToPool('I65G', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Serpent's Embrace
        call RegisterItemToPool('I65H', 1, ITEM_RARITY_UNCOMMON, 100, false)  // Moonlit Whisper Cloak
        // Level 3
        call RegisterItemToPool('sand', 3, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (sand)
        call RegisterItemToPool('vamp', 3, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (vamp)
        call RegisterItemToPool('I624', 3, ITEM_RARITY_UNCOMMON, 100, false)  // Jin'Zun Healing Ward
        call RegisterItemToPool('srrc', 3, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (srrc)
        // Level 6
        call RegisterItemToPool('I00E', 6, ITEM_RARITY_UNCOMMON, 100, false)  // Cannonballs
        call RegisterItemToPool('I6C4', 6, ITEM_RARITY_UNCOMMON, 100, false)  // Tent
        call RegisterItemToPool('I00Y', 6, ITEM_RARITY_UNCOMMON, 100, false)  // Mana Crystal
        call RegisterItemToPool('I6CI', 6, ITEM_RARITY_UNCOMMON, 100, false)  // Frost Trap
        call RegisterItemToPool('pinv', 6, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (pinv)
        call RegisterItemToPool('pnvl', 6, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (pnvl)
        call RegisterItemToPool('I010', 6, ITEM_RARITY_UNCOMMON, 100, false)  // Supplies
        call RegisterItemToPool('I00P', 6, ITEM_RARITY_UNCOMMON, 100, false)  // Dragon Egg
        call RegisterItemToPool('I6A8', 6, ITEM_RARITY_UNCOMMON, 100, false)  // Heavy Leather
        call RegisterItemToPool('I61N', 6, ITEM_RARITY_UNCOMMON, 100, false)  // Vizier Skin
        call RegisterItemToPool('I61H', 6, ITEM_RARITY_UNCOMMON, 100, false)  // Hawk Wing
        call RegisterItemToPool('I61G', 6, ITEM_RARITY_UNCOMMON, 100, false)  // Thunder Lizard Skin
        call RegisterItemToPool('I61F', 6, ITEM_RARITY_UNCOMMON, 100, false)  // Wolf Skin
        call RegisterItemToPool('I61E', 6, ITEM_RARITY_UNCOMMON, 100, false)  // Turtle Skin
        call RegisterItemToPool('I61D', 6, ITEM_RARITY_UNCOMMON, 100, false)  // Frog Skin
        call RegisterItemToPool('I61C', 6, ITEM_RARITY_UNCOMMON, 100, false)  // Boar Skin
        call RegisterItemToPool('I61B', 6, ITEM_RARITY_UNCOMMON, 100, false)  // Bear Skin
        call RegisterItemToPool('I615', 6, ITEM_RARITY_UNCOMMON, 100, false)  // Frog Slime
        call RegisterItemToPool('I614', 6, ITEM_RARITY_UNCOMMON, 100, false)  // Stag Hair
        call RegisterItemToPool('whwd', 6, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (whwd)
        call RegisterItemToPool('gobm', 6, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (gobm)
        call RegisterItemToPool('I00C', 6, ITEM_RARITY_UNCOMMON, 100, false)  // Spirit Shard
        call RegisterItemToPool('I00Q', 6, ITEM_RARITY_UNCOMMON, 100, false)  // Raptor Egg
        call RegisterItemToPool('I00R', 6, ITEM_RARITY_UNCOMMON, 100, false)  // Chimaera Egg
        call RegisterItemToPool('mcri', 6, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (mcri)
        call RegisterItemToPool('I6CH', 6, ITEM_RARITY_UNCOMMON, 100, false)  // Net
        call RegisterItemToPool('I60F', 6, ITEM_RARITY_UNCOMMON, 100, false)  // Keg of Beer
        call RegisterItemToPool('I6AB', 6, ITEM_RARITY_UNCOMMON, 100, false)  // Big Bear Tooth
        call RegisterItemToPool('I69B', 6, ITEM_RARITY_UNCOMMON, 100, false)  // Stolen Goods
        call RegisterItemToPool('I00F', 6, ITEM_RARITY_UNCOMMON, 100, false)  // Barrel of Explosives
        // Level 8
        call RegisterItemToPool('I60T', 8, ITEM_RARITY_UNCOMMON, 100, false)  // |CFFFF8C00Chestpiece of Arenamaster|r
        call RegisterItemToPool('I60R', 8, ITEM_RARITY_UNCOMMON, 100, false)  // |CFFFF8C00Boots of Arenamaster|r
        call RegisterItemToPool('I60U', 8, ITEM_RARITY_UNCOMMON, 100, false)  // |CFFFF8C00Shoulders of Arenamaster|r
        call RegisterItemToPool('I605', 8, ITEM_RARITY_UNCOMMON, 100, false)  // Hammer of Blood
        call RegisterItemToPool('I60Q', 8, ITEM_RARITY_UNCOMMON, 100, false)  // |CFFFF8C00Cloak of Arenamaster|r
        call RegisterItemToPool('I60S', 8, ITEM_RARITY_UNCOMMON, 100, false)  // |CFFFF8C00Gloves of Arenamaster|r
        // Level 10
        call RegisterItemToPool('I6BC', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Greater Healing Salve
        call RegisterItemToPool('I6AS', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Large Hoof
        call RegisterItemToPool('shea', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (shea)
        call RegisterItemToPool('hslv', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (hslv)
        call RegisterItemToPool('I60K', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Pile Of Wood
        call RegisterItemToPool('I6BE', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Major Healing Potion
        call RegisterItemToPool('I6BD', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Minor Healing Potion
        call RegisterItemToPool('rej5', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (rej5)
        call RegisterItemToPool('pghe', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Greater Healing Potion
        call RegisterItemToPool('pman', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Mana Potion
        call RegisterItemToPool('I6BT', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Major Mana Potion
        call RegisterItemToPool('I6BS', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Minor Mana Potion
        call RegisterItemToPool('phea', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Healing Potion
        call RegisterItemToPool('scul', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (scul)
        call RegisterItemToPool('I60N', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Old Copper Ring
        call RegisterItemToPool('I011', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Wraith Essence
        call RegisterItemToPool('I60O', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Holy Cross
        call RegisterItemToPool('I00X', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Sharp Claw
        call RegisterItemToPool('I00W', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Ruined Dragonhide
        call RegisterItemToPool('I6AR', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Wolf Jawbone
        call RegisterItemToPool('rej3', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (rej3)
        call RegisterItemToPool('rej4', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Greater Replenishment Potion (old)
        call RegisterItemToPool('sres', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (sres)
        call RegisterItemToPool('hlst', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (hlst)
        call RegisterItemToPool('shas', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (shas)
        call RegisterItemToPool('I00V', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Small Flame Sac
        call RegisterItemToPool('mnst', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (mnst)
        call RegisterItemToPool('I6BM', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Scroll of Greater Protection
        call RegisterItemToPool('sreg', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (sreg)
        call RegisterItemToPool('I6CA', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Rock
        call RegisterItemToPool('spro', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (spro)
        call RegisterItemToPool('pres', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Restoration Potion
        call RegisterItemToPool('pclr', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (pclr)
        call RegisterItemToPool('sman', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (sman)
        call RegisterItemToPool('I6BR', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Scroll of Major Restoration
        call RegisterItemToPool('I6BQ', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Scroll of Greater Restoration
        call RegisterItemToPool('I6BP', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Scroll of Major Regeneration
        call RegisterItemToPool('I6BO', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Scroll of Greater Regeneration
        call RegisterItemToPool('I00S', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Whelp Scale
        call RegisterItemToPool('I6BN', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Scroll of Major Protection
        call RegisterItemToPool('I6BK', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Scroll of Greater Mana
        call RegisterItemToPool('I6BJ', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Scroll of Major Healing
        call RegisterItemToPool('I6BI', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Scroll of Greater Healing
        call RegisterItemToPool('i1g3', 10, ITEM_RARITY_UNCOMMON, 100, false)  // |c00FFFFFFElven Wine|r
        call RegisterItemToPool('rej1', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Minor Replenishment Potion (old)
        call RegisterItemToPool('arsc', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (arsc)
        call RegisterItemToPool('I6BH', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Greater Replenishment Potion
        call RegisterItemToPool('I6BG', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Minor Replenishment Potion
        call RegisterItemToPool('pgma', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Greater Mana Potion
        call RegisterItemToPool('I6BL', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Scroll of Major Mana
        call RegisterItemToPool('I6BF', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Greater Restoration Potion
        call RegisterItemToPool('I6AE', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Murloc Fin
        call RegisterItemToPool('I66Q', 10, ITEM_RARITY_UNCOMMON, 100, false)  // Spider Ichor
        // Level 12
        call RegisterItemToPool('I69C', 12, ITEM_RARITY_UNCOMMON, 100, false)  // Barricade
        // Level 20
        call RegisterItemToPool('I60X', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Earth Roots
        call RegisterItemToPool('i1g0', 20, ITEM_RARITY_UNCOMMON, 100, false)  // |c00FFFFFFWillow Branch|r
        call RegisterItemToPool('pams', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (pams)
        call RegisterItemToPool('i1g9', 20, ITEM_RARITY_UNCOMMON, 100, false)  // |c00FFFFFFshea test|r
        call RegisterItemToPool('I61O', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Raw Wolf Meat
        call RegisterItemToPool('I61P', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Raw Stag Meat
        call RegisterItemToPool('I61Q', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Raw Bear Meat
        call RegisterItemToPool('I61R', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Raw Lizard Meat
        call RegisterItemToPool('I61S', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Raw Hawk Meat
        call RegisterItemToPool('I61T', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Raw Murloc Meat
        call RegisterItemToPool('I61U', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Raw Turtle Meat
        call RegisterItemToPool('I61V', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Raw Tiger Meat
        call RegisterItemToPool('I61W', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Raw Panther Meat
        call RegisterItemToPool('I61X', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Raw Raptor Meat
        call RegisterItemToPool('I61Y', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Raw Snake Meat
        call RegisterItemToPool('I61Z', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Raw Makrura Meat
        call RegisterItemToPool('I620', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Raw Boar Meat
        call RegisterItemToPool('I621', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Raw Crawler Meat
        call RegisterItemToPool('I622', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Raw Rabbit Meat
        call RegisterItemToPool('I623', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Raw Cow Meat
        call RegisterItemToPool('I686', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Diamond
        call RegisterItemToPool('I69A', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Gnoll Head
        call RegisterItemToPool('pgin', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (pgin)
        call RegisterItemToPool('pspd', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Unknown Item (pspd)
        call RegisterItemToPool('I60E', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Bottle of Beer
        call RegisterItemToPool('I60W', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Agave
        call RegisterItemToPool('I60Y', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Forest Flower
        call RegisterItemToPool('I60Z', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Spring Water
        call RegisterItemToPool('I610', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Murloc Head
        call RegisterItemToPool('I61J', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Create Spring Water
        call RegisterItemToPool('I61M', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Empty Flask
        call RegisterItemToPool('I61K', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Empty Vial
        call RegisterItemToPool('I66K', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Salt
        call RegisterItemToPool('I66L', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Thread
        call RegisterItemToPool('I66N', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Dye
        call RegisterItemToPool('I66S', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Blindweed
        call RegisterItemToPool('I66T', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Bruiseweed
        call RegisterItemToPool('I66U', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Gromsblood
        call RegisterItemToPool('I66V', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Liferoot
        call RegisterItemToPool('I66W', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Mountain Silversage
        call RegisterItemToPool('I66X', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Peacebloom
        call RegisterItemToPool('I66Y', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Plaguebloom
        call RegisterItemToPool('I66Z', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Shroom Blue
        call RegisterItemToPool('I670', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Shroom Red
        call RegisterItemToPool('I671', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Shroom Green
        call RegisterItemToPool('I67E', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Copper Ore
        call RegisterItemToPool('I67F', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Tin Ore
        call RegisterItemToPool('I67G', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Silver Ore
        call RegisterItemToPool('I67H', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Iron Ore
        call RegisterItemToPool('I67I', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Gold Ore
        call RegisterItemToPool('I67J', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Mithril Ore
        call RegisterItemToPool('I67K', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Arcanite Ore
        call RegisterItemToPool('I67L', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Thorium Ore
        call RegisterItemToPool('I67M', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Copper Bar
        call RegisterItemToPool('I67N', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Tin Bar
        call RegisterItemToPool('I67O', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Silver Bar
        call RegisterItemToPool('I67P', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Bronze Bar
        call RegisterItemToPool('I67Q', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Iron Bar
        call RegisterItemToPool('I67R', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Steel Bar
        call RegisterItemToPool('I67S', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Gold Bar
        call RegisterItemToPool('I67T', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Mithril Bar
        call RegisterItemToPool('I67U', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Arcanite Bar
        call RegisterItemToPool('I67V', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Thorium Bar
        call RegisterItemToPool('I67W', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Malachite
        call RegisterItemToPool('I67X', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Tigerseye
        call RegisterItemToPool('I67Y', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Shadowgem
        call RegisterItemToPool('I67Z', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Moonstone
        call RegisterItemToPool('I680', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Moss Agate
        call RegisterItemToPool('I681', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Jade
        call RegisterItemToPool('I682', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Citrine
        call RegisterItemToPool('I683', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Opal
        call RegisterItemToPool('I684', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Blue Sapphire
        call RegisterItemToPool('I685', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Emerald
        call RegisterItemToPool('I687', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Arcane Crystal
        call RegisterItemToPool('I688', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Star Ruby
        call RegisterItemToPool('I689', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Coal
        call RegisterItemToPool('I6A6', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Light Leather
        call RegisterItemToPool('I6A7', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Medium Leather
        call RegisterItemToPool('I6A9', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Rugged Leather
        call RegisterItemToPool('I6AA', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Thick Leather
        call RegisterItemToPool('I6BA', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Crystal Water
        call RegisterItemToPool('I6BB', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Purified Water
        call RegisterItemToPool('I005', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Blue Crystal
        call RegisterItemToPool('I006', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Red Crystal
        call RegisterItemToPool('I007', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Yellow Crystal
        call RegisterItemToPool('I008', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Green Crystal
        call RegisterItemToPool('i1f8', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Stranglekelp
        call RegisterItemToPool('i1fa', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Swiftthistle
        call RegisterItemToPool('i1fd', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Goldthorn
        call RegisterItemToPool('i1ca', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Bloodthistle
        call RegisterItemToPool('i1cc', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Cinderbloom
        call RegisterItemToPool('i1d2', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Evergreen Moss
        call RegisterItemToPool('i1d3', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Fadeleaf
        call RegisterItemToPool('i1d4', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Felweed
        call RegisterItemToPool('i1d6', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Fireweed
        call RegisterItemToPool('i1da', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Frostweed
        call RegisterItemToPool('i1dc', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Goldclover
        call RegisterItemToPool('i1de', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Grave Moss
        call RegisterItemToPool('i1e1', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Jade Tea Leaf
        call RegisterItemToPool('i1e5', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Gloom Cap
        call RegisterItemToPool('i1e6', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Fel Cap
        call RegisterItemToPool('i1e7', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Spawn Cap
        call RegisterItemToPool('i1ec', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Rain Poppy
        call RegisterItemToPool('i1ef', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Silkweed
        call RegisterItemToPool('i1f0', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Silverleaf
        call RegisterItemToPool('i1f1', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Snow Lily
        call RegisterItemToPool('i1f5', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Steelbloom
        call RegisterItemToPool('i200', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Tiger Lily
        call RegisterItemToPool('i204', 20, ITEM_RARITY_UNCOMMON, 100, false)  // Winter's Bite
        // Level 50
        call RegisterItemToPool('i1g4', 50, ITEM_RARITY_UNCOMMON, 100, false)  // |c00FFFFFFBaseItemAbilitiesTestItem|r
        // Level 100
        call RegisterItemToPool('I68C', 100, ITEM_RARITY_UNCOMMON, 100, false)  // test_helmet_level_100
        call RegisterItemToPool('hcun', 100, ITEM_RARITY_UNCOMMON, 100, false)  // |c00A9A9A9Hood of Cunning|r
        call RegisterItemToPool('I6AV', 100, ITEM_RARITY_UNCOMMON, 100, false)  // |c00A9A9A9Dusty Cap|r
        call RegisterItemToPool('hval', 100, ITEM_RARITY_UNCOMMON, 100, false)  // |c00A9A9A9Helm of Valor|r
        call RegisterItemToPool('I66G', 100, ITEM_RARITY_UNCOMMON, 100, false)  // |c00A9A9A9Frayed Hat|r
        // Level 105
        call RegisterItemToPool('I68D', 105, ITEM_RARITY_UNCOMMON, 100, false)  // test_helmet_level_105
        // Level 123
        call RegisterItemToPool('i0b2', 123, ITEM_RARITY_UNCOMMON, 100, false)  // |c00FFFFFFQuality reserved_4 of Protection|r
        // Level 136
        call RegisterItemToPool('I606', 136, ITEM_RARITY_UNCOMMON, 100, false)  // Helm of Fel'Dok
        // Level 149
        call RegisterItemToPool('I68E', 149, ITEM_RARITY_UNCOMMON, 100, false)  // test_helmet_level_149
        // Level 167
        call RegisterItemToPool('i1h1', 167, ITEM_RARITY_UNCOMMON, 100, false)  // |c00FFFFFFSturdy Material|r
        // Level 186
        call RegisterItemToPool('I6CF', 186, ITEM_RARITY_UNCOMMON, 100, false)  // |c00FF8000Infernal Sigil of Colossus|r
        // Level 235
        call RegisterItemToPool('i1h3', 235, ITEM_RARITY_UNCOMMON, 100, false)  // |c00FFFFFFReliable Quest of the Warrior|r
        // Level 250
        call RegisterItemToPool('I6AW', 250, ITEM_RARITY_UNCOMMON, 100, false)  // |c00A9A9A9Ragged Cloak|r
        // Level 300
        call RegisterItemToPool('i0c1', 300, ITEM_RARITY_UNCOMMON, 100, false)  // |c00FFFFFFFine Chest of Strength|r
        call RegisterItemToPool('I6AX', 300, ITEM_RARITY_UNCOMMON, 100, false)  // |c00A9A9A9Worn Chainmail|r
        call RegisterItemToPool('I66F', 300, ITEM_RARITY_UNCOMMON, 100, false)  // |c00A9A9A9Faded Cloth Robes|r
        // Level 350
        call RegisterItemToPool('I6AY', 350, ITEM_RARITY_UNCOMMON, 100, false)  // |c00A9A9A9Frayed Bindings|r
        // Level 400
        call RegisterItemToPool('I6AU', 400, ITEM_RARITY_UNCOMMON, 100, false)  // |c00A9A9A9Worn Gloves|r
        // Level 450
        call RegisterItemToPool('I6AZ', 450, ITEM_RARITY_UNCOMMON, 100, false)  // |c00A9A9A9Frayed Girdle|r
        call RegisterItemToPool('i0a7', 450, ITEM_RARITY_UNCOMMON, 100, false)  // |c00FFFFFFReliable Belt|r
        call RegisterItemToPool('i0d1', 450, ITEM_RARITY_UNCOMMON, 100, false)  // |c00FFFFFFTEST Quality Belt|r
        call RegisterItemToPool('I6B0', 450, ITEM_RARITY_UNCOMMON, 100, false)  // |c00A9A9A9Worn Pants|r
        // Level 550
        call RegisterItemToPool('rag1', 550, ITEM_RARITY_UNCOMMON, 100, false)  // |c00A9A9A9Slippers of Agility|r
        call RegisterItemToPool('I6AT', 550, ITEM_RARITY_UNCOMMON, 100, false)  // |c00A9A9A9Worn Boots|r
        // Level 600
        call RegisterItemToPool('lnrn', 600, ITEM_RARITY_UNCOMMON, 100, false)  // |c00A9A9A9Lion's Ring|r
        // Level 650
        call RegisterItemToPool('tmmt', 650, ITEM_RARITY_UNCOMMON, 100, false)  // |c00A9A9A9Totem of Might|r
        // Level 700
        call RegisterItemToPool('I673', 700, ITEM_RARITY_UNCOMMON, 100, false)  // TEST 1H Axe 04
        call RegisterItemToPool('I6B3', 700, ITEM_RARITY_UNCOMMON, 100, false)  // |c00A9A9A9Dulled Dagger|r
        call RegisterItemToPool('I66M', 700, ITEM_RARITY_UNCOMMON, 100, false)  // Skinning Knife
        call RegisterItemToPool('I66R', 700, ITEM_RARITY_UNCOMMON, 100, false)  // Adept Shaman Claws
        call RegisterItemToPool('I672', 700, ITEM_RARITY_UNCOMMON, 100, false)  // Mining Pick
        call RegisterItemToPool('I6B2', 700, ITEM_RARITY_UNCOMMON, 100, false)  // |c00A9A9A9Chipped Axe|r
        call RegisterItemToPool('I676', 700, ITEM_RARITY_UNCOMMON, 100, false)  // TEST 1H Mace
        call RegisterItemToPool('I678', 700, ITEM_RARITY_UNCOMMON, 100, false)  // TEST 1H Sword
        call RegisterItemToPool('mlst', 700, ITEM_RARITY_UNCOMMON, 100, false)  // |c00A9A9A9Maul of Strength|r
        call RegisterItemToPool('I612', 700, ITEM_RARITY_UNCOMMON, 100, false)  // Torch
        call RegisterItemToPool('i1g8', 700, ITEM_RARITY_UNCOMMON, 100, false)  // |c00FFFFFFamrc stats|r
        call RegisterItemToPool('i1g2', 700, ITEM_RARITY_UNCOMMON, 100, false)  // |c00FFFFFFWine Bottle|r
        call RegisterItemToPool('i1g6', 700, ITEM_RARITY_UNCOMMON, 100, false)  // |c00FFFFFFafac stats|r
        call RegisterItemToPool('i1g7', 700, ITEM_RARITY_UNCOMMON, 100, false)  // |c00FFFFFFamrc nostats|r
        call RegisterItemToPool('I6B1', 700, ITEM_RARITY_UNCOMMON, 100, false)  // |c00A9A9A9Blunt Sword|r
        call RegisterItemToPool('i1g5', 700, ITEM_RARITY_UNCOMMON, 100, false)  // |c00FFFFFFafac nostats|r
        // Level 705
        call RegisterItemToPool('I694', 705, ITEM_RARITY_UNCOMMON, 100, false)  // test_1hwep_level_705
        // Level 749
        call RegisterItemToPool('I695', 749, ITEM_RARITY_UNCOMMON, 100, false)  // test_1hwep_level_749
        // Level 750
        call RegisterItemToPool('I674', 750, ITEM_RARITY_UNCOMMON, 100, false)  // TEST 2H Axe B 01
        call RegisterItemToPool('I679', 750, ITEM_RARITY_UNCOMMON, 100, false)  // TEST 2H Sword
        call RegisterItemToPool('I677', 750, ITEM_RARITY_UNCOMMON, 100, false)  // TEST 2H Mace
        call RegisterItemToPool('I6B4', 750, ITEM_RARITY_UNCOMMON, 100, false)  // |c00A9A9A9Rusted Battleaxe|r
        call RegisterItemToPool('I675', 750, ITEM_RARITY_UNCOMMON, 100, false)  // TEST 2H Polearm
        // Level 760
        call RegisterItemToPool('I696', 760, ITEM_RARITY_UNCOMMON, 100, false)  // test_2hwep_level_760
        call RegisterItemToPool('I00O', 760, ITEM_RARITY_UNCOMMON, 100, false)  // Shovel
        // Level 786
        call RegisterItemToPool('I00U', 786, ITEM_RARITY_UNCOMMON, 100, false)  // |cff6f2583Dragonslayer's Sword|r
        // Level 796
        call RegisterItemToPool('I607', 796, ITEM_RARITY_UNCOMMON, 100, false)  // |c00FF8000Weapon of Fel'Dok|r
        // Level 799
        call RegisterItemToPool('I697', 799, ITEM_RARITY_UNCOMMON, 100, false)  // test_2hwep_level_799
        // Level 800
        call RegisterItemToPool('I6B5', 800, ITEM_RARITY_UNCOMMON, 100, false)  // |c00A9A9A9Warped Staff|r
        // Level 846
        call RegisterItemToPool('I6CJ', 846, ITEM_RARITY_UNCOMMON, 100, false)  // |c00FFFF00Jin'Zun's Fishing Pole|r
        // Level 850
        call RegisterItemToPool('I66E', 850, ITEM_RARITY_UNCOMMON, 100, false)  // Wooden Shield
        call RegisterItemToPool('I01D', 850, ITEM_RARITY_UNCOMMON, 100, false)  // item_objectcomponents_shield_buckler_damaged_a_01a
        call RegisterItemToPool('I01C', 850, ITEM_RARITY_UNCOMMON, 100, false)  // item_objectcomponents_shield_buckler_damaged_a_01_test
        call RegisterItemToPool('I01B', 850, ITEM_RARITY_UNCOMMON, 100, false)  // item_objectcomponents_shield_shield_ahnqiraj_d_01
        call RegisterItemToPool('I01A', 850, ITEM_RARITY_UNCOMMON, 100, false)  // item_objectcomponents_shield_buckler_round_a_01
        call RegisterItemToPool('I019', 850, ITEM_RARITY_UNCOMMON, 100, false)  // item_objectcomponents_shield_buckler_oval_a_01
        call RegisterItemToPool('I018', 850, ITEM_RARITY_UNCOMMON, 100, false)  // item_objectcomponents_shield_buckler_damaged_a_02
        call RegisterItemToPool('I017', 850, ITEM_RARITY_UNCOMMON, 100, false)  // item_objectcomponents_shield_buckler_damaged_a_01
        call RegisterItemToPool('I67A', 850, ITEM_RARITY_UNCOMMON, 100, false)  // TEST Shield 1
        call RegisterItemToPool('I67B', 850, ITEM_RARITY_UNCOMMON, 100, false)  // TEST Shield 2
        call RegisterItemToPool('I01E', 850, ITEM_RARITY_UNCOMMON, 100, false)  // item_objectcomponents_shield_buckler_damaged_a_01b
        call RegisterItemToPool('I01F', 850, ITEM_RARITY_UNCOMMON, 100, false)  // item_objectcomponents_shield_buckler_damaged_a_01c
        call RegisterItemToPool('I6B7', 850, ITEM_RARITY_UNCOMMON, 100, false)  // |c00A9A9A9Cracked Aegis|r
        call RegisterItemToPool('I6B6', 850, ITEM_RARITY_UNCOMMON, 100, false)  // |c00A9A9A9Dented Shield|r
        // Level 851
        call RegisterItemToPool('I698', 851, ITEM_RARITY_UNCOMMON, 100, false)  // test_shield_level_851
        // Level 899
        call RegisterItemToPool('I699', 899, ITEM_RARITY_UNCOMMON, 100, false)  // test_shield_level_899

        // === ITEM_RARITY_RARE ITEMS ===
        // Level 6
        call RegisterItemToPool('I6C5', 6, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Essence of Fire|r
        call RegisterItemToPool('I6C7', 6, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Essence of Air|r
        call RegisterItemToPool('I6C8', 6, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Essence of Earth|r
        call RegisterItemToPool('I6C6', 6, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Essence of Water|r
        // Level 20
        call RegisterItemToPool('i1f6', 20, ITEM_RARITY_RARE, 100, false)  // Stormvine
        call RegisterItemToPool('i206', 20, ITEM_RARITY_RARE, 100, false)  // |c001EFF00Thornroot|r
        call RegisterItemToPool('i1db', 20, ITEM_RARITY_RARE, 100, false)  // Frozen Herb
        call RegisterItemToPool('i1f4', 20, ITEM_RARITY_RARE, 100, false)  // Starflower
        call RegisterItemToPool('i1c6', 20, ITEM_RARITY_RARE, 100, false)  // Ancient Lichen
        call RegisterItemToPool('i1d1', 20, ITEM_RARITY_RARE, 100, false)  // Dreaming Glory
        call RegisterItemToPool('i1fc', 20, ITEM_RARITY_RARE, 100, false)  // Talandra's Rose
        call RegisterItemToPool('i1d0', 20, ITEM_RARITY_RARE, 100, false)  // Dreamfoil
        call RegisterItemToPool('i1e0', 20, ITEM_RARITY_RARE, 100, false)  // Icecap
        call RegisterItemToPool('i1df', 20, ITEM_RARITY_RARE, 100, false)  // Heartblossom
        call RegisterItemToPool('i1f2', 20, ITEM_RARITY_RARE, 100, false)  // Spineleaf
        call RegisterItemToPool('i1ff', 20, ITEM_RARITY_RARE, 100, false)  // Terocone
        call RegisterItemToPool('i1e2', 20, ITEM_RARITY_RARE, 100, false)  // Khadgar's Whisker
        call RegisterItemToPool('i1fe', 20, ITEM_RARITY_RARE, 100, false)  // Icethorn
        call RegisterItemToPool('i205', 20, ITEM_RARITY_RARE, 100, false)  // Snakeroot
        call RegisterItemToPool('i1eb', 20, ITEM_RARITY_RARE, 100, false)  // Ragveil
        call RegisterItemToPool('i1f9', 20, ITEM_RARITY_RARE, 100, false)  // Sungrass
        call RegisterItemToPool('i202', 20, ITEM_RARITY_RARE, 100, false)  // Whiptail
        call RegisterItemToPool('i1fb', 20, ITEM_RARITY_RARE, 100, false)  // Talador Orchid
        call RegisterItemToPool('i201', 20, ITEM_RARITY_RARE, 100, false)  // Twilight Jasmine
        call RegisterItemToPool('i1d8', 20, ITEM_RARITY_RARE, 100, false)  // Fool's Cap
        call RegisterItemToPool('i1cd', 20, ITEM_RARITY_RARE, 100, false)  // Constrictor Grass
        call RegisterItemToPool('i1d5', 20, ITEM_RARITY_RARE, 100, false)  // Firebloom
        call RegisterItemToPool('i1ed', 20, ITEM_RARITY_RARE, 100, false)  // Mountain Sansam
        call RegisterItemToPool('i1e9', 20, ITEM_RARITY_RARE, 100, false)  // Nightmare Vine
        call RegisterItemToPool('i1ea', 20, ITEM_RARITY_RARE, 100, false)  // Purple Lotus
        // Level 110
        call RegisterItemToPool('I68F', 110, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Copper Chain Helmet|r
        call RegisterItemToPool('I65Z', 110, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Reinforced Leather Helmet|r
        call RegisterItemToPool('I604', 110, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Voodoo Mask|r
        call RegisterItemToPool('cnob', 110, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Circlet of Nobility|r
        // Level 136
        call RegisterItemToPool('i0b6', 136, ITEM_RARITY_RARE, 100, false)  // |c001EFF00Reliable reserved_1 of Power|r
        // Level 153
        call RegisterItemToPool('i0c0', 153, ITEM_RARITY_RARE, 100, false)  // |c001EFF00Reliable Blade of the Bear|r
        // Level 160
        call RegisterItemToPool('I6BX', 160, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Gem of Lesser Health|r
        call RegisterItemToPool('I65L', 160, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Enchanted Amulet|r
        // Level 161
        call RegisterItemToPool('I6BY', 161, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Gem of Health|r
        // Level 162
        call RegisterItemToPool('I6BZ', 162, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Gem of Greater Health|r
        // Level 163
        call RegisterItemToPool('I6C0', 163, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Gem of Major Health|r
        // Level 166
        call RegisterItemToPool('I00K', 166, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Medal of Honor|r
        // Level 210
        call RegisterItemToPool('I662', 210, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Reinforced Leather Shoulderpads|r
        call RegisterItemToPool('I68G', 210, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Copper Chain Leggings|r
        call RegisterItemToPool('i0a9', 210, ITEM_RARITY_RARE, 100, false)  // |c001EFF00TEST Sturdy Shoulders of Power|r
        // Level 261
        call RegisterItemToPool('I6C9', 261, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Stealth Cloak|r
        // Level 310
        call RegisterItemToPool('I660', 310, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Reinforced Leather Chestpiece|r
        call RegisterItemToPool('I68H', 310, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Copper Chain Vest|r
        // Level 360
        call RegisterItemToPool('I68I', 360, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Copper Chain Bracers|r
        // Level 410
        call RegisterItemToPool('I65X', 410, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Reinforced Leather Gloves|r
        call RegisterItemToPool('I68J', 410, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Copper Chain Gauntlets|r
        // Level 450
        call RegisterItemToPool('I627', 450, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Belt of Strength|r
        // Level 460
        call RegisterItemToPool('I68K', 460, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Copper Chain Belt|r
        call RegisterItemToPool('I661', 460, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Reinforced Leather Belt|r
        call RegisterItemToPool('bgst', 460, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Belt of Giant Strength|r
        call RegisterItemToPool('I6B8', 460, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Belt of Wise Man|r
        call RegisterItemToPool('I6B9', 460, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Belt of Tiger Trainer|r
        // Level 560
        call RegisterItemToPool('i0b1', 560, ITEM_RARITY_RARE, 100, false)  // |c001EFF00TEST Reliable Foot of Swiftness|r
        call RegisterItemToPool('I603', 560, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Heavy Boots|r
        call RegisterItemToPool('i0d3', 560, ITEM_RARITY_RARE, 100, false)  // |c001EFF00Quality Foot of Power|r
        call RegisterItemToPool('I65Y', 560, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Reinforced Leather Boots|r
        call RegisterItemToPool('I68M', 560, ITEM_RARITY_RARE, 100, false)  // |c001EFF00Copper Chain Boots|r
        // Level 610
        call RegisterItemToPool('rlif', 610, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Ring of Regeneration|r
        call RegisterItemToPool('rde1', 610, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Ring of Protection +2|r
        call RegisterItemToPool('rde2', 610, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Ring of Protection +3|r
        call RegisterItemToPool('i0a8', 610, ITEM_RARITY_RARE, 100, false)  // |c001EFF00TEST Solid Ring of Power|r
        // Level 611
        call RegisterItemToPool('jdrn', 611, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Jade Ring|r
        call RegisterItemToPool('rde3', 611, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Ring of Protection +4|r
        // Level 660
        call RegisterItemToPool('i0d2', 660, ITEM_RARITY_RARE, 100, false)  // |c001EFF00TEST Quality Trinket of the Bear|r
        // Level 710
        call RegisterItemToPool('i0c5', 710, ITEM_RARITY_RARE, 100, false)  // |c001EFF00Sturdy Other of the Bear|r
        call RegisterItemToPool('rat3', 710, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Claws of Attack +3|r
        call RegisterItemToPool('I68L', 710, ITEM_RARITY_RARE, 100, false)  // |c001EFF00Copper Chain Shoulders|r
        call RegisterItemToPool('i0c7', 710, ITEM_RARITY_RARE, 100, false)  // |c001EFF00Fine 1h of the Eagle|r
        // Level 711
        call RegisterItemToPool('rat6', 711, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Claws of Attack +6|r
        // Level 712
        call RegisterItemToPool('rat9', 712, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Claws of Attack +9|r
        // Level 713
        call RegisterItemToPool('ratc', 713, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Claws of Attack +12|r
        // Level 714
        call RegisterItemToPool('ratf', 714, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Claws of Attack +15|r
        call RegisterItemToPool('I6C1', 714, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Claws of Attack +20|r
        // Level 715
        call RegisterItemToPool('I6C2', 715, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Claws of Attack +24|r
        // Level 716
        call RegisterItemToPool('I68A', 716, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Nazgrek's Axe|r
        // Level 760
        call RegisterItemToPool('i0b0', 760, ITEM_RARITY_RARE, 100, false)  // |c001EFF00TEST Sturdy Blade of the Eagle|r
        call RegisterItemToPool('I60I', 760, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Steel Blade|r
        call RegisterItemToPool('I65K', 760, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Steel Longsword|r
        // Level 800
        call RegisterItemToPool('I65M', 800, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Polished Wooden Wand|r
        // Level 810
        call RegisterItemToPool('rots', 810, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Scepter of the Sea|r
        call RegisterItemToPool('I61I', 810, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Gnarled Staff|r
        call RegisterItemToPool('i0b9', 810, ITEM_RARITY_RARE, 100, false)  // |c001EFF00Sturdy Stave of the Bear|r
        call RegisterItemToPool('schl', 810, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Scepter of Healing|r
        call RegisterItemToPool('i1h2', 810, ITEM_RARITY_RARE, 100, false)  // |c001EFF00Divine Stave of the Bear|r
        call RegisterItemToPool('I68B', 810, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Shadowcaster's Scepter|r
        // Level 861
        call RegisterItemToPool('sksh', 861, ITEM_RARITY_RARE, 100, false)  // |c0090EE90Skull Shield|r

        // === ITEM_RARITY_EPIC ITEMS ===
        // Level 20
        call RegisterItemToPool('i1f7', 20, ITEM_RARITY_EPIC, 100, false)  // Stormvine Bubbles
        call RegisterItemToPool('i1e3', 20, ITEM_RARITY_EPIC, 100, false)  // Magebloom
        call RegisterItemToPool('i1e4', 20, ITEM_RARITY_EPIC, 100, false)  // Mana Thistle
        call RegisterItemToPool('i1c7', 20, ITEM_RARITY_EPIC, 100, false)  // Arthas' Tears
        call RegisterItemToPool('i1c8', 20, ITEM_RARITY_EPIC, 100, false)  // Azshara's Veil
        call RegisterItemToPool('i1e8', 20, ITEM_RARITY_EPIC, 100, false)  // Netherbloom
        call RegisterItemToPool('i1dd', 20, ITEM_RARITY_EPIC, 100, false)  // Golden Lotus
        call RegisterItemToPool('i1ce', 20, ITEM_RARITY_EPIC, 100, false)  // Crown Royal
        call RegisterItemToPool('i1ee', 20, ITEM_RARITY_EPIC, 100, false)  // Sha-Touched Herb
        call RegisterItemToPool('i1cb', 20, ITEM_RARITY_EPIC, 100, false)  // Chameleon Lotus
        call RegisterItemToPool('i1cf', 20, ITEM_RARITY_EPIC, 100, false)  // Dragon's Teeth
        call RegisterItemToPool('i203', 20, ITEM_RARITY_EPIC, 100, false)  // Whispervine
        call RegisterItemToPool('i1d7', 20, ITEM_RARITY_EPIC, 100, false)  // Flame Cap
        call RegisterItemToPool('i1f3', 20, ITEM_RARITY_EPIC, 100, false)  // Stardust
        // Level 120
        call RegisterItemToPool('rwiz', 120, ITEM_RARITY_EPIC, 100, false)  // |c000080FFSobi Mask|r
        // Level 170
        call RegisterItemToPool('i0b5', 170, ITEM_RARITY_EPIC, 100, false)  // |c000070DDReliable Neck of the Titan|r
        // Level 171
        call RegisterItemToPool('spsh', 171, ITEM_RARITY_EPIC, 100, false)  // |c000080FFAmulet of Spell Shield|r
        // Level 272
        call RegisterItemToPool('I65E', 272, ITEM_RARITY_EPIC, 100, false)  // |c000080FFRunebound Cloak|r
        // Level 300
        call RegisterItemToPool('I619', 300, ITEM_RARITY_EPIC, 100, false)  // |c000080FFNecromancer Robes|r
        // Level 320
        call RegisterItemToPool('i0c6', 320, ITEM_RARITY_EPIC, 100, false)  // |c000070DDSturdy Chest of the Warrior|r
        // Level 570
        call RegisterItemToPool('bspd', 570, ITEM_RARITY_EPIC, 100, false)  // |c000080FFBoots of Speed|r
        // Level 620
        call RegisterItemToPool('i1g1', 620, ITEM_RARITY_EPIC, 100, false)  // |c000070DDReliable Ring of the Warrior|r
        // Level 671
        call RegisterItemToPool('ajen', 671, ITEM_RARITY_EPIC, 100, false)  // |c000080FFAncient Janggo of Endurance|r
        // Level 720
        call RegisterItemToPool('i0c4', 720, ITEM_RARITY_EPIC, 100, false)  // |c000070DDSturdy Axe of the Phoenix|r
        // Level 770
        call RegisterItemToPool('i0c3', 770, ITEM_RARITY_EPIC, 100, false)  // |c000070DDQuality Weapon of Legends|r

        // === ITEM_RARITY_LEGENDARY ITEMS ===
        // Level 20
        call RegisterItemToPool('i1c9', 20, ITEM_RARITY_LEGENDARY, 100, false)  // Black Lotus
        call RegisterItemToPool('i1d9', 20, ITEM_RARITY_LEGENDARY, 100, false)  // Frost Lotus
        // Level 119
        call RegisterItemToPool('i0c9', 119, ITEM_RARITY_LEGENDARY, 100, false)  // |c00A335EEReliable Other of the Ancients|r
        // Level 136
        call RegisterItemToPool('I6CD', 136, ITEM_RARITY_LEGENDARY, 100, false)  // |c00800080Crown of of the Molten Golem King|r
        // Level 286
        call RegisterItemToPool('I6CC', 286, ITEM_RARITY_LEGENDARY, 100, false)  // |c00800080Cloak of Dragonbound Mountain|r
        // Level 300
        call RegisterItemToPool('I61A', 300, ITEM_RARITY_LEGENDARY, 100, false)  // |c00800080Lich Robe|r
        // Level 330
        call RegisterItemToPool('i0d0', 330, ITEM_RARITY_LEGENDARY, 100, false)  // |c00A335EETEST Chest of the Ancients|r
        // Level 336
        call RegisterItemToPool('I64U', 336, ITEM_RARITY_LEGENDARY, 100, false)  // |c00800080Shadowmantle Armor|r
        // Level 480
        call RegisterItemToPool('i0b7', 480, ITEM_RARITY_LEGENDARY, 100, false)  // |c00A335EEQuality Belt of the Ancients|r
        // Level 586
        call RegisterItemToPool('I65O', 586, ITEM_RARITY_LEGENDARY, 100, false)  // |c00800080Stormcaller Boots|r
        call RegisterItemToPool('I6CE', 586, ITEM_RARITY_LEGENDARY, 100, false)  // |c00800080Dragonforged Warboots|r
        // Level 736
        call RegisterItemToPool('I63R', 736, ITEM_RARITY_LEGENDARY, 100, false)  // |c00800080Stormcaller Mace|r
        // Level 786
        call RegisterItemToPool('I63N', 786, ITEM_RARITY_LEGENDARY, 100, false)  // |c00800080Vortex Warhammer|r
        call RegisterItemToPool('I6CB', 786, ITEM_RARITY_LEGENDARY, 100, false)  // |c00800080Blazing Obsidian Sharpblade|r
        call RegisterItemToPool('I65N', 786, ITEM_RARITY_LEGENDARY, 100, false)  // |c00800080Vortex Blade|r
        // Level 830
        call RegisterItemToPool('i0c2', 830, ITEM_RARITY_LEGENDARY, 100, false)  // |c00A335EESturdy Stave of Eternity|r
        // Level 882
        call RegisterItemToPool('shhn', 882, ITEM_RARITY_LEGENDARY, 100, false)  // |c00800080Shield of Honor|r
        // Level 884
        call RegisterItemToPool('shdt', 884, ITEM_RARITY_LEGENDARY, 100, false)  // |c00800080Shield of Deathlord|r
        // Level 886
        call RegisterItemToPool('I62O', 886, ITEM_RARITY_LEGENDARY, 100, false)  // |c00800080Stormguard|r

        // === ITEM_RARITY_ARTIFACT ITEMS ===
        // Level 90
        call RegisterItemToPool('i0d4', 90, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000Sturdy Miscellaneous of Creation|r
        // Level 190
        call RegisterItemToPool('i0b8', 190, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000Solid Neck of Creation|r
        // Level 240
        call RegisterItemToPool('i0g4', 240, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000TEST_stat_spellpowerPct|r
        call RegisterItemToPool('i0b3', 240, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000Test Solid Shoulders of Apocalypse|r
        // Level 340
        call RegisterItemToPool('i0e2', 340, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000TEST_stat_critchance|r
        call RegisterItemToPool('i0e5', 340, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000TEST_stat_meleeDMGPct|r
        call RegisterItemToPool('i0d7', 340, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000TEST_stat_int|r
        call RegisterItemToPool('i0e4', 340, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000TEST_stat_meleeDMG|r
        call RegisterItemToPool('i0e3', 340, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000TEST_stat_damage|r
        call RegisterItemToPool('i0d8', 340, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000TEST_stat_health|r
        call RegisterItemToPool('i0d9', 340, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000TEST_stat_hpregen|r
        call RegisterItemToPool('i0d6', 340, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000TEST_stat_agi|r
        call RegisterItemToPool('i0e6', 340, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000TEST_stat_rangedDMG|r
        call RegisterItemToPool('i0e7', 340, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000TEST_stat_rangedDMGPct|r
        call RegisterItemToPool('i0e1', 340, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000TEST_stat_manaregen|r
        call RegisterItemToPool('i0d5', 340, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000TEST_stat_str|r
        call RegisterItemToPool('i0e0', 340, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000TEST_stat_mana|r
        call RegisterItemToPool('i0e8', 340, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000TEST_stat_cleavePct|r
        // Level 390
        call RegisterItemToPool('i0c8', 390, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000Reliable Bracers of Infinity|r
        // Level 440
        call RegisterItemToPool('i0g7', 440, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000TEST_stat_meleetakenPctNeg|r
        call RegisterItemToPool('i0f4', 440, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000TEST_stat_armor|r
        call RegisterItemToPool('i0f5', 440, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000TEST_stat_armorPct|r
        call RegisterItemToPool('i0f6', 440, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000TEST_stat_dodge|r
        call RegisterItemToPool('i0f7', 440, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000TEST_stat_magictakenPct|r
        call RegisterItemToPool('i0f8', 440, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000TEST_stat_meleetakenPct|r
        call RegisterItemToPool('i0f9', 440, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000TEST_stat_piercetakenPct|r
        call RegisterItemToPool('i0g0', 440, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000TEST_stat_movementSpeed|r
        call RegisterItemToPool('i0g1', 440, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000TEST_stat_movementSpeedPct|r
        call RegisterItemToPool('i0g8', 440, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000TEST_stat_piercetakenPctNeg|r
        call RegisterItemToPool('i0g6', 440, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000TEST_stat_magictakenPctNeg|r
        // Level 490
        call RegisterItemToPool('i0f3', 490, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000TEST_stat_thornsPct|r
        call RegisterItemToPool('i0f2', 490, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000TEST_stat_thornsFlat|r
        // Level 590
        call RegisterItemToPool('i0g5', 590, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000TEST_stat_spellpowerFlat|r
        // Level 640
        call RegisterItemToPool('i0f1', 640, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000TEST_stat_lifesteal|r
        call RegisterItemToPool('i0f0', 640, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000TEST_stat_attackSpeed|r
        call RegisterItemToPool('i0e9', 640, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000TEST_stat_cleaveArea|r
        // Level 690
        call RegisterItemToPool('i1h0', 690, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000Eliaksen Hondan Avain|r
        // Level 790
        call RegisterItemToPool('i0g3', 790, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000TEST_stat_hit|r
        call RegisterItemToPool('i0b4', 790, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000Sturdy Weapon of the Warrior|r
        // Level 890
        call RegisterItemToPool('i0g2', 890, ITEM_RARITY_ARTIFACT, 100, false)  // |c00FF8000TEST_stat_block|r

    endfunction

    private function RegisterAllTiers takes nothing returns nothing
        call DestroyTimer(GetExpiredTimer())

        // === LOOT TIER DEFINITIONS ===
        // RegisterLootTier(tierId, minLevel, maxLevel, dropChance)
        // RegisterTierRarity(tierId, rarityId, itemLevel, weight)

        // TIER_1_5: Units level 1-5
        call RegisterLootTier(1, 1, 5, 1500)
        call RegisterTierRarity(1, ITEM_RARITY_COMMON, 5, 60)
        call RegisterTierRarity(1, ITEM_RARITY_UNCOMMON, 10, 25)
        call RegisterTierRarity(1, ITEM_RARITY_RARE, 15, 15)

        // TIER_6_10: Units level 6-10
        call RegisterLootTier(2, 6, 10, 1200)
        call RegisterTierRarity(2, ITEM_RARITY_COMMON, 10, 55)
        call RegisterTierRarity(2, ITEM_RARITY_UNCOMMON, 15, 28)
        call RegisterTierRarity(2, ITEM_RARITY_RARE, 20, 14)
        call RegisterTierRarity(2, ITEM_RARITY_EPIC, 25, 3)

        // TIER_11_15: Units level 11-15
        call RegisterLootTier(3, 11, 15, 1000)
        call RegisterTierRarity(3, ITEM_RARITY_COMMON, 15, 50)
        call RegisterTierRarity(3, ITEM_RARITY_UNCOMMON, 20, 28)
        call RegisterTierRarity(3, ITEM_RARITY_RARE, 25, 15)
        call RegisterTierRarity(3, ITEM_RARITY_EPIC, 30, 5)
        call RegisterTierRarity(3, ITEM_RARITY_LEGENDARY, 35, 2)

        // TIER_16_20: Units level 16-20
        call RegisterLootTier(4, 16, 20, 800)
        call RegisterTierRarity(4, ITEM_RARITY_COMMON, 20, 45)
        call RegisterTierRarity(4, ITEM_RARITY_UNCOMMON, 25, 30)
        call RegisterTierRarity(4, ITEM_RARITY_RARE, 30, 16)
        call RegisterTierRarity(4, ITEM_RARITY_EPIC, 35, 6)
        call RegisterTierRarity(4, ITEM_RARITY_LEGENDARY, 40, 3)

        // TIER_21_25: Units level 21-25
        call RegisterLootTier(5, 21, 25, 600)
        call RegisterTierRarity(5, ITEM_RARITY_COMMON, 25, 40)
        call RegisterTierRarity(5, ITEM_RARITY_UNCOMMON, 30, 30)
        call RegisterTierRarity(5, ITEM_RARITY_RARE, 35, 18)
        call RegisterTierRarity(5, ITEM_RARITY_EPIC, 40, 8)
        call RegisterTierRarity(5, ITEM_RARITY_LEGENDARY, 45, 3)
        call RegisterTierRarity(5, ITEM_RARITY_ARTIFACT, 50, 1)

        // TIER_26_30: Units level 26-30
        call RegisterLootTier(6, 26, 30, 500)
        call RegisterTierRarity(6, ITEM_RARITY_COMMON, 30, 35)
        call RegisterTierRarity(6, ITEM_RARITY_UNCOMMON, 35, 30)
        call RegisterTierRarity(6, ITEM_RARITY_RARE, 40, 20)
        call RegisterTierRarity(6, ITEM_RARITY_EPIC, 45, 10)
        call RegisterTierRarity(6, ITEM_RARITY_LEGENDARY, 50, 4)
        call RegisterTierRarity(6, ITEM_RARITY_ARTIFACT, 55, 1)

        // TIER_31_PLUS: Units level 31-99
        call RegisterLootTier(7, 31, 99, 400)
        call RegisterTierRarity(7, ITEM_RARITY_COMMON, 35, 30)
        call RegisterTierRarity(7, ITEM_RARITY_UNCOMMON, 40, 28)
        call RegisterTierRarity(7, ITEM_RARITY_RARE, 45, 22)
        call RegisterTierRarity(7, ITEM_RARITY_EPIC, 50, 12)
        call RegisterTierRarity(7, ITEM_RARITY_LEGENDARY, 55, 6)
        call RegisterTierRarity(7, ITEM_RARITY_ARTIFACT, 60, 2)

        // === ITEM POOL REGISTRATION ===
        call RegisterItemPools()
    endfunction

    private function Init takes nothing returns nothing
        // Tier registration delayed to allow ItemLootSystem to initialize
        call TimerStart(CreateTimer(), 0.01, false, function RegisterAllTiers)
    endfunction

endlibrary
