//===========================================================================
// ItemLootDefinitionsSpecific.j
// Generated by WC3ItemManager - DO NOT EDIT MANUALLY
// Generated: 2026-07-28 22.56.24
//===========================================================================

library ItemLootDefinitionsSpecific initializer Init requires ItemLootSystem

    private function RegisterAllSpecificDrops takes nothing returns nothing
        call DestroyTimer(GetExpiredTimer())

        // === SPECIFIC/BOSS DROP DEFINITIONS ===
        // RegisterSpecificDrop(unitTypeId, itemTypeId, dropChance, isGuaranteed, weight)

        // Faerie Dragon Ghost ('e001')
        call RegisterSpecificDrop('e001', 'I00S', 4000, false, 95)  // Whelp Scale
        call RegisterSpecificDrop('e001', 'I00X', 1667, false, 80)  // Sharp Claw
        call RegisterSpecificDrop('e001', 'I00W', 1667, false, 70)  // Ruined Dragonhide
        call RegisterSpecificDrop('e001', 'I00V', 1667, false, 70)  // Small Flame Sac
        call RegisterSpecificDrop('e001', 'j0b6', 1200, false, 60)  // |c001EFF00Charred Whelp Horn|r
        call RegisterSpecificDrop('e001', 'j0b7', 800, false, 35)  // |c000070DDEmber-Warmed Scale|r

        // Enraged Faerie Dragon ('e60C')
        call RegisterSpecificDrop('e60C', 'I00S', 4000, false, 95)  // Whelp Scale
        call RegisterSpecificDrop('e60C', 'I00V', 1667, false, 70)  // Small Flame Sac
        call RegisterSpecificDrop('e60C', 'I00X', 1667, false, 80)  // Sharp Claw
        call RegisterSpecificDrop('e60C', 'I00W', 1667, false, 70)  // Ruined Dragonhide
        call RegisterSpecificDrop('e60C', 'j0b6', 1200, false, 60)  // |c001EFF00Charred Whelp Horn|r
        call RegisterSpecificDrop('e60C', 'j0b7', 800, false, 35)  // |c000070DDEmber-Warmed Scale|r

        // Dummy ('h000')
        call RegisterSpecificDrop('h000', 'i0c3', 1000, false, 100)  // |c000070DDQuality Weapon of Legends|r

        // Air Elemental ('h60D')
        call RegisterSpecificDrop('h60D', 'I6C7', 5500, false, 100)  // |c0090EE90Essence of Air|r

        // Ghost Wolf ('H60K')
        call RegisterSpecificDrop('H60K', 'I61F', 1667, false, 90)  // Wolf Skin
        call RegisterSpecificDrop('H60K', 'I6AR', 1667, false, 90)  // Wolf Jawbone
        call RegisterSpecificDrop('H60K', 'j0a0', 1200, false, 70)  // |c009D9D9DFrayed Wolf Pelt|r
        call RegisterSpecificDrop('H60K', 'I61O', 1000, false, 100)  // Raw Wolf Meat
        call RegisterSpecificDrop('H60K', 'j0c6', 600, false, 30)  // |cFF1EFF00Smoked Wolf Jerky|r

        // Dragon Egg ('h60R')
        call RegisterSpecificDrop('h60R', 'I00S', 4000, false, 95)  // Whelp Scale
        call RegisterSpecificDrop('h60R', 'I00W', 1667, false, 70)  // Ruined Dragonhide
        call RegisterSpecificDrop('h60R', 'I00X', 1667, false, 80)  // Sharp Claw
        call RegisterSpecificDrop('h60R', 'I00V', 1667, false, 70)  // Small Flame Sac
        call RegisterSpecificDrop('h60R', 'j0b6', 1200, false, 60)  // |c001EFF00Charred Whelp Horn|r
        call RegisterSpecificDrop('h60R', 'j0b7', 800, false, 35)  // |c000070DDEmber-Warmed Scale|r

        // Ember Salamander ('n01U')
        call RegisterSpecificDrop('n01U', 'I61G', 2000, false, 80)  // Thunder Lizard Skin
        call RegisterSpecificDrop('n01U', 'I61R', 1000, false, 100)  // Raw Lizard Meat
        call RegisterSpecificDrop('n01U', 'j0b7', 800, false, 35)  // |c000070DDEmber-Warmed Scale|r

        // Ember Salamander ('n01V')
        call RegisterSpecificDrop('n01V', 'I61G', 2000, false, 80)  // Thunder Lizard Skin
        call RegisterSpecificDrop('n01V', 'I61R', 1000, false, 100)  // Raw Lizard Meat
        call RegisterSpecificDrop('n01V', 'j0b7', 800, false, 35)  // |c000070DDEmber-Warmed Scale|r

        // MordraxDummy ('n022')
        call RegisterSpecificDrop('n022', 'j1d0', 4500, false, 100)  // |c00A335EEIronbound Legplates|r

        // Salamander Hazzling ('n02K')
        call RegisterSpecificDrop('n02K', 'I61G', 2000, false, 80)  // Thunder Lizard Skin
        call RegisterSpecificDrop('n02K', 'I61R', 1000, false, 100)  // Raw Lizard Meat
        call RegisterSpecificDrop('n02K', 'j0b7', 800, false, 35)  // |c000070DDEmber-Warmed Scale|r

        // Rol'jin ('n605')
        call RegisterSpecificDrop('n605', 'j1b9', 2500, false, 100)  // |c001EFF00Stormlink Wristguards|r

        // Mur'gal ('n607')
        call RegisterSpecificDrop('n607', 'I6AE', 3333, false, 90)  // Murloc Fin
        call RegisterSpecificDrop('n607', 'j1c0', 3000, false, 100)  // |c000070DDStormlink Grips|r
        call RegisterSpecificDrop('n607', 'I610', 1500, false, 60)  // Murloc Head
        call RegisterSpecificDrop('n607', 'j0a6', 1400, false, 70)  // |c009D9D9DMurloc Gill Slime|r
        call RegisterSpecificDrop('n607', 'j0a7', 1200, false, 55)  // |c001EFF00Briny Murloc Scale|r
        call RegisterSpecificDrop('n607', 'I61T', 1000, false, 100)  // Raw Murloc Meat

        // Deathlord Fel'Dok ('n609')
        call RegisterSpecificDrop('n609', 'I60Z', 10000, false, 100)  // |cFFFFFFFFSpring Water|r
        call RegisterSpecificDrop('n609', 'phea', 10000, false, 100)  // Healing Potion
        call RegisterSpecificDrop('n609', 'i0c3', 10000, false, 100)  // |c000070DDQuality Weapon of Legends|r
        call RegisterSpecificDrop('n609', 'i0c6', 5500, false, 100)  // |c000070DDSturdy Chest of the Warrior|r
        call RegisterSpecificDrop('n609', 'j1c4', 3500, false, 100)  // |c000070DDIronbound Greathelm|r
        call RegisterSpecificDrop('n609', 'j1c6', 3500, false, 100)  // |c00A335EEIronbound Breastplate|r
        call RegisterSpecificDrop('n609', 'I69A', 2500, false, 80)  // Gnoll Head
        call RegisterSpecificDrop('n609', 'j0a4', 1200, false, 60)  // |c009D9D9DGnoll Coin Pouch|r
        call RegisterSpecificDrop('n609', 'j0a5', 1000, false, 50)  // |c009D9D9DBent Gnoll Dagger|r
        call RegisterSpecificDrop('n609', 'j0c0', 800, false, 40)  // |c009D9D9DRagged Banner Scrap|r
        call RegisterSpecificDrop('n609', 'j1b1', 400, false, 20)  // |c009D9D9DTrailscarred Leather Bracers|r
        call RegisterSpecificDrop('n609', 'j1b9', 300, false, 12)  // |c001EFF00Stormlink Wristguards|r

        // Gnoll Poacher (Elite) ('n60E')
        call RegisterSpecificDrop('n60E', 'I69A', 2500, false, 80)  // Gnoll Head
        call RegisterSpecificDrop('n60E', 'j0a4', 1200, false, 60)  // |c009D9D9DGnoll Coin Pouch|r
        call RegisterSpecificDrop('n60E', 'j0a5', 1000, false, 50)  // |c009D9D9DBent Gnoll Dagger|r
        call RegisterSpecificDrop('n60E', 'j0c0', 800, false, 40)  // |c009D9D9DRagged Banner Scrap|r
        call RegisterSpecificDrop('n60E', 'j1b1', 400, false, 20)  // |c009D9D9DTrailscarred Leather Bracers|r
        call RegisterSpecificDrop('n60E', 'j1b9', 300, false, 12)  // |c001EFF00Stormlink Wristguards|r

        // Gnoll Assasin (Elite) ('n60F')
        call RegisterSpecificDrop('n60F', 'I69A', 2500, false, 80)  // Gnoll Head
        call RegisterSpecificDrop('n60F', 'j0a4', 1200, false, 60)  // |c009D9D9DGnoll Coin Pouch|r
        call RegisterSpecificDrop('n60F', 'j0a5', 1000, false, 50)  // |c009D9D9DBent Gnoll Dagger|r
        call RegisterSpecificDrop('n60F', 'j0c0', 800, false, 40)  // |c009D9D9DRagged Banner Scrap|r
        call RegisterSpecificDrop('n60F', 'j1b1', 400, false, 20)  // |c009D9D9DTrailscarred Leather Bracers|r
        call RegisterSpecificDrop('n60F', 'j1b9', 300, false, 12)  // |c001EFF00Stormlink Wristguards|r

        // Gnoll (Elite) ('n60G')
        call RegisterSpecificDrop('n60G', 'I69A', 2500, false, 80)  // Gnoll Head
        call RegisterSpecificDrop('n60G', 'j0a4', 1200, false, 60)  // |c009D9D9DGnoll Coin Pouch|r
        call RegisterSpecificDrop('n60G', 'j0a5', 1000, false, 50)  // |c009D9D9DBent Gnoll Dagger|r
        call RegisterSpecificDrop('n60G', 'j0c0', 800, false, 40)  // |c009D9D9DRagged Banner Scrap|r
        call RegisterSpecificDrop('n60G', 'j1b1', 400, false, 20)  // |c009D9D9DTrailscarred Leather Bracers|r
        call RegisterSpecificDrop('n60G', 'j1b9', 300, false, 12)  // |c001EFF00Stormlink Wristguards|r

        // Gnoll Brute (Elite) ('n60H')
        call RegisterSpecificDrop('n60H', 'I69A', 2500, false, 80)  // Gnoll Head
        call RegisterSpecificDrop('n60H', 'j0a4', 1200, false, 60)  // |c009D9D9DGnoll Coin Pouch|r
        call RegisterSpecificDrop('n60H', 'j0a5', 1000, false, 50)  // |c009D9D9DBent Gnoll Dagger|r
        call RegisterSpecificDrop('n60H', 'j0c0', 800, false, 40)  // |c009D9D9DRagged Banner Scrap|r
        call RegisterSpecificDrop('n60H', 'j1b1', 400, false, 20)  // |c009D9D9DTrailscarred Leather Bracers|r
        call RegisterSpecificDrop('n60H', 'j1b9', 300, false, 12)  // |c001EFF00Stormlink Wristguards|r

        // Gnoll Warden (Elite) ('n60I')
        call RegisterSpecificDrop('n60I', 'I69A', 2500, false, 80)  // Gnoll Head
        call RegisterSpecificDrop('n60I', 'j0a4', 1200, false, 60)  // |c009D9D9DGnoll Coin Pouch|r
        call RegisterSpecificDrop('n60I', 'j0a5', 1000, false, 50)  // |c009D9D9DBent Gnoll Dagger|r
        call RegisterSpecificDrop('n60I', 'j0c0', 800, false, 40)  // |c009D9D9DRagged Banner Scrap|r
        call RegisterSpecificDrop('n60I', 'j1b1', 400, false, 20)  // |c009D9D9DTrailscarred Leather Bracers|r
        call RegisterSpecificDrop('n60I', 'j1b9', 300, false, 12)  // |c001EFF00Stormlink Wristguards|r

        // Gnoll Overseer (Elite) ('n60J')
        call RegisterSpecificDrop('n60J', 'I69A', 2500, false, 80)  // Gnoll Head
        call RegisterSpecificDrop('n60J', 'j0a4', 1200, false, 60)  // |c009D9D9DGnoll Coin Pouch|r
        call RegisterSpecificDrop('n60J', 'j0a5', 1000, false, 50)  // |c009D9D9DBent Gnoll Dagger|r
        call RegisterSpecificDrop('n60J', 'j0c0', 800, false, 40)  // |c009D9D9DRagged Banner Scrap|r
        call RegisterSpecificDrop('n60J', 'j1b1', 400, false, 20)  // |c009D9D9DTrailscarred Leather Bracers|r
        call RegisterSpecificDrop('n60J', 'j1b9', 300, false, 12)  // |c001EFF00Stormlink Wristguards|r

        // Gnoll Curser (Elite) ('n60K')
        call RegisterSpecificDrop('n60K', 'I69A', 2500, false, 80)  // Gnoll Head
        call RegisterSpecificDrop('n60K', 'j0a4', 1200, false, 60)  // |c009D9D9DGnoll Coin Pouch|r
        call RegisterSpecificDrop('n60K', 'j0a5', 1000, false, 50)  // |c009D9D9DBent Gnoll Dagger|r
        call RegisterSpecificDrop('n60K', 'j0c0', 800, false, 40)  // |c009D9D9DRagged Banner Scrap|r
        call RegisterSpecificDrop('n60K', 'j1b1', 400, false, 20)  // |c009D9D9DTrailscarred Leather Bracers|r
        call RegisterSpecificDrop('n60K', 'j1b9', 300, false, 12)  // |c001EFF00Stormlink Wristguards|r

        // Gnoll Necromancer ('n60O')
        call RegisterSpecificDrop('n60O', 'I69A', 2500, false, 80)  // Gnoll Head
        call RegisterSpecificDrop('n60O', 'j0a4', 1200, false, 60)  // |c009D9D9DGnoll Coin Pouch|r
        call RegisterSpecificDrop('n60O', 'j0a5', 1000, false, 50)  // |c009D9D9DBent Gnoll Dagger|r
        call RegisterSpecificDrop('n60O', 'j0c0', 800, false, 40)  // |c009D9D9DRagged Banner Scrap|r
        call RegisterSpecificDrop('n60O', 'j1b1', 400, false, 20)  // |c009D9D9DTrailscarred Leather Bracers|r
        call RegisterSpecificDrop('n60O', 'j1b9', 300, false, 12)  // |c001EFF00Stormlink Wristguards|r

        // Gnoll Assasin Rogue (Elite) ('n60P')
        call RegisterSpecificDrop('n60P', 'I69A', 2500, false, 80)  // Gnoll Head
        call RegisterSpecificDrop('n60P', 'j0a4', 1200, false, 60)  // |c009D9D9DGnoll Coin Pouch|r
        call RegisterSpecificDrop('n60P', 'j0a5', 1000, false, 50)  // |c009D9D9DBent Gnoll Dagger|r
        call RegisterSpecificDrop('n60P', 'j0c0', 800, false, 40)  // |c009D9D9DRagged Banner Scrap|r
        call RegisterSpecificDrop('n60P', 'j1b1', 400, false, 20)  // |c009D9D9DTrailscarred Leather Bracers|r
        call RegisterSpecificDrop('n60P', 'j1b9', 300, false, 12)  // |c001EFF00Stormlink Wristguards|r

        // Margul ('n60R')
        call RegisterSpecificDrop('n60R', 'I6AE', 3333, false, 90)  // Murloc Fin
        call RegisterSpecificDrop('n60R', 'j1b8', 3000, false, 100)  // |c000070DDStormlink Hauberk|r
        call RegisterSpecificDrop('n60R', 'I610', 1500, false, 60)  // Murloc Head
        call RegisterSpecificDrop('n60R', 'j0a6', 1400, false, 70)  // |c009D9D9DMurloc Gill Slime|r
        call RegisterSpecificDrop('n60R', 'j0a7', 1200, false, 55)  // |c001EFF00Briny Murloc Scale|r
        call RegisterSpecificDrop('n60R', 'I61T', 1000, false, 100)  // Raw Murloc Meat

        // Gnoll Ravager ('n61A')
        call RegisterSpecificDrop('n61A', 'I69A', 2500, false, 80)  // Gnoll Head
        call RegisterSpecificDrop('n61A', 'j0a4', 1200, false, 60)  // |c009D9D9DGnoll Coin Pouch|r
        call RegisterSpecificDrop('n61A', 'j0a5', 1000, false, 50)  // |c009D9D9DBent Gnoll Dagger|r
        call RegisterSpecificDrop('n61A', 'j0c0', 800, false, 40)  // |c009D9D9DRagged Banner Scrap|r
        call RegisterSpecificDrop('n61A', 'j1b1', 400, false, 20)  // |c009D9D9DTrailscarred Leather Bracers|r
        call RegisterSpecificDrop('n61A', 'j1b9', 300, false, 12)  // |c001EFF00Stormlink Wristguards|r

        // Wolf (Mount) ('n61B')
        call RegisterSpecificDrop('n61B', 'I61F', 1667, false, 90)  // Wolf Skin
        call RegisterSpecificDrop('n61B', 'I6AR', 1667, false, 90)  // Wolf Jawbone
        call RegisterSpecificDrop('n61B', 'j0a0', 1200, false, 70)  // |c009D9D9DFrayed Wolf Pelt|r
        call RegisterSpecificDrop('n61B', 'I61O', 1000, false, 100)  // Raw Wolf Meat
        call RegisterSpecificDrop('n61B', 'j0c6', 600, false, 30)  // |cFF1EFF00Smoked Wolf Jerky|r

        // Snake ('n61M')
        call RegisterSpecificDrop('n61M', 'j0b0', 2000, false, 80)  // |c009D9D9DShed Snake Scale|r
        call RegisterSpecificDrop('n61M', 'I61Y', 1000, false, 100)  // Raw Snake Meat
        call RegisterSpecificDrop('n61M', 'j0b1', 1000, false, 50)  // |c001EFF00Clouded Venom Fang|r
        call RegisterSpecificDrop('n61M', 'j0d0', 600, false, 30)  // |cFF1EFF00Spiced Snake Strips|r

        // Skeleton Paladin ('n61V')
        call RegisterSpecificDrop('n61V', 'I66P', 2000, false, 100)  // Rotten Part
        call RegisterSpecificDrop('n61V', 'j0b8', 1200, false, 65)  // |c009D9D9DGrave Moss|r
        call RegisterSpecificDrop('n61V', 'j0b9', 1200, false, 65)  // |c009D9D9DRotten Rib|r
        call RegisterSpecificDrop('n61V', 'j1a3', 300, false, 15)  // |c009D9D9DMistwoven Wraps|r

        // Unknown Entity ('n621')
        call RegisterSpecificDrop('n621', 'j1a4', 2500, false, 100)  // |c001EFF00Mistwoven Gloves|r

        // Sargoth ('n622')
        call RegisterSpecificDrop('n622', 'j1c4', 3500, false, 100)  // |c000070DDIronbound Greathelm|r

        // Gnoll Crusher ('n626')
        call RegisterSpecificDrop('n626', 'I69A', 2500, false, 80)  // Gnoll Head
        call RegisterSpecificDrop('n626', 'j0a4', 1200, false, 60)  // |c009D9D9DGnoll Coin Pouch|r
        call RegisterSpecificDrop('n626', 'j0a5', 1000, false, 50)  // |c009D9D9DBent Gnoll Dagger|r
        call RegisterSpecificDrop('n626', 'j0c0', 800, false, 40)  // |c009D9D9DRagged Banner Scrap|r
        call RegisterSpecificDrop('n626', 'j1b1', 400, false, 20)  // |c009D9D9DTrailscarred Leather Bracers|r
        call RegisterSpecificDrop('n626', 'j1b9', 300, false, 12)  // |c001EFF00Stormlink Wristguards|r

        // Murloc Sorcerer ('n62A')
        call RegisterSpecificDrop('n62A', 'I6AE', 3333, false, 90)  // Murloc Fin
        call RegisterSpecificDrop('n62A', 'I610', 1500, false, 60)  // Murloc Head
        call RegisterSpecificDrop('n62A', 'j0a6', 1400, false, 70)  // |c009D9D9DMurloc Gill Slime|r
        call RegisterSpecificDrop('n62A', 'j0a7', 1200, false, 55)  // |c001EFF00Briny Murloc Scale|r
        call RegisterSpecificDrop('n62A', 'I61T', 1000, false, 100)  // Raw Murloc Meat

        // Murloc Tidecaller ('n62B')
        call RegisterSpecificDrop('n62B', 'I6AE', 3333, false, 90)  // Murloc Fin
        call RegisterSpecificDrop('n62B', 'I610', 1500, false, 60)  // Murloc Head
        call RegisterSpecificDrop('n62B', 'j0a6', 1400, false, 70)  // |c009D9D9DMurloc Gill Slime|r
        call RegisterSpecificDrop('n62B', 'j0a7', 1200, false, 55)  // |c001EFF00Briny Murloc Scale|r
        call RegisterSpecificDrop('n62B', 'I61T', 1000, false, 100)  // Raw Murloc Meat

        // Velaria ('n636')
        call RegisterSpecificDrop('n636', 'j1a2', 2500, false, 100)  // |c001EFF00Mistwoven Robe|r

        // Scorching Whelp ('n637')
        call RegisterSpecificDrop('n637', 'I00S', 4000, false, 95)  // Whelp Scale
        call RegisterSpecificDrop('n637', 'I00X', 1667, false, 80)  // Sharp Claw
        call RegisterSpecificDrop('n637', 'I00V', 1667, false, 70)  // Small Flame Sac
        call RegisterSpecificDrop('n637', 'I00W', 1667, false, 70)  // Ruined Dragonhide
        call RegisterSpecificDrop('n637', 'j0b6', 1200, false, 60)  // |c001EFF00Charred Whelp Horn|r
        call RegisterSpecificDrop('n637', 'j0b7', 800, false, 35)  // |c000070DDEmber-Warmed Scale|r

        // Red Whelp ('n639')
        call RegisterSpecificDrop('n639', 'I00S', 4000, false, 95)  // Whelp Scale
        call RegisterSpecificDrop('n639', 'I00W', 1667, false, 70)  // Ruined Dragonhide
        call RegisterSpecificDrop('n639', 'I00V', 1667, false, 70)  // Small Flame Sac
        call RegisterSpecificDrop('n639', 'I00X', 1667, false, 80)  // Sharp Claw
        call RegisterSpecificDrop('n639', 'j0b6', 1200, false, 60)  // |c001EFF00Charred Whelp Horn|r
        call RegisterSpecificDrop('n639', 'j0b7', 800, false, 35)  // |c000070DDEmber-Warmed Scale|r

        // Scorching Dragon ('n63F')
        call RegisterSpecificDrop('n63F', 'I00S', 4000, false, 95)  // Whelp Scale
        call RegisterSpecificDrop('n63F', 'I00V', 1667, false, 70)  // Small Flame Sac
        call RegisterSpecificDrop('n63F', 'I00W', 1667, false, 70)  // Ruined Dragonhide
        call RegisterSpecificDrop('n63F', 'I00X', 1667, false, 80)  // Sharp Claw
        call RegisterSpecificDrop('n63F', 'j0b6', 1200, false, 60)  // |c001EFF00Charred Whelp Horn|r
        call RegisterSpecificDrop('n63F', 'j0b7', 800, false, 35)  // |c000070DDEmber-Warmed Scale|r

        // Red Dragon ('n644')
        call RegisterSpecificDrop('n644', 'I00S', 4000, false, 95)  // Whelp Scale
        call RegisterSpecificDrop('n644', 'I00V', 1667, false, 70)  // Small Flame Sac
        call RegisterSpecificDrop('n644', 'I00W', 1667, false, 70)  // Ruined Dragonhide
        call RegisterSpecificDrop('n644', 'I00X', 1667, false, 80)  // Sharp Claw
        call RegisterSpecificDrop('n644', 'j0b6', 1200, false, 60)  // |c001EFF00Charred Whelp Horn|r
        call RegisterSpecificDrop('n644', 'j0b7', 800, false, 35)  // |c000070DDEmber-Warmed Scale|r

        // Mordrax the Desolator ('n645')
        call RegisterSpecificDrop('n645', 'j1d0', 4500, false, 100)  // |c00A335EEIronbound Legplates|r

        // Colossus ('n646')
        call RegisterSpecificDrop('n646', 'j1c6', 4500, false, 100)  // |c00A335EEIronbound Breastplate|r
        call RegisterSpecificDrop('n646', 'j1d0', 4500, false, 100)  // |c00A335EEIronbound Legplates|r

        // Wolf Mother ('n648')
        call RegisterSpecificDrop('n648', 'I61F', 1667, false, 90)  // Wolf Skin
        call RegisterSpecificDrop('n648', 'I6AR', 1667, false, 90)  // Wolf Jawbone
        call RegisterSpecificDrop('n648', 'j0a0', 1200, false, 70)  // |c009D9D9DFrayed Wolf Pelt|r
        call RegisterSpecificDrop('n648', 'I61O', 1000, false, 100)  // Raw Wolf Meat
        call RegisterSpecificDrop('n648', 'j0c6', 600, false, 30)  // |cFF1EFF00Smoked Wolf Jerky|r

        // Alpha Wolf ('n64B')
        call RegisterSpecificDrop('n64B', 'I61F', 1667, false, 90)  // Wolf Skin
        call RegisterSpecificDrop('n64B', 'I6AR', 1667, false, 90)  // Wolf Jawbone
        call RegisterSpecificDrop('n64B', 'j0a0', 1200, false, 70)  // |c009D9D9DFrayed Wolf Pelt|r
        call RegisterSpecificDrop('n64B', 'I61O', 1000, false, 100)  // Raw Wolf Meat
        call RegisterSpecificDrop('n64B', 'j0c6', 600, false, 30)  // |cFF1EFF00Smoked Wolf Jerky|r

        // Skeletal Archer ('n64V')
        call RegisterSpecificDrop('n64V', 'I66P', 2000, false, 100)  // Rotten Part
        call RegisterSpecificDrop('n64V', 'j0b8', 1200, false, 65)  // |c009D9D9DGrave Moss|r
        call RegisterSpecificDrop('n64V', 'j0b9', 1200, false, 65)  // |c009D9D9DRotten Rib|r
        call RegisterSpecificDrop('n64V', 'j1a3', 300, false, 15)  // |c009D9D9DMistwoven Wraps|r

        // Scorching Dragon ('n656')
        call RegisterSpecificDrop('n656', 'I00S', 4000, false, 95)  // Whelp Scale
        call RegisterSpecificDrop('n656', 'I00V', 1667, false, 70)  // Small Flame Sac
        call RegisterSpecificDrop('n656', 'I00W', 1667, false, 70)  // Ruined Dragonhide
        call RegisterSpecificDrop('n656', 'I00X', 1667, false, 80)  // Sharp Claw
        call RegisterSpecificDrop('n656', 'j0b6', 1200, false, 60)  // |c001EFF00Charred Whelp Horn|r
        call RegisterSpecificDrop('n656', 'j0b7', 800, false, 35)  // |c000070DDEmber-Warmed Scale|r

        // Scorching Whelp ('n658')
        call RegisterSpecificDrop('n658', 'I00S', 4000, false, 95)  // Whelp Scale
        call RegisterSpecificDrop('n658', 'I00V', 1667, false, 70)  // Small Flame Sac
        call RegisterSpecificDrop('n658', 'I00W', 1667, false, 70)  // Ruined Dragonhide
        call RegisterSpecificDrop('n658', 'I00X', 1667, false, 80)  // Sharp Claw
        call RegisterSpecificDrop('n658', 'j0b6', 1200, false, 60)  // |c001EFF00Charred Whelp Horn|r
        call RegisterSpecificDrop('n658', 'j0b7', 800, false, 35)  // |c000070DDEmber-Warmed Scale|r

        // Red Whelp ('n659')
        call RegisterSpecificDrop('n659', 'I00S', 4000, false, 95)  // Whelp Scale
        call RegisterSpecificDrop('n659', 'I00V', 1667, false, 70)  // Small Flame Sac
        call RegisterSpecificDrop('n659', 'I00W', 1667, false, 70)  // Ruined Dragonhide
        call RegisterSpecificDrop('n659', 'I00X', 1667, false, 80)  // Sharp Claw
        call RegisterSpecificDrop('n659', 'j0b6', 1200, false, 60)  // |c001EFF00Charred Whelp Horn|r
        call RegisterSpecificDrop('n659', 'j0b7', 800, false, 35)  // |c000070DDEmber-Warmed Scale|r

        // Red Dragon ('n65B')
        call RegisterSpecificDrop('n65B', 'I00S', 4000, false, 95)  // Whelp Scale
        call RegisterSpecificDrop('n65B', 'I00V', 1667, false, 70)  // Small Flame Sac
        call RegisterSpecificDrop('n65B', 'I00W', 1667, false, 70)  // Ruined Dragonhide
        call RegisterSpecificDrop('n65B', 'I00X', 1667, false, 80)  // Sharp Claw
        call RegisterSpecificDrop('n65B', 'j0b6', 1200, false, 60)  // |c001EFF00Charred Whelp Horn|r
        call RegisterSpecificDrop('n65B', 'j0b7', 800, false, 35)  // |c000070DDEmber-Warmed Scale|r

        // Diseased Stag ('n65D')
        call RegisterSpecificDrop('n65D', 'I614', 2500, false, 90)  // Stag Hair
        call RegisterSpecificDrop('n65D', 'I6AS', 1667, false, 70)  // Large Hoof
        call RegisterSpecificDrop('n65D', 'j0a2', 1200, false, 60)  // |c009D9D9DPolished Stag Antler|r
        call RegisterSpecificDrop('n65D', 'I61P', 1000, false, 100)  // Raw Stag Meat
        call RegisterSpecificDrop('n65D', 'j0c7', 600, false, 30)  // |cFF1EFF00Roasted Stag Haunch|r

        // Fel Boar ('n65J')
        call RegisterSpecificDrop('n65J', 'j0a1', 1800, false, 70)  // |c009D9D9DCracked Boar Tusk|r
        call RegisterSpecificDrop('n65J', 'I61C', 1500, false, 80)  // Boar Skin
        call RegisterSpecificDrop('n65J', 'I620', 1000, false, 100)  // Raw Boar Meat

        // Fel Boar ('n65K')
        call RegisterSpecificDrop('n65K', 'j0a1', 1800, false, 70)  // |c009D9D9DCracked Boar Tusk|r
        call RegisterSpecificDrop('n65K', 'I61C', 1500, false, 80)  // Boar Skin
        call RegisterSpecificDrop('n65K', 'I620', 1000, false, 100)  // Raw Boar Meat

        // Fel Boar ('n65L')
        call RegisterSpecificDrop('n65L', 'j0a1', 1800, false, 70)  // |c009D9D9DCracked Boar Tusk|r
        call RegisterSpecificDrop('n65L', 'I61C', 1500, false, 80)  // Boar Skin
        call RegisterSpecificDrop('n65L', 'I620', 1000, false, 100)  // Raw Boar Meat

        // Bear Cub ('ngz1')
        call RegisterSpecificDrop('ngz1', 'I6AB', 2000, false, 80)  // Big Bear Tooth
        call RegisterSpecificDrop('ngz1', 'I61B', 2000, false, 90)  // Bear Skin
        call RegisterSpecificDrop('ngz1', 'j0a3', 1200, false, 60)  // |c001EFF00Bear Grease|r
        call RegisterSpecificDrop('ngz1', 'I61Q', 1000, false, 100)  // Raw Bear Meat
        call RegisterSpecificDrop('ngz1', 'j0c8', 600, false, 30)  // |cFF1EFF00Bear Fat Biscuit|r

        // Bear ('ngz2')
        call RegisterSpecificDrop('ngz2', 'I61B', 2000, false, 90)  // Bear Skin
        call RegisterSpecificDrop('ngz2', 'I6AB', 2000, false, 80)  // Big Bear Tooth
        call RegisterSpecificDrop('ngz2', 'j0a3', 1200, false, 60)  // |c001EFF00Bear Grease|r
        call RegisterSpecificDrop('ngz2', 'I61Q', 1000, false, 100)  // Raw Bear Meat
        call RegisterSpecificDrop('ngz2', 'j0c8', 600, false, 30)  // |cFF1EFF00Bear Fat Biscuit|r

        // Mother Bear ('ngz4')
        call RegisterSpecificDrop('ngz4', 'I6AB', 10000, true, 100)  // Big Bear Tooth
        call RegisterSpecificDrop('ngz4', 'I61B', 2000, false, 90)  // Bear Skin
        call RegisterSpecificDrop('ngz4', 'j0a3', 1200, false, 60)  // |c001EFF00Bear Grease|r
        call RegisterSpecificDrop('ngz4', 'I61Q', 1000, false, 100)  // Raw Bear Meat
        call RegisterSpecificDrop('ngz4', 'j0c8', 600, false, 30)  // |cFF1EFF00Bear Fat Biscuit|r

        // Ferocious Bear ('ngza')
        call RegisterSpecificDrop('ngza', 'I6AB', 5000, false, 100)  // Big Bear Tooth
        call RegisterSpecificDrop('ngza', 'I61B', 2000, false, 90)  // Bear Skin
        call RegisterSpecificDrop('ngza', 'j0a3', 1200, false, 60)  // |c001EFF00Bear Grease|r
        call RegisterSpecificDrop('ngza', 'I61Q', 1000, false, 100)  // Raw Bear Meat
        call RegisterSpecificDrop('ngza', 'j0c8', 600, false, 30)  // |cFF1EFF00Bear Fat Biscuit|r

        // npig ('npig')
        call RegisterSpecificDrop('npig', 'j0a1', 1800, false, 70)  // |c009D9D9DCracked Boar Tusk|r
        call RegisterSpecificDrop('npig', 'I61C', 1500, false, 80)  // Boar Skin
        call RegisterSpecificDrop('npig', 'I620', 1000, false, 100)  // Raw Boar Meat

        // Wolfy ('o600')
        call RegisterSpecificDrop('o600', 'I6AR', 1667, false, 90)  // Wolf Jawbone
        call RegisterSpecificDrop('o600', 'I61F', 1667, false, 90)  // Wolf Skin
        call RegisterSpecificDrop('o600', 'j0a0', 1200, false, 70)  // |c009D9D9DFrayed Wolf Pelt|r
        call RegisterSpecificDrop('o600', 'I61O', 1000, false, 100)  // Raw Wolf Meat
        call RegisterSpecificDrop('o600', 'j0c6', 600, false, 30)  // |cFF1EFF00Smoked Wolf Jerky|r

        // Wolfy ('o601')
        call RegisterSpecificDrop('o601', 'I6AR', 1667, false, 90)  // Wolf Jawbone
        call RegisterSpecificDrop('o601', 'I61F', 1667, false, 90)  // Wolf Skin
        call RegisterSpecificDrop('o601', 'j0a0', 1200, false, 70)  // |c009D9D9DFrayed Wolf Pelt|r
        call RegisterSpecificDrop('o601', 'I61O', 1000, false, 100)  // Raw Wolf Meat
        call RegisterSpecificDrop('o601', 'j0c6', 600, false, 30)  // |cFF1EFF00Smoked Wolf Jerky|r

        // Wolfy ('o602')
        call RegisterSpecificDrop('o602', 'I6AR', 1667, false, 90)  // Wolf Jawbone
        call RegisterSpecificDrop('o602', 'I61F', 1667, false, 90)  // Wolf Skin
        call RegisterSpecificDrop('o602', 'j0a0', 1200, false, 70)  // |c009D9D9DFrayed Wolf Pelt|r
        call RegisterSpecificDrop('o602', 'I61O', 1000, false, 100)  // Raw Wolf Meat
        call RegisterSpecificDrop('o602', 'j0c6', 600, false, 30)  // |cFF1EFF00Smoked Wolf Jerky|r

        // Ghost Wolf ('O61Y')
        call RegisterSpecificDrop('O61Y', 'I61F', 1667, false, 90)  // Wolf Skin
        call RegisterSpecificDrop('O61Y', 'I6AR', 1667, false, 90)  // Wolf Jawbone
        call RegisterSpecificDrop('O61Y', 'j0a0', 1200, false, 70)  // |c009D9D9DFrayed Wolf Pelt|r
        call RegisterSpecificDrop('O61Y', 'I61O', 1000, false, 100)  // Raw Wolf Meat
        call RegisterSpecificDrop('O61Y', 'j0c6', 600, false, 30)  // |cFF1EFF00Smoked Wolf Jerky|r

        // Ghost Wolf ('O61Z')
        call RegisterSpecificDrop('O61Z', 'I61F', 1667, false, 90)  // Wolf Skin
        call RegisterSpecificDrop('O61Z', 'I6AR', 1667, false, 90)  // Wolf Jawbone
        call RegisterSpecificDrop('O61Z', 'j0a0', 1200, false, 70)  // |c009D9D9DFrayed Wolf Pelt|r
        call RegisterSpecificDrop('O61Z', 'I61O', 1000, false, 100)  // Raw Wolf Meat
        call RegisterSpecificDrop('O61Z', 'j0c6', 600, false, 30)  // |cFF1EFF00Smoked Wolf Jerky|r

        // Ghost Wolf ('o624')
        call RegisterSpecificDrop('o624', 'I6AR', 1667, false, 90)  // Wolf Jawbone
        call RegisterSpecificDrop('o624', 'I61F', 1667, false, 90)  // Wolf Skin
        call RegisterSpecificDrop('o624', 'j0a0', 1200, false, 70)  // |c009D9D9DFrayed Wolf Pelt|r
        call RegisterSpecificDrop('o624', 'I61O', 1000, false, 100)  // Raw Wolf Meat
        call RegisterSpecificDrop('o624', 'j0c6', 600, false, 30)  // |cFF1EFF00Smoked Wolf Jerky|r

        // Undead Dragon XXX ('u001')
        call RegisterSpecificDrop('u001', 'I00S', 4000, false, 95)  // Whelp Scale
        call RegisterSpecificDrop('u001', 'I00W', 1667, false, 70)  // Ruined Dragonhide
        call RegisterSpecificDrop('u001', 'I00V', 1667, false, 70)  // Small Flame Sac
        call RegisterSpecificDrop('u001', 'I00X', 1667, false, 80)  // Sharp Claw
        call RegisterSpecificDrop('u001', 'j0b6', 1200, false, 60)  // |c001EFF00Charred Whelp Horn|r
        call RegisterSpecificDrop('u001', 'j0b7', 800, false, 35)  // |c000070DDEmber-Warmed Scale|r

        // Gollum ('u002')
        call RegisterSpecificDrop('u002', 'j1d1', 2500, false, 100)  // |c000070DDIronbound Greaves|r

        // Skeleton ('u007')
        call RegisterSpecificDrop('u007', 'I66P', 2000, false, 100)  // Rotten Part
        call RegisterSpecificDrop('u007', 'j0b8', 1200, false, 65)  // |c009D9D9DGrave Moss|r
        call RegisterSpecificDrop('u007', 'j0b9', 1200, false, 65)  // |c009D9D9DRotten Rib|r
        call RegisterSpecificDrop('u007', 'j1a3', 300, false, 15)  // |c009D9D9DMistwoven Wraps|r

        // Skeleton ('u008')
        call RegisterSpecificDrop('u008', 'I66P', 2000, false, 100)  // Rotten Part
        call RegisterSpecificDrop('u008', 'j0b8', 1200, false, 65)  // |c009D9D9DGrave Moss|r
        call RegisterSpecificDrop('u008', 'j0b9', 1200, false, 65)  // |c009D9D9DRotten Rib|r
        call RegisterSpecificDrop('u008', 'j1a3', 300, false, 15)  // |c009D9D9DMistwoven Wraps|r

        // Skeleton ('u009')
        call RegisterSpecificDrop('u009', 'I66P', 2000, false, 100)  // Rotten Part
        call RegisterSpecificDrop('u009', 'j0b8', 1200, false, 65)  // |c009D9D9DGrave Moss|r
        call RegisterSpecificDrop('u009', 'j0b9', 1200, false, 65)  // |c009D9D9DRotten Rib|r
        call RegisterSpecificDrop('u009', 'j1a3', 300, false, 15)  // |c009D9D9DMistwoven Wraps|r

        // Skeleton ('u603')
        call RegisterSpecificDrop('u603', 'I66P', 2000, false, 100)  // Rotten Part
        call RegisterSpecificDrop('u603', 'j0b8', 1200, false, 65)  // |c009D9D9DGrave Moss|r
        call RegisterSpecificDrop('u603', 'j0b9', 1200, false, 65)  // |c009D9D9DRotten Rib|r
        call RegisterSpecificDrop('u603', 'j1a3', 300, false, 15)  // |c009D9D9DMistwoven Wraps|r

        // Skeleton Mage ('u604')
        call RegisterSpecificDrop('u604', 'I66P', 2000, false, 100)  // Rotten Part
        call RegisterSpecificDrop('u604', 'j0b8', 1200, false, 65)  // |c009D9D9DGrave Moss|r
        call RegisterSpecificDrop('u604', 'j0b9', 1200, false, 65)  // |c009D9D9DRotten Rib|r
        call RegisterSpecificDrop('u604', 'j1a3', 300, false, 15)  // |c009D9D9DMistwoven Wraps|r

    endfunction

    private function Init takes nothing returns nothing
        // Specific drop registration delayed to allow ItemLootSystem to initialize
        call TimerStart(CreateTimer(), 0.02, false, function RegisterAllSpecificDrops)
    endfunction

endlibrary
