//===========================================================================
// ItemLootDefinitionsDestructible.j
// Generated by WC3ItemManager - DO NOT EDIT MANUALLY
// Generated: 2026-07-29 14.22.42
//===========================================================================

library ItemLootDefinitionsDestructible initializer Init requires ItemLootDestructibles

    private function RegisterAllDestructibleDrops takes nothing returns nothing
        call DestroyTimer(GetExpiredTimer())

        // === DESTRUCTIBLE LEVELS (for Generic drops) ===
        // RegisterDestructibleLevel(destructibleTypeId, level)

        call RegisterDestructibleLevel('B60J', 1)  // Stash (Basic 1-5)
        call RegisterDestructibleLevel('B60K', 1)  // Stash (Metallic 1-5)
        call RegisterDestructibleLevel('B60L', 1)  // Stash (Basic 5-10)
        call RegisterDestructibleLevel('B60M', 1)  // Stash (Basic 10-15)
        call RegisterDestructibleLevel('B60N', 1)  // Stash (Basic 15-20)
        call RegisterDestructibleLevel('B60O', 1)  // Stash (Basic 20-25)
        call RegisterDestructibleLevel('B60P', 1)  // Stash (Basic 25-30)
        call RegisterDestructibleLevel('B60Q', 1)  // Stash (Tribal 1-5)
        call RegisterDestructibleLevel('B60R', 1)  // Stash (Basic2 1-5)
        call RegisterDestructibleLevel('B60S', 1)  // Stash (Ancient 1-5)
        call RegisterDestructibleLevel('B60T', 1)  // Stash (Basic2 5-10)
        call RegisterDestructibleLevel('B60U', 1)  // Stash (Basic2 10-15)
        call RegisterDestructibleLevel('B60V', 1)  // Stash (Basic2 15-20)
        call RegisterDestructibleLevel('B60W', 1)  // Stash (Basic2 20-25)
        call RegisterDestructibleLevel('B60X', 1)  // Stash (Basic2 25-30)
        call RegisterDestructibleLevel('B60Y', 1)  // Stash (Ancient 5-10)
        call RegisterDestructibleLevel('B60Z', 1)  // Stash (Ancient 10-15)
        call RegisterDestructibleLevel('B610', 1)  // Stash (Ancient 15-20)
        call RegisterDestructibleLevel('B611', 1)  // Stash (Ancient 20-25)
        call RegisterDestructibleLevel('B612', 1)  // Stash (Ancient 25-30)
        call RegisterDestructibleLevel('B614', 1)  // Stash (Tribal 10-15)
        call RegisterDestructibleLevel('B615', 1)  // Stash (Tribal 15-20)
        call RegisterDestructibleLevel('B616', 1)  // Stash (Tribal 20-25)
        call RegisterDestructibleLevel('B617', 1)  // Stash (Tribal 25-30)
        call RegisterDestructibleLevel('B618', 1)  // Stash (Metallic 5-10)
        call RegisterDestructibleLevel('B619', 1)  // Stash (Metallic 10-15)
        call RegisterDestructibleLevel('B61A', 1)  // Stash (Metallic 15-20)
        call RegisterDestructibleLevel('B61B', 1)  // Stash (Metallic 20-25)
        call RegisterDestructibleLevel('B61C', 1)  // Stash (Metallic 25-30)
        call RegisterDestructibleLevel('B61D', 1)  // Stash (Quest)
        call RegisterDestructibleLevel('B02A', 10)  // B02A (Gnoll Hideout)
        call RegisterDestructibleLevel('B029', 15)  // B029 (Crypt)
        call RegisterDestructibleLevel('B02B', 15)  // B02B (Boom Brothers Mine)

        // === DESTRUCTIBLE LOOT TABLE SETTINGS ===
        // RegisterDestructibleTable(destructibleTypeId, dropChance, dropCountMin, dropCountMax)

        call RegisterDestructibleTable('B01P', 10000, 1, 1)  // Destructible Level 6-10
        call RegisterDestructibleTable('B01Q', 10000, 1, 1)  // Destructible Level 6-10
        call RegisterDestructibleTable('B01R', 10000, 1, 1)  // Destructible Level 6-10
        call RegisterDestructibleTable('B01S', 10000, 1, 1)  // Destructible Level 6-10
        call RegisterDestructibleTable('B01T', 10000, 1, 1)  // Destructible Level 6-10
        call RegisterDestructibleTable('B01U', 10000, 1, 1)  // Destructible Level 6-10
        call RegisterDestructibleTable('B01V', 10000, 1, 1)  // Destructible Level 6-10
        call RegisterDestructibleTable('B01W', 10000, 1, 1)  // Destructible Level 6-10
        call RegisterDestructibleTable('B01X', 10000, 1, 1)  // Destructible Level 6-10
        call RegisterDestructibleTable('B01Y', 10000, 1, 1)  // Destructible Level 6-10
        call RegisterDestructibleTable('B01Z', 10000, 1, 1)  // Destructible Level 6-10
        call RegisterDestructibleTable('B020', 10000, 1, 1)  // Destructible Level 6-10
        call RegisterDestructibleTable('B021', 10000, 1, 1)  // Destructible Level 6-10
        call RegisterDestructibleTable('B022', 10000, 1, 1)  // Destructible Level 6-10
        call RegisterDestructibleTable('B023', 10000, 1, 1)  // Destructible Level 6-10
        call RegisterDestructibleTable('B024', 10000, 1, 1)  // Destructible Level 6-10
        call RegisterDestructibleTable('B025', 10000, 1, 1)  // Destructible Level 6-10
        call RegisterDestructibleTable('B026', 10000, 1, 1)  // Destructible Level 6-10
        call RegisterDestructibleTable('B027', 10000, 1, 1)  // Destructible Level 6-10
        call RegisterDestructibleTable('B028', 10000, 1, 1)  // Destructible Level 6-10
        call RegisterDestructibleTable('LTbr', 10000, 1, 1)  // Destructible Level 1-5
        call RegisterDestructibleTable('LTbs', 10000, 1, 1)  // Destructible Level 1-5
        call RegisterDestructibleTable('LTbx', 10000, 1, 1)  // Destructible Level 1-5
        call RegisterDestructibleTable('LTcr', 10000, 1, 1)  // Destructible Level 1-5

        // === DESTRUCTIBLE SPECIFIC DROPS ===
        // RegisterDestructibleDropEx(destructibleTypeId, itemTypeId, dropChance, isGuaranteed, weight, quantityMin, quantityMax)

        // B01P (Level 6-10) -> loot table 'Destructible Level 6-10'
        call RegisterDestructibleDropEx('B01P', 'I60R', 9900, false, 100, 1, 1)  // |CFFFF8C00Boots of Arenamaster|r
        call RegisterDestructibleDropEx('B01P', 'shea', 9900, false, 100, 1, 1)  // Unknown Item (shea)
        call RegisterDestructibleDropEx('B01P', 'I66Q', 9900, false, 100, 1, 1)  // Spider Ichor
        call RegisterDestructibleDropEx('B01P', 'I605', 9900, false, 100, 1, 1)  // Hammer of Blood
        call RegisterDestructibleDropEx('B01P', 'pres', 9900, false, 100, 1, 1)  // Restoration Potion
        call RegisterDestructibleDropEx('B01P', 'I00F', 9900, false, 100, 1, 1)  // Barrel of Explosives
        call RegisterDestructibleDropEx('B01P', 'spro', 9900, false, 100, 1, 1)  // Unknown Item (spro)
        call RegisterDestructibleDropEx('B01P', 'I60K', 9900, false, 100, 1, 1)  // Pile Of Wood
        call RegisterDestructibleDropEx('B01P', 'I6BI', 9900, false, 100, 1, 1)  // Scroll of Greater Healing
        call RegisterDestructibleDropEx('B01P', 'rej3', 9900, false, 100, 1, 1)  // Unknown Item (rej3)
        call RegisterDestructibleDropEx('B01P', 'rej1', 9900, false, 100, 1, 1)  // Minor Replenishment Potion (old)
        call RegisterDestructibleDropEx('B01P', 'I00Q', 9900, false, 100, 1, 1)  // Raptor Egg

        // B01Q (Level 11-15) -> loot table 'Destructible Level 6-10'
        call RegisterDestructibleDropEx('B01Q', 'I60R', 9900, false, 100, 1, 1)  // |CFFFF8C00Boots of Arenamaster|r
        call RegisterDestructibleDropEx('B01Q', 'shea', 9900, false, 100, 1, 1)  // Unknown Item (shea)
        call RegisterDestructibleDropEx('B01Q', 'I66Q', 9900, false, 100, 1, 1)  // Spider Ichor
        call RegisterDestructibleDropEx('B01Q', 'I605', 9900, false, 100, 1, 1)  // Hammer of Blood
        call RegisterDestructibleDropEx('B01Q', 'pres', 9900, false, 100, 1, 1)  // Restoration Potion
        call RegisterDestructibleDropEx('B01Q', 'I00F', 9900, false, 100, 1, 1)  // Barrel of Explosives
        call RegisterDestructibleDropEx('B01Q', 'spro', 9900, false, 100, 1, 1)  // Unknown Item (spro)
        call RegisterDestructibleDropEx('B01Q', 'I60K', 9900, false, 100, 1, 1)  // Pile Of Wood
        call RegisterDestructibleDropEx('B01Q', 'I6BI', 9900, false, 100, 1, 1)  // Scroll of Greater Healing
        call RegisterDestructibleDropEx('B01Q', 'rej3', 9900, false, 100, 1, 1)  // Unknown Item (rej3)
        call RegisterDestructibleDropEx('B01Q', 'rej1', 9900, false, 100, 1, 1)  // Minor Replenishment Potion (old)
        call RegisterDestructibleDropEx('B01Q', 'I00Q', 9900, false, 100, 1, 1)  // Raptor Egg

        // B01R (Level 16-20) -> loot table 'Destructible Level 6-10'
        call RegisterDestructibleDropEx('B01R', 'I60R', 9900, false, 100, 1, 1)  // |CFFFF8C00Boots of Arenamaster|r
        call RegisterDestructibleDropEx('B01R', 'shea', 9900, false, 100, 1, 1)  // Unknown Item (shea)
        call RegisterDestructibleDropEx('B01R', 'I66Q', 9900, false, 100, 1, 1)  // Spider Ichor
        call RegisterDestructibleDropEx('B01R', 'I605', 9900, false, 100, 1, 1)  // Hammer of Blood
        call RegisterDestructibleDropEx('B01R', 'pres', 9900, false, 100, 1, 1)  // Restoration Potion
        call RegisterDestructibleDropEx('B01R', 'I00F', 9900, false, 100, 1, 1)  // Barrel of Explosives
        call RegisterDestructibleDropEx('B01R', 'spro', 9900, false, 100, 1, 1)  // Unknown Item (spro)
        call RegisterDestructibleDropEx('B01R', 'I60K', 9900, false, 100, 1, 1)  // Pile Of Wood
        call RegisterDestructibleDropEx('B01R', 'I6BI', 9900, false, 100, 1, 1)  // Scroll of Greater Healing
        call RegisterDestructibleDropEx('B01R', 'rej3', 9900, false, 100, 1, 1)  // Unknown Item (rej3)
        call RegisterDestructibleDropEx('B01R', 'rej1', 9900, false, 100, 1, 1)  // Minor Replenishment Potion (old)
        call RegisterDestructibleDropEx('B01R', 'I00Q', 9900, false, 100, 1, 1)  // Raptor Egg

        // B01S (Level 21-25) -> loot table 'Destructible Level 6-10'
        call RegisterDestructibleDropEx('B01S', 'I60R', 9900, false, 100, 1, 1)  // |CFFFF8C00Boots of Arenamaster|r
        call RegisterDestructibleDropEx('B01S', 'shea', 9900, false, 100, 1, 1)  // Unknown Item (shea)
        call RegisterDestructibleDropEx('B01S', 'I66Q', 9900, false, 100, 1, 1)  // Spider Ichor
        call RegisterDestructibleDropEx('B01S', 'I605', 9900, false, 100, 1, 1)  // Hammer of Blood
        call RegisterDestructibleDropEx('B01S', 'pres', 9900, false, 100, 1, 1)  // Restoration Potion
        call RegisterDestructibleDropEx('B01S', 'I00F', 9900, false, 100, 1, 1)  // Barrel of Explosives
        call RegisterDestructibleDropEx('B01S', 'spro', 9900, false, 100, 1, 1)  // Unknown Item (spro)
        call RegisterDestructibleDropEx('B01S', 'I60K', 9900, false, 100, 1, 1)  // Pile Of Wood
        call RegisterDestructibleDropEx('B01S', 'I6BI', 9900, false, 100, 1, 1)  // Scroll of Greater Healing
        call RegisterDestructibleDropEx('B01S', 'rej3', 9900, false, 100, 1, 1)  // Unknown Item (rej3)
        call RegisterDestructibleDropEx('B01S', 'rej1', 9900, false, 100, 1, 1)  // Minor Replenishment Potion (old)
        call RegisterDestructibleDropEx('B01S', 'I00Q', 9900, false, 100, 1, 1)  // Raptor Egg

        // B01T (Level 26-30) -> loot table 'Destructible Level 6-10'
        call RegisterDestructibleDropEx('B01T', 'I60R', 9900, false, 100, 1, 1)  // |CFFFF8C00Boots of Arenamaster|r
        call RegisterDestructibleDropEx('B01T', 'shea', 9900, false, 100, 1, 1)  // Unknown Item (shea)
        call RegisterDestructibleDropEx('B01T', 'I66Q', 9900, false, 100, 1, 1)  // Spider Ichor
        call RegisterDestructibleDropEx('B01T', 'I605', 9900, false, 100, 1, 1)  // Hammer of Blood
        call RegisterDestructibleDropEx('B01T', 'pres', 9900, false, 100, 1, 1)  // Restoration Potion
        call RegisterDestructibleDropEx('B01T', 'I00F', 9900, false, 100, 1, 1)  // Barrel of Explosives
        call RegisterDestructibleDropEx('B01T', 'spro', 9900, false, 100, 1, 1)  // Unknown Item (spro)
        call RegisterDestructibleDropEx('B01T', 'I60K', 9900, false, 100, 1, 1)  // Pile Of Wood
        call RegisterDestructibleDropEx('B01T', 'I6BI', 9900, false, 100, 1, 1)  // Scroll of Greater Healing
        call RegisterDestructibleDropEx('B01T', 'rej3', 9900, false, 100, 1, 1)  // Unknown Item (rej3)
        call RegisterDestructibleDropEx('B01T', 'rej1', 9900, false, 100, 1, 1)  // Minor Replenishment Potion (old)
        call RegisterDestructibleDropEx('B01T', 'I00Q', 9900, false, 100, 1, 1)  // Raptor Egg

        // B01U (Level 6-10) -> loot table 'Destructible Level 6-10'
        call RegisterDestructibleDropEx('B01U', 'I60R', 9900, false, 100, 1, 1)  // |CFFFF8C00Boots of Arenamaster|r
        call RegisterDestructibleDropEx('B01U', 'shea', 9900, false, 100, 1, 1)  // Unknown Item (shea)
        call RegisterDestructibleDropEx('B01U', 'I66Q', 9900, false, 100, 1, 1)  // Spider Ichor
        call RegisterDestructibleDropEx('B01U', 'I605', 9900, false, 100, 1, 1)  // Hammer of Blood
        call RegisterDestructibleDropEx('B01U', 'pres', 9900, false, 100, 1, 1)  // Restoration Potion
        call RegisterDestructibleDropEx('B01U', 'I00F', 9900, false, 100, 1, 1)  // Barrel of Explosives
        call RegisterDestructibleDropEx('B01U', 'spro', 9900, false, 100, 1, 1)  // Unknown Item (spro)
        call RegisterDestructibleDropEx('B01U', 'I60K', 9900, false, 100, 1, 1)  // Pile Of Wood
        call RegisterDestructibleDropEx('B01U', 'I6BI', 9900, false, 100, 1, 1)  // Scroll of Greater Healing
        call RegisterDestructibleDropEx('B01U', 'rej3', 9900, false, 100, 1, 1)  // Unknown Item (rej3)
        call RegisterDestructibleDropEx('B01U', 'rej1', 9900, false, 100, 1, 1)  // Minor Replenishment Potion (old)
        call RegisterDestructibleDropEx('B01U', 'I00Q', 9900, false, 100, 1, 1)  // Raptor Egg

        // B01V (Level 6-10) -> loot table 'Destructible Level 6-10'
        call RegisterDestructibleDropEx('B01V', 'I60R', 9900, false, 100, 1, 1)  // |CFFFF8C00Boots of Arenamaster|r
        call RegisterDestructibleDropEx('B01V', 'shea', 9900, false, 100, 1, 1)  // Unknown Item (shea)
        call RegisterDestructibleDropEx('B01V', 'I66Q', 9900, false, 100, 1, 1)  // Spider Ichor
        call RegisterDestructibleDropEx('B01V', 'I605', 9900, false, 100, 1, 1)  // Hammer of Blood
        call RegisterDestructibleDropEx('B01V', 'pres', 9900, false, 100, 1, 1)  // Restoration Potion
        call RegisterDestructibleDropEx('B01V', 'I00F', 9900, false, 100, 1, 1)  // Barrel of Explosives
        call RegisterDestructibleDropEx('B01V', 'spro', 9900, false, 100, 1, 1)  // Unknown Item (spro)
        call RegisterDestructibleDropEx('B01V', 'I60K', 9900, false, 100, 1, 1)  // Pile Of Wood
        call RegisterDestructibleDropEx('B01V', 'I6BI', 9900, false, 100, 1, 1)  // Scroll of Greater Healing
        call RegisterDestructibleDropEx('B01V', 'rej3', 9900, false, 100, 1, 1)  // Unknown Item (rej3)
        call RegisterDestructibleDropEx('B01V', 'rej1', 9900, false, 100, 1, 1)  // Minor Replenishment Potion (old)
        call RegisterDestructibleDropEx('B01V', 'I00Q', 9900, false, 100, 1, 1)  // Raptor Egg

        // B01W (Level 6-10) -> loot table 'Destructible Level 6-10'
        call RegisterDestructibleDropEx('B01W', 'I60R', 9900, false, 100, 1, 1)  // |CFFFF8C00Boots of Arenamaster|r
        call RegisterDestructibleDropEx('B01W', 'shea', 9900, false, 100, 1, 1)  // Unknown Item (shea)
        call RegisterDestructibleDropEx('B01W', 'I66Q', 9900, false, 100, 1, 1)  // Spider Ichor
        call RegisterDestructibleDropEx('B01W', 'I605', 9900, false, 100, 1, 1)  // Hammer of Blood
        call RegisterDestructibleDropEx('B01W', 'pres', 9900, false, 100, 1, 1)  // Restoration Potion
        call RegisterDestructibleDropEx('B01W', 'I00F', 9900, false, 100, 1, 1)  // Barrel of Explosives
        call RegisterDestructibleDropEx('B01W', 'spro', 9900, false, 100, 1, 1)  // Unknown Item (spro)
        call RegisterDestructibleDropEx('B01W', 'I60K', 9900, false, 100, 1, 1)  // Pile Of Wood
        call RegisterDestructibleDropEx('B01W', 'I6BI', 9900, false, 100, 1, 1)  // Scroll of Greater Healing
        call RegisterDestructibleDropEx('B01W', 'rej3', 9900, false, 100, 1, 1)  // Unknown Item (rej3)
        call RegisterDestructibleDropEx('B01W', 'rej1', 9900, false, 100, 1, 1)  // Minor Replenishment Potion (old)
        call RegisterDestructibleDropEx('B01W', 'I00Q', 9900, false, 100, 1, 1)  // Raptor Egg

        // B01X (Level 11-15) -> loot table 'Destructible Level 6-10'
        call RegisterDestructibleDropEx('B01X', 'I60R', 9900, false, 100, 1, 1)  // |CFFFF8C00Boots of Arenamaster|r
        call RegisterDestructibleDropEx('B01X', 'shea', 9900, false, 100, 1, 1)  // Unknown Item (shea)
        call RegisterDestructibleDropEx('B01X', 'I66Q', 9900, false, 100, 1, 1)  // Spider Ichor
        call RegisterDestructibleDropEx('B01X', 'I605', 9900, false, 100, 1, 1)  // Hammer of Blood
        call RegisterDestructibleDropEx('B01X', 'pres', 9900, false, 100, 1, 1)  // Restoration Potion
        call RegisterDestructibleDropEx('B01X', 'I00F', 9900, false, 100, 1, 1)  // Barrel of Explosives
        call RegisterDestructibleDropEx('B01X', 'spro', 9900, false, 100, 1, 1)  // Unknown Item (spro)
        call RegisterDestructibleDropEx('B01X', 'I60K', 9900, false, 100, 1, 1)  // Pile Of Wood
        call RegisterDestructibleDropEx('B01X', 'I6BI', 9900, false, 100, 1, 1)  // Scroll of Greater Healing
        call RegisterDestructibleDropEx('B01X', 'rej3', 9900, false, 100, 1, 1)  // Unknown Item (rej3)
        call RegisterDestructibleDropEx('B01X', 'rej1', 9900, false, 100, 1, 1)  // Minor Replenishment Potion (old)
        call RegisterDestructibleDropEx('B01X', 'I00Q', 9900, false, 100, 1, 1)  // Raptor Egg

        // B01Y (Level 11-15) -> loot table 'Destructible Level 6-10'
        call RegisterDestructibleDropEx('B01Y', 'I60R', 9900, false, 100, 1, 1)  // |CFFFF8C00Boots of Arenamaster|r
        call RegisterDestructibleDropEx('B01Y', 'shea', 9900, false, 100, 1, 1)  // Unknown Item (shea)
        call RegisterDestructibleDropEx('B01Y', 'I66Q', 9900, false, 100, 1, 1)  // Spider Ichor
        call RegisterDestructibleDropEx('B01Y', 'I605', 9900, false, 100, 1, 1)  // Hammer of Blood
        call RegisterDestructibleDropEx('B01Y', 'pres', 9900, false, 100, 1, 1)  // Restoration Potion
        call RegisterDestructibleDropEx('B01Y', 'I00F', 9900, false, 100, 1, 1)  // Barrel of Explosives
        call RegisterDestructibleDropEx('B01Y', 'spro', 9900, false, 100, 1, 1)  // Unknown Item (spro)
        call RegisterDestructibleDropEx('B01Y', 'I60K', 9900, false, 100, 1, 1)  // Pile Of Wood
        call RegisterDestructibleDropEx('B01Y', 'I6BI', 9900, false, 100, 1, 1)  // Scroll of Greater Healing
        call RegisterDestructibleDropEx('B01Y', 'rej3', 9900, false, 100, 1, 1)  // Unknown Item (rej3)
        call RegisterDestructibleDropEx('B01Y', 'rej1', 9900, false, 100, 1, 1)  // Minor Replenishment Potion (old)
        call RegisterDestructibleDropEx('B01Y', 'I00Q', 9900, false, 100, 1, 1)  // Raptor Egg

        // B01Z (Level 11-15) -> loot table 'Destructible Level 6-10'
        call RegisterDestructibleDropEx('B01Z', 'I60R', 9900, false, 100, 1, 1)  // |CFFFF8C00Boots of Arenamaster|r
        call RegisterDestructibleDropEx('B01Z', 'shea', 9900, false, 100, 1, 1)  // Unknown Item (shea)
        call RegisterDestructibleDropEx('B01Z', 'I66Q', 9900, false, 100, 1, 1)  // Spider Ichor
        call RegisterDestructibleDropEx('B01Z', 'I605', 9900, false, 100, 1, 1)  // Hammer of Blood
        call RegisterDestructibleDropEx('B01Z', 'pres', 9900, false, 100, 1, 1)  // Restoration Potion
        call RegisterDestructibleDropEx('B01Z', 'I00F', 9900, false, 100, 1, 1)  // Barrel of Explosives
        call RegisterDestructibleDropEx('B01Z', 'spro', 9900, false, 100, 1, 1)  // Unknown Item (spro)
        call RegisterDestructibleDropEx('B01Z', 'I60K', 9900, false, 100, 1, 1)  // Pile Of Wood
        call RegisterDestructibleDropEx('B01Z', 'I6BI', 9900, false, 100, 1, 1)  // Scroll of Greater Healing
        call RegisterDestructibleDropEx('B01Z', 'rej3', 9900, false, 100, 1, 1)  // Unknown Item (rej3)
        call RegisterDestructibleDropEx('B01Z', 'rej1', 9900, false, 100, 1, 1)  // Minor Replenishment Potion (old)
        call RegisterDestructibleDropEx('B01Z', 'I00Q', 9900, false, 100, 1, 1)  // Raptor Egg

        // B020 (Level 16-20) -> loot table 'Destructible Level 6-10'
        call RegisterDestructibleDropEx('B020', 'I60R', 9900, false, 100, 1, 1)  // |CFFFF8C00Boots of Arenamaster|r
        call RegisterDestructibleDropEx('B020', 'shea', 9900, false, 100, 1, 1)  // Unknown Item (shea)
        call RegisterDestructibleDropEx('B020', 'I66Q', 9900, false, 100, 1, 1)  // Spider Ichor
        call RegisterDestructibleDropEx('B020', 'I605', 9900, false, 100, 1, 1)  // Hammer of Blood
        call RegisterDestructibleDropEx('B020', 'pres', 9900, false, 100, 1, 1)  // Restoration Potion
        call RegisterDestructibleDropEx('B020', 'I00F', 9900, false, 100, 1, 1)  // Barrel of Explosives
        call RegisterDestructibleDropEx('B020', 'spro', 9900, false, 100, 1, 1)  // Unknown Item (spro)
        call RegisterDestructibleDropEx('B020', 'I60K', 9900, false, 100, 1, 1)  // Pile Of Wood
        call RegisterDestructibleDropEx('B020', 'I6BI', 9900, false, 100, 1, 1)  // Scroll of Greater Healing
        call RegisterDestructibleDropEx('B020', 'rej3', 9900, false, 100, 1, 1)  // Unknown Item (rej3)
        call RegisterDestructibleDropEx('B020', 'rej1', 9900, false, 100, 1, 1)  // Minor Replenishment Potion (old)
        call RegisterDestructibleDropEx('B020', 'I00Q', 9900, false, 100, 1, 1)  // Raptor Egg

        // B021 (Level 16-20) -> loot table 'Destructible Level 6-10'
        call RegisterDestructibleDropEx('B021', 'I60R', 9900, false, 100, 1, 1)  // |CFFFF8C00Boots of Arenamaster|r
        call RegisterDestructibleDropEx('B021', 'shea', 9900, false, 100, 1, 1)  // Unknown Item (shea)
        call RegisterDestructibleDropEx('B021', 'I66Q', 9900, false, 100, 1, 1)  // Spider Ichor
        call RegisterDestructibleDropEx('B021', 'I605', 9900, false, 100, 1, 1)  // Hammer of Blood
        call RegisterDestructibleDropEx('B021', 'pres', 9900, false, 100, 1, 1)  // Restoration Potion
        call RegisterDestructibleDropEx('B021', 'I00F', 9900, false, 100, 1, 1)  // Barrel of Explosives
        call RegisterDestructibleDropEx('B021', 'spro', 9900, false, 100, 1, 1)  // Unknown Item (spro)
        call RegisterDestructibleDropEx('B021', 'I60K', 9900, false, 100, 1, 1)  // Pile Of Wood
        call RegisterDestructibleDropEx('B021', 'I6BI', 9900, false, 100, 1, 1)  // Scroll of Greater Healing
        call RegisterDestructibleDropEx('B021', 'rej3', 9900, false, 100, 1, 1)  // Unknown Item (rej3)
        call RegisterDestructibleDropEx('B021', 'rej1', 9900, false, 100, 1, 1)  // Minor Replenishment Potion (old)
        call RegisterDestructibleDropEx('B021', 'I00Q', 9900, false, 100, 1, 1)  // Raptor Egg

        // B022 (Level 16-20) -> loot table 'Destructible Level 6-10'
        call RegisterDestructibleDropEx('B022', 'I60R', 9900, false, 100, 1, 1)  // |CFFFF8C00Boots of Arenamaster|r
        call RegisterDestructibleDropEx('B022', 'shea', 9900, false, 100, 1, 1)  // Unknown Item (shea)
        call RegisterDestructibleDropEx('B022', 'I66Q', 9900, false, 100, 1, 1)  // Spider Ichor
        call RegisterDestructibleDropEx('B022', 'I605', 9900, false, 100, 1, 1)  // Hammer of Blood
        call RegisterDestructibleDropEx('B022', 'pres', 9900, false, 100, 1, 1)  // Restoration Potion
        call RegisterDestructibleDropEx('B022', 'I00F', 9900, false, 100, 1, 1)  // Barrel of Explosives
        call RegisterDestructibleDropEx('B022', 'spro', 9900, false, 100, 1, 1)  // Unknown Item (spro)
        call RegisterDestructibleDropEx('B022', 'I60K', 9900, false, 100, 1, 1)  // Pile Of Wood
        call RegisterDestructibleDropEx('B022', 'I6BI', 9900, false, 100, 1, 1)  // Scroll of Greater Healing
        call RegisterDestructibleDropEx('B022', 'rej3', 9900, false, 100, 1, 1)  // Unknown Item (rej3)
        call RegisterDestructibleDropEx('B022', 'rej1', 9900, false, 100, 1, 1)  // Minor Replenishment Potion (old)
        call RegisterDestructibleDropEx('B022', 'I00Q', 9900, false, 100, 1, 1)  // Raptor Egg

        // B023 (Level 21-25) -> loot table 'Destructible Level 6-10'
        call RegisterDestructibleDropEx('B023', 'I60R', 9900, false, 100, 1, 1)  // |CFFFF8C00Boots of Arenamaster|r
        call RegisterDestructibleDropEx('B023', 'shea', 9900, false, 100, 1, 1)  // Unknown Item (shea)
        call RegisterDestructibleDropEx('B023', 'I66Q', 9900, false, 100, 1, 1)  // Spider Ichor
        call RegisterDestructibleDropEx('B023', 'I605', 9900, false, 100, 1, 1)  // Hammer of Blood
        call RegisterDestructibleDropEx('B023', 'pres', 9900, false, 100, 1, 1)  // Restoration Potion
        call RegisterDestructibleDropEx('B023', 'I00F', 9900, false, 100, 1, 1)  // Barrel of Explosives
        call RegisterDestructibleDropEx('B023', 'spro', 9900, false, 100, 1, 1)  // Unknown Item (spro)
        call RegisterDestructibleDropEx('B023', 'I60K', 9900, false, 100, 1, 1)  // Pile Of Wood
        call RegisterDestructibleDropEx('B023', 'I6BI', 9900, false, 100, 1, 1)  // Scroll of Greater Healing
        call RegisterDestructibleDropEx('B023', 'rej3', 9900, false, 100, 1, 1)  // Unknown Item (rej3)
        call RegisterDestructibleDropEx('B023', 'rej1', 9900, false, 100, 1, 1)  // Minor Replenishment Potion (old)
        call RegisterDestructibleDropEx('B023', 'I00Q', 9900, false, 100, 1, 1)  // Raptor Egg

        // B024 (Level 21-25) -> loot table 'Destructible Level 6-10'
        call RegisterDestructibleDropEx('B024', 'I60R', 9900, false, 100, 1, 1)  // |CFFFF8C00Boots of Arenamaster|r
        call RegisterDestructibleDropEx('B024', 'shea', 9900, false, 100, 1, 1)  // Unknown Item (shea)
        call RegisterDestructibleDropEx('B024', 'I66Q', 9900, false, 100, 1, 1)  // Spider Ichor
        call RegisterDestructibleDropEx('B024', 'I605', 9900, false, 100, 1, 1)  // Hammer of Blood
        call RegisterDestructibleDropEx('B024', 'pres', 9900, false, 100, 1, 1)  // Restoration Potion
        call RegisterDestructibleDropEx('B024', 'I00F', 9900, false, 100, 1, 1)  // Barrel of Explosives
        call RegisterDestructibleDropEx('B024', 'spro', 9900, false, 100, 1, 1)  // Unknown Item (spro)
        call RegisterDestructibleDropEx('B024', 'I60K', 9900, false, 100, 1, 1)  // Pile Of Wood
        call RegisterDestructibleDropEx('B024', 'I6BI', 9900, false, 100, 1, 1)  // Scroll of Greater Healing
        call RegisterDestructibleDropEx('B024', 'rej3', 9900, false, 100, 1, 1)  // Unknown Item (rej3)
        call RegisterDestructibleDropEx('B024', 'rej1', 9900, false, 100, 1, 1)  // Minor Replenishment Potion (old)
        call RegisterDestructibleDropEx('B024', 'I00Q', 9900, false, 100, 1, 1)  // Raptor Egg

        // B025 (Level 21-25) -> loot table 'Destructible Level 6-10'
        call RegisterDestructibleDropEx('B025', 'I60R', 9900, false, 100, 1, 1)  // |CFFFF8C00Boots of Arenamaster|r
        call RegisterDestructibleDropEx('B025', 'shea', 9900, false, 100, 1, 1)  // Unknown Item (shea)
        call RegisterDestructibleDropEx('B025', 'I66Q', 9900, false, 100, 1, 1)  // Spider Ichor
        call RegisterDestructibleDropEx('B025', 'I605', 9900, false, 100, 1, 1)  // Hammer of Blood
        call RegisterDestructibleDropEx('B025', 'pres', 9900, false, 100, 1, 1)  // Restoration Potion
        call RegisterDestructibleDropEx('B025', 'I00F', 9900, false, 100, 1, 1)  // Barrel of Explosives
        call RegisterDestructibleDropEx('B025', 'spro', 9900, false, 100, 1, 1)  // Unknown Item (spro)
        call RegisterDestructibleDropEx('B025', 'I60K', 9900, false, 100, 1, 1)  // Pile Of Wood
        call RegisterDestructibleDropEx('B025', 'I6BI', 9900, false, 100, 1, 1)  // Scroll of Greater Healing
        call RegisterDestructibleDropEx('B025', 'rej3', 9900, false, 100, 1, 1)  // Unknown Item (rej3)
        call RegisterDestructibleDropEx('B025', 'rej1', 9900, false, 100, 1, 1)  // Minor Replenishment Potion (old)
        call RegisterDestructibleDropEx('B025', 'I00Q', 9900, false, 100, 1, 1)  // Raptor Egg

        // B026 (Level 26-30) -> loot table 'Destructible Level 6-10'
        call RegisterDestructibleDropEx('B026', 'I60R', 9900, false, 100, 1, 1)  // |CFFFF8C00Boots of Arenamaster|r
        call RegisterDestructibleDropEx('B026', 'shea', 9900, false, 100, 1, 1)  // Unknown Item (shea)
        call RegisterDestructibleDropEx('B026', 'I66Q', 9900, false, 100, 1, 1)  // Spider Ichor
        call RegisterDestructibleDropEx('B026', 'I605', 9900, false, 100, 1, 1)  // Hammer of Blood
        call RegisterDestructibleDropEx('B026', 'pres', 9900, false, 100, 1, 1)  // Restoration Potion
        call RegisterDestructibleDropEx('B026', 'I00F', 9900, false, 100, 1, 1)  // Barrel of Explosives
        call RegisterDestructibleDropEx('B026', 'spro', 9900, false, 100, 1, 1)  // Unknown Item (spro)
        call RegisterDestructibleDropEx('B026', 'I60K', 9900, false, 100, 1, 1)  // Pile Of Wood
        call RegisterDestructibleDropEx('B026', 'I6BI', 9900, false, 100, 1, 1)  // Scroll of Greater Healing
        call RegisterDestructibleDropEx('B026', 'rej3', 9900, false, 100, 1, 1)  // Unknown Item (rej3)
        call RegisterDestructibleDropEx('B026', 'rej1', 9900, false, 100, 1, 1)  // Minor Replenishment Potion (old)
        call RegisterDestructibleDropEx('B026', 'I00Q', 9900, false, 100, 1, 1)  // Raptor Egg

        // B027 (Level 26-30) -> loot table 'Destructible Level 6-10'
        call RegisterDestructibleDropEx('B027', 'I60R', 9900, false, 100, 1, 1)  // |CFFFF8C00Boots of Arenamaster|r
        call RegisterDestructibleDropEx('B027', 'shea', 9900, false, 100, 1, 1)  // Unknown Item (shea)
        call RegisterDestructibleDropEx('B027', 'I66Q', 9900, false, 100, 1, 1)  // Spider Ichor
        call RegisterDestructibleDropEx('B027', 'I605', 9900, false, 100, 1, 1)  // Hammer of Blood
        call RegisterDestructibleDropEx('B027', 'pres', 9900, false, 100, 1, 1)  // Restoration Potion
        call RegisterDestructibleDropEx('B027', 'I00F', 9900, false, 100, 1, 1)  // Barrel of Explosives
        call RegisterDestructibleDropEx('B027', 'spro', 9900, false, 100, 1, 1)  // Unknown Item (spro)
        call RegisterDestructibleDropEx('B027', 'I60K', 9900, false, 100, 1, 1)  // Pile Of Wood
        call RegisterDestructibleDropEx('B027', 'I6BI', 9900, false, 100, 1, 1)  // Scroll of Greater Healing
        call RegisterDestructibleDropEx('B027', 'rej3', 9900, false, 100, 1, 1)  // Unknown Item (rej3)
        call RegisterDestructibleDropEx('B027', 'rej1', 9900, false, 100, 1, 1)  // Minor Replenishment Potion (old)
        call RegisterDestructibleDropEx('B027', 'I00Q', 9900, false, 100, 1, 1)  // Raptor Egg

        // B028 (Level 26-30) -> loot table 'Destructible Level 6-10'
        call RegisterDestructibleDropEx('B028', 'I60R', 9900, false, 100, 1, 1)  // |CFFFF8C00Boots of Arenamaster|r
        call RegisterDestructibleDropEx('B028', 'shea', 9900, false, 100, 1, 1)  // Unknown Item (shea)
        call RegisterDestructibleDropEx('B028', 'I66Q', 9900, false, 100, 1, 1)  // Spider Ichor
        call RegisterDestructibleDropEx('B028', 'I605', 9900, false, 100, 1, 1)  // Hammer of Blood
        call RegisterDestructibleDropEx('B028', 'pres', 9900, false, 100, 1, 1)  // Restoration Potion
        call RegisterDestructibleDropEx('B028', 'I00F', 9900, false, 100, 1, 1)  // Barrel of Explosives
        call RegisterDestructibleDropEx('B028', 'spro', 9900, false, 100, 1, 1)  // Unknown Item (spro)
        call RegisterDestructibleDropEx('B028', 'I60K', 9900, false, 100, 1, 1)  // Pile Of Wood
        call RegisterDestructibleDropEx('B028', 'I6BI', 9900, false, 100, 1, 1)  // Scroll of Greater Healing
        call RegisterDestructibleDropEx('B028', 'rej3', 9900, false, 100, 1, 1)  // Unknown Item (rej3)
        call RegisterDestructibleDropEx('B028', 'rej1', 9900, false, 100, 1, 1)  // Minor Replenishment Potion (old)
        call RegisterDestructibleDropEx('B028', 'I00Q', 9900, false, 100, 1, 1)  // Raptor Egg

        // LTbr (Level 1-5) -> loot table 'Destructible Level 1-5'
        call RegisterDestructibleDropEx('LTbr', 'olig', 10000, false, 100, 1, 1)  // Unknown Item (olig)
        call RegisterDestructibleDropEx('LTbr', 'ofir', 10000, false, 100, 1, 1)  // Unknown Item (ofir)
        call RegisterDestructibleDropEx('LTbr', 'hbth', 10000, false, 100, 1, 1)  // Unknown Item (hbth)
        call RegisterDestructibleDropEx('LTbr', 'rugt', 10000, false, 100, 1, 1)  // Unknown Item (rugt)
        call RegisterDestructibleDropEx('LTbr', 'rump', 10000, false, 100, 1, 1)  // Unknown Item (rump)
        call RegisterDestructibleDropEx('LTbr', 'gcel', 10000, false, 100, 1, 1)  // Unknown Item (gcel)
        call RegisterDestructibleDropEx('LTbr', 'plcl', 10000, false, 100, 1, 1)  // Unknown Item (plcl)
        call RegisterDestructibleDropEx('LTbr', 'I602', 10000, false, 100, 1, 1)  // Light Boots
        call RegisterDestructibleDropEx('LTbr', 'I60G', 10000, false, 100, 1, 1)  // Unknown Item (I60G)
        call RegisterDestructibleDropEx('LTbr', 'I60M', 10000, false, 100, 1, 1)  // Rusty Kitchen Knive
        call RegisterDestructibleDropEx('LTbr', 'I60P', 10000, false, 100, 1, 1)  // Worn Gloves
        call RegisterDestructibleDropEx('LTbr', 'I60V', 10000, false, 100, 1, 1)  // |CFFFF8C00Helm of Arenamaster|r
        call RegisterDestructibleDropEx('LTbr', 'I626', 10000, false, 100, 1, 1)  // Gloves of Strength
        call RegisterDestructibleDropEx('LTbr', 'I62A', 10000, false, 100, 1, 1)  // Helm of Strength
        call RegisterDestructibleDropEx('LTbr', 'I62E', 10000, false, 100, 1, 1)  // Axe of Strength
        call RegisterDestructibleDropEx('LTbr', 'I62F', 10000, false, 100, 1, 1)  // Staff of Strength
        call RegisterDestructibleDropEx('LTbr', 'I62I', 10000, false, 100, 1, 1)  // Belt of Intelligence
        call RegisterDestructibleDropEx('LTbr', 'I62M', 10000, false, 100, 1, 1)  // Necklace of Intelligence
        call RegisterDestructibleDropEx('LTbr', 'I62X', 10000, false, 100, 1, 1)  // Ironwood Protector
        call RegisterDestructibleDropEx('LTbr', 'I62Y', 10000, false, 100, 1, 1)  // Arcane Ward
        call RegisterDestructibleDropEx('LTbr', 'I62Z', 10000, false, 100, 1, 1)  // Dragonhide Shield
        call RegisterDestructibleDropEx('LTbr', 'I630', 10000, false, 100, 1, 1)  // Radiant Crest
        call RegisterDestructibleDropEx('LTbr', 'I634', 10000, false, 100, 1, 1)  // Frostbite Ward
        call RegisterDestructibleDropEx('LTbr', 'I63G', 10000, false, 100, 1, 1)  // Moonlit Rod
        call RegisterDestructibleDropEx('LTbr', 'I63H', 10000, false, 100, 1, 1)  // Inferno Scepter
        call RegisterDestructibleDropEx('LTbr', 'I63K', 10000, false, 100, 1, 1)  // Thunderfury Sword
        call RegisterDestructibleDropEx('LTbr', 'I63L', 10000, false, 100, 1, 1)  // Frostbite Axe
        call RegisterDestructibleDropEx('LTbr', 'I63T', 10000, false, 100, 1, 1)  // Soulreaper Halberd
        call RegisterDestructibleDropEx('LTbr', 'I63V', 10000, false, 100, 1, 1)  // Frostshard Greatsword
        call RegisterDestructibleDropEx('LTbr', 'I63X', 10000, false, 100, 1, 1)  // Celestial Crescent Blade
        call RegisterDestructibleDropEx('LTbr', 'I642', 10000, false, 100, 1, 1)  // Skullcrusher Maul
        call RegisterDestructibleDropEx('LTbr', 'I644', 10000, false, 100, 1, 1)  // Thunderhorn Warhammer
        call RegisterDestructibleDropEx('LTbr', 'I649', 10000, false, 100, 1, 1)  // Celestial Harmony Necklace
        call RegisterDestructibleDropEx('LTbr', 'I64B', 10000, false, 100, 1, 1)  // Venomweave Locket
        call RegisterDestructibleDropEx('LTbr', 'I64C', 10000, false, 100, 1, 1)  // Rune-etched Collar
        call RegisterDestructibleDropEx('LTbr', 'I64E', 10000, false, 100, 1, 1)  // Serpent's Coil Necklace
        call RegisterDestructibleDropEx('LTbr', 'I64G', 10000, false, 100, 1, 1)  // Thunderforged Band
        call RegisterDestructibleDropEx('LTbr', 'I64I', 10000, false, 100, 1, 1)  // Celestial Halo
        call RegisterDestructibleDropEx('LTbr', 'I64J', 10000, false, 100, 1, 1)  // Runebound Circlet
        call RegisterDestructibleDropEx('LTbr', 'I64M', 10000, false, 100, 1, 1)  // Bloodfire Signet
        call RegisterDestructibleDropEx('LTbr', 'I64O', 10000, false, 100, 1, 1)  // Ironheart Ring
        call RegisterDestructibleDropEx('LTbr', 'I64Q', 10000, false, 100, 1, 1)  // Thunderforged Breastplate
        call RegisterDestructibleDropEx('LTbr', 'I64V', 10000, false, 100, 1, 1)  // Frostbitten Plate
        call RegisterDestructibleDropEx('LTbr', 'I64X', 10000, false, 100, 1, 1)  // Obsidian Warplate
        call RegisterDestructibleDropEx('LTbr', 'I650', 10000, false, 100, 1, 1)  // Emberweave Robes
        call RegisterDestructibleDropEx('LTbr', 'I653', 10000, false, 100, 1, 1)  // Runebound Silk Tunic
        call RegisterDestructibleDropEx('LTbr', 'I659', 10000, false, 100, 1, 1)  // Cloak of Shadowsong
        call RegisterDestructibleDropEx('LTbr', 'I65R', 10000, false, 100, 1, 1)  // Hammer of the Ancients
        call RegisterDestructibleDropEx('LTbr', 'I65S', 10000, false, 100, 1, 1)  // Gleaming Plate Armor
        call RegisterDestructibleDropEx('LTbr', 'I65V', 10000, false, 100, 1, 1)  // Celestial Robes
        call RegisterDestructibleDropEx('LTbr', 'I665', 10000, false, 100, 1, 1)  // Dragonhide Cloak of the Serpent
        call RegisterDestructibleDropEx('LTbr', 'I669', 10000, false, 100, 1, 1)  // Tattered Leather Gloves
        call RegisterDestructibleDropEx('LTbr', 'I66A', 10000, false, 100, 1, 1)  // Tattered Leather Shoulderpads
        call RegisterDestructibleDropEx('LTbr', 'I66D', 10000, false, 100, 1, 1)  // Tattered Leather Belt
        call RegisterDestructibleDropEx('LTbr', 'I66I', 10000, false, 100, 1, 1)  // Sargoth's Ichor
        call RegisterDestructibleDropEx('LTbr', 'I68O', 10000, false, 100, 1, 1)  // Bronze Boots
        call RegisterDestructibleDropEx('LTbr', 'I68U', 10000, false, 100, 1, 1)  // Silvered Bronze Helmet
        call RegisterDestructibleDropEx('LTbr', 'I68V', 10000, false, 100, 1, 1)  // Silvered Bronze Breastplate
        call RegisterDestructibleDropEx('LTbr', 'I68W', 10000, false, 100, 1, 1)  // Iron Helmet
        call RegisterDestructibleDropEx('LTbr', 'I68Y', 10000, false, 100, 1, 1)  // Iron Breastplate
        call RegisterDestructibleDropEx('LTbr', 'I692', 10000, false, 100, 1, 1)  // Iron Leggings
        call RegisterDestructibleDropEx('LTbr', 'I69D', 10000, false, 100, 1, 1)  // Healing Rain
        call RegisterDestructibleDropEx('LTbr', 'I69I', 10000, false, 100, 1, 1)  // Fire Shock
        call RegisterDestructibleDropEx('LTbr', 'I69T', 10000, false, 100, 1, 1)  // Bloodlust
        call RegisterDestructibleDropEx('LTbr', 'I69U', 10000, false, 100, 1, 1)  // Ghost Wolf
        call RegisterDestructibleDropEx('LTbr', 'I6AC', 10000, false, 100, 1, 1)  // Frost Shock
        call RegisterDestructibleDropEx('LTbr', 'I6AD', 10000, false, 100, 1, 1)  // Nature Shock
        call RegisterDestructibleDropEx('LTbr', 'I6AF', 10000, false, 100, 1, 1)  // Rejuvenation
        call RegisterDestructibleDropEx('LTbr', 'I6AI', 10000, false, 100, 1, 1)  // Spiritmender
        call RegisterDestructibleDropEx('LTbr', 'I6AM', 10000, false, 100, 1, 1)  // Ancestral Ward
        call RegisterDestructibleDropEx('LTbr', 'I6AN', 10000, false, 100, 1, 1)  // Supply Crate
        call RegisterDestructibleDropEx('LTbr', 'I6CK', 10000, false, 100, 1, 1)  // Whirlwind
        call RegisterDestructibleDropEx('LTbr', 'I001', 10000, false, 100, 1, 1)  // Earth Crystal
        call RegisterDestructibleDropEx('LTbr', 'I004', 10000, false, 100, 1, 1)  // Wind Crystal
        call RegisterDestructibleDropEx('LTbr', 'I009', 10000, false, 100, 1, 1)  // Spirit Link
        call RegisterDestructibleDropEx('LTbr', 'I00B', 10000, false, 100, 1, 1)  // Wind Shear
        call RegisterDestructibleDropEx('LTbr', 'I00J', 10000, false, 100, 1, 1)  // The One Ring
        call RegisterDestructibleDropEx('LTbr', 'stwp', 10000, false, 100, 1, 1)  // Unknown Item (stwp)
        call RegisterDestructibleDropEx('LTbr', 'vamp', 10000, false, 100, 1, 1)  // Unknown Item (vamp)
        call RegisterDestructibleDropEx('LTbr', 'wneg', 10000, false, 100, 1, 1)  // Unknown Item (wneg)
        call RegisterDestructibleDropEx('LTbr', 'rej6', 10000, false, 100, 1, 1)  // Greater Scroll of Replenishment (old)
        call RegisterDestructibleDropEx('LTbr', 'I608', 10000, false, 100, 1, 1)  // Tome of God
        call RegisterDestructibleDropEx('LTbr', 'I60A', 10000, false, 100, 1, 1)  // Tome of Eternal Agility
        call RegisterDestructibleDropEx('LTbr', 'I60B', 10000, false, 100, 1, 1)  // Tome of Eternal Intelligence
        call RegisterDestructibleDropEx('LTbr', 'I611', 10000, false, 100, 1, 1)  // Camp Fire
        call RegisterDestructibleDropEx('LTbr', 'I624', 10000, false, 100, 1, 1)  // Jin'Zun Healing Ward
        call RegisterDestructibleDropEx('LTbr', 'I6C3', 10000, false, 100, 1, 1)  // Water Shield
        call RegisterDestructibleDropEx('LTbr', 'I00N', 10000, false, 100, 1, 1)  // Gutcleanser Elixir
        call RegisterDestructibleDropEx('LTbr', 'I6A3', 10000, false, 100, 1, 1)  // I6A3
        call RegisterDestructibleDropEx('LTbr', 'I6AO', 10000, false, 100, 1, 1)  // I6AO
        call RegisterDestructibleDropEx('LTbr', 'I69H', 10000, false, 100, 1, 1)  // I69H
        call RegisterDestructibleDropEx('LTbr', 'I69X', 10000, false, 100, 1, 1)  // I69X
        call RegisterDestructibleDropEx('LTbr', 'I69L', 10000, false, 100, 1, 1)  // I69L
        call RegisterDestructibleDropEx('LTbr', 'I00A', 10000, false, 100, 1, 1)  // I00A
        call RegisterDestructibleDropEx('LTbr', 'I69Q', 10000, false, 100, 1, 1)  // I69Q

        // LTbs (Level 1-5) -> loot table 'Destructible Level 1-5'
        call RegisterDestructibleDropEx('LTbs', 'olig', 10000, false, 100, 1, 1)  // Unknown Item (olig)
        call RegisterDestructibleDropEx('LTbs', 'ofir', 10000, false, 100, 1, 1)  // Unknown Item (ofir)
        call RegisterDestructibleDropEx('LTbs', 'hbth', 10000, false, 100, 1, 1)  // Unknown Item (hbth)
        call RegisterDestructibleDropEx('LTbs', 'rugt', 10000, false, 100, 1, 1)  // Unknown Item (rugt)
        call RegisterDestructibleDropEx('LTbs', 'rump', 10000, false, 100, 1, 1)  // Unknown Item (rump)
        call RegisterDestructibleDropEx('LTbs', 'gcel', 10000, false, 100, 1, 1)  // Unknown Item (gcel)
        call RegisterDestructibleDropEx('LTbs', 'plcl', 10000, false, 100, 1, 1)  // Unknown Item (plcl)
        call RegisterDestructibleDropEx('LTbs', 'I602', 10000, false, 100, 1, 1)  // Light Boots
        call RegisterDestructibleDropEx('LTbs', 'I60G', 10000, false, 100, 1, 1)  // Unknown Item (I60G)
        call RegisterDestructibleDropEx('LTbs', 'I60M', 10000, false, 100, 1, 1)  // Rusty Kitchen Knive
        call RegisterDestructibleDropEx('LTbs', 'I60P', 10000, false, 100, 1, 1)  // Worn Gloves
        call RegisterDestructibleDropEx('LTbs', 'I60V', 10000, false, 100, 1, 1)  // |CFFFF8C00Helm of Arenamaster|r
        call RegisterDestructibleDropEx('LTbs', 'I626', 10000, false, 100, 1, 1)  // Gloves of Strength
        call RegisterDestructibleDropEx('LTbs', 'I62A', 10000, false, 100, 1, 1)  // Helm of Strength
        call RegisterDestructibleDropEx('LTbs', 'I62E', 10000, false, 100, 1, 1)  // Axe of Strength
        call RegisterDestructibleDropEx('LTbs', 'I62F', 10000, false, 100, 1, 1)  // Staff of Strength
        call RegisterDestructibleDropEx('LTbs', 'I62I', 10000, false, 100, 1, 1)  // Belt of Intelligence
        call RegisterDestructibleDropEx('LTbs', 'I62M', 10000, false, 100, 1, 1)  // Necklace of Intelligence
        call RegisterDestructibleDropEx('LTbs', 'I62X', 10000, false, 100, 1, 1)  // Ironwood Protector
        call RegisterDestructibleDropEx('LTbs', 'I62Y', 10000, false, 100, 1, 1)  // Arcane Ward
        call RegisterDestructibleDropEx('LTbs', 'I62Z', 10000, false, 100, 1, 1)  // Dragonhide Shield
        call RegisterDestructibleDropEx('LTbs', 'I630', 10000, false, 100, 1, 1)  // Radiant Crest
        call RegisterDestructibleDropEx('LTbs', 'I634', 10000, false, 100, 1, 1)  // Frostbite Ward
        call RegisterDestructibleDropEx('LTbs', 'I63G', 10000, false, 100, 1, 1)  // Moonlit Rod
        call RegisterDestructibleDropEx('LTbs', 'I63H', 10000, false, 100, 1, 1)  // Inferno Scepter
        call RegisterDestructibleDropEx('LTbs', 'I63K', 10000, false, 100, 1, 1)  // Thunderfury Sword
        call RegisterDestructibleDropEx('LTbs', 'I63L', 10000, false, 100, 1, 1)  // Frostbite Axe
        call RegisterDestructibleDropEx('LTbs', 'I63T', 10000, false, 100, 1, 1)  // Soulreaper Halberd
        call RegisterDestructibleDropEx('LTbs', 'I63V', 10000, false, 100, 1, 1)  // Frostshard Greatsword
        call RegisterDestructibleDropEx('LTbs', 'I63X', 10000, false, 100, 1, 1)  // Celestial Crescent Blade
        call RegisterDestructibleDropEx('LTbs', 'I642', 10000, false, 100, 1, 1)  // Skullcrusher Maul
        call RegisterDestructibleDropEx('LTbs', 'I644', 10000, false, 100, 1, 1)  // Thunderhorn Warhammer
        call RegisterDestructibleDropEx('LTbs', 'I649', 10000, false, 100, 1, 1)  // Celestial Harmony Necklace
        call RegisterDestructibleDropEx('LTbs', 'I64B', 10000, false, 100, 1, 1)  // Venomweave Locket
        call RegisterDestructibleDropEx('LTbs', 'I64C', 10000, false, 100, 1, 1)  // Rune-etched Collar
        call RegisterDestructibleDropEx('LTbs', 'I64E', 10000, false, 100, 1, 1)  // Serpent's Coil Necklace
        call RegisterDestructibleDropEx('LTbs', 'I64G', 10000, false, 100, 1, 1)  // Thunderforged Band
        call RegisterDestructibleDropEx('LTbs', 'I64I', 10000, false, 100, 1, 1)  // Celestial Halo
        call RegisterDestructibleDropEx('LTbs', 'I64J', 10000, false, 100, 1, 1)  // Runebound Circlet
        call RegisterDestructibleDropEx('LTbs', 'I64M', 10000, false, 100, 1, 1)  // Bloodfire Signet
        call RegisterDestructibleDropEx('LTbs', 'I64O', 10000, false, 100, 1, 1)  // Ironheart Ring
        call RegisterDestructibleDropEx('LTbs', 'I64Q', 10000, false, 100, 1, 1)  // Thunderforged Breastplate
        call RegisterDestructibleDropEx('LTbs', 'I64V', 10000, false, 100, 1, 1)  // Frostbitten Plate
        call RegisterDestructibleDropEx('LTbs', 'I64X', 10000, false, 100, 1, 1)  // Obsidian Warplate
        call RegisterDestructibleDropEx('LTbs', 'I650', 10000, false, 100, 1, 1)  // Emberweave Robes
        call RegisterDestructibleDropEx('LTbs', 'I653', 10000, false, 100, 1, 1)  // Runebound Silk Tunic
        call RegisterDestructibleDropEx('LTbs', 'I659', 10000, false, 100, 1, 1)  // Cloak of Shadowsong
        call RegisterDestructibleDropEx('LTbs', 'I65R', 10000, false, 100, 1, 1)  // Hammer of the Ancients
        call RegisterDestructibleDropEx('LTbs', 'I65S', 10000, false, 100, 1, 1)  // Gleaming Plate Armor
        call RegisterDestructibleDropEx('LTbs', 'I65V', 10000, false, 100, 1, 1)  // Celestial Robes
        call RegisterDestructibleDropEx('LTbs', 'I665', 10000, false, 100, 1, 1)  // Dragonhide Cloak of the Serpent
        call RegisterDestructibleDropEx('LTbs', 'I669', 10000, false, 100, 1, 1)  // Tattered Leather Gloves
        call RegisterDestructibleDropEx('LTbs', 'I66A', 10000, false, 100, 1, 1)  // Tattered Leather Shoulderpads
        call RegisterDestructibleDropEx('LTbs', 'I66D', 10000, false, 100, 1, 1)  // Tattered Leather Belt
        call RegisterDestructibleDropEx('LTbs', 'I66I', 10000, false, 100, 1, 1)  // Sargoth's Ichor
        call RegisterDestructibleDropEx('LTbs', 'I68O', 10000, false, 100, 1, 1)  // Bronze Boots
        call RegisterDestructibleDropEx('LTbs', 'I68U', 10000, false, 100, 1, 1)  // Silvered Bronze Helmet
        call RegisterDestructibleDropEx('LTbs', 'I68V', 10000, false, 100, 1, 1)  // Silvered Bronze Breastplate
        call RegisterDestructibleDropEx('LTbs', 'I68W', 10000, false, 100, 1, 1)  // Iron Helmet
        call RegisterDestructibleDropEx('LTbs', 'I68Y', 10000, false, 100, 1, 1)  // Iron Breastplate
        call RegisterDestructibleDropEx('LTbs', 'I692', 10000, false, 100, 1, 1)  // Iron Leggings
        call RegisterDestructibleDropEx('LTbs', 'I69D', 10000, false, 100, 1, 1)  // Healing Rain
        call RegisterDestructibleDropEx('LTbs', 'I69I', 10000, false, 100, 1, 1)  // Fire Shock
        call RegisterDestructibleDropEx('LTbs', 'I69T', 10000, false, 100, 1, 1)  // Bloodlust
        call RegisterDestructibleDropEx('LTbs', 'I69U', 10000, false, 100, 1, 1)  // Ghost Wolf
        call RegisterDestructibleDropEx('LTbs', 'I6AC', 10000, false, 100, 1, 1)  // Frost Shock
        call RegisterDestructibleDropEx('LTbs', 'I6AD', 10000, false, 100, 1, 1)  // Nature Shock
        call RegisterDestructibleDropEx('LTbs', 'I6AF', 10000, false, 100, 1, 1)  // Rejuvenation
        call RegisterDestructibleDropEx('LTbs', 'I6AI', 10000, false, 100, 1, 1)  // Spiritmender
        call RegisterDestructibleDropEx('LTbs', 'I6AM', 10000, false, 100, 1, 1)  // Ancestral Ward
        call RegisterDestructibleDropEx('LTbs', 'I6AN', 10000, false, 100, 1, 1)  // Supply Crate
        call RegisterDestructibleDropEx('LTbs', 'I6CK', 10000, false, 100, 1, 1)  // Whirlwind
        call RegisterDestructibleDropEx('LTbs', 'I001', 10000, false, 100, 1, 1)  // Earth Crystal
        call RegisterDestructibleDropEx('LTbs', 'I004', 10000, false, 100, 1, 1)  // Wind Crystal
        call RegisterDestructibleDropEx('LTbs', 'I009', 10000, false, 100, 1, 1)  // Spirit Link
        call RegisterDestructibleDropEx('LTbs', 'I00B', 10000, false, 100, 1, 1)  // Wind Shear
        call RegisterDestructibleDropEx('LTbs', 'I00J', 10000, false, 100, 1, 1)  // The One Ring
        call RegisterDestructibleDropEx('LTbs', 'stwp', 10000, false, 100, 1, 1)  // Unknown Item (stwp)
        call RegisterDestructibleDropEx('LTbs', 'vamp', 10000, false, 100, 1, 1)  // Unknown Item (vamp)
        call RegisterDestructibleDropEx('LTbs', 'wneg', 10000, false, 100, 1, 1)  // Unknown Item (wneg)
        call RegisterDestructibleDropEx('LTbs', 'rej6', 10000, false, 100, 1, 1)  // Greater Scroll of Replenishment (old)
        call RegisterDestructibleDropEx('LTbs', 'I608', 10000, false, 100, 1, 1)  // Tome of God
        call RegisterDestructibleDropEx('LTbs', 'I60A', 10000, false, 100, 1, 1)  // Tome of Eternal Agility
        call RegisterDestructibleDropEx('LTbs', 'I60B', 10000, false, 100, 1, 1)  // Tome of Eternal Intelligence
        call RegisterDestructibleDropEx('LTbs', 'I611', 10000, false, 100, 1, 1)  // Camp Fire
        call RegisterDestructibleDropEx('LTbs', 'I624', 10000, false, 100, 1, 1)  // Jin'Zun Healing Ward
        call RegisterDestructibleDropEx('LTbs', 'I6C3', 10000, false, 100, 1, 1)  // Water Shield
        call RegisterDestructibleDropEx('LTbs', 'I00N', 10000, false, 100, 1, 1)  // Gutcleanser Elixir
        call RegisterDestructibleDropEx('LTbs', 'I6A3', 10000, false, 100, 1, 1)  // I6A3
        call RegisterDestructibleDropEx('LTbs', 'I6AO', 10000, false, 100, 1, 1)  // I6AO
        call RegisterDestructibleDropEx('LTbs', 'I69H', 10000, false, 100, 1, 1)  // I69H
        call RegisterDestructibleDropEx('LTbs', 'I69X', 10000, false, 100, 1, 1)  // I69X
        call RegisterDestructibleDropEx('LTbs', 'I69L', 10000, false, 100, 1, 1)  // I69L
        call RegisterDestructibleDropEx('LTbs', 'I00A', 10000, false, 100, 1, 1)  // I00A
        call RegisterDestructibleDropEx('LTbs', 'I69Q', 10000, false, 100, 1, 1)  // I69Q

        // LTbx (Level 1-5) -> loot table 'Destructible Level 1-5'
        call RegisterDestructibleDropEx('LTbx', 'olig', 10000, false, 100, 1, 1)  // Unknown Item (olig)
        call RegisterDestructibleDropEx('LTbx', 'ofir', 10000, false, 100, 1, 1)  // Unknown Item (ofir)
        call RegisterDestructibleDropEx('LTbx', 'hbth', 10000, false, 100, 1, 1)  // Unknown Item (hbth)
        call RegisterDestructibleDropEx('LTbx', 'rugt', 10000, false, 100, 1, 1)  // Unknown Item (rugt)
        call RegisterDestructibleDropEx('LTbx', 'rump', 10000, false, 100, 1, 1)  // Unknown Item (rump)
        call RegisterDestructibleDropEx('LTbx', 'gcel', 10000, false, 100, 1, 1)  // Unknown Item (gcel)
        call RegisterDestructibleDropEx('LTbx', 'plcl', 10000, false, 100, 1, 1)  // Unknown Item (plcl)
        call RegisterDestructibleDropEx('LTbx', 'I602', 10000, false, 100, 1, 1)  // Light Boots
        call RegisterDestructibleDropEx('LTbx', 'I60G', 10000, false, 100, 1, 1)  // Unknown Item (I60G)
        call RegisterDestructibleDropEx('LTbx', 'I60M', 10000, false, 100, 1, 1)  // Rusty Kitchen Knive
        call RegisterDestructibleDropEx('LTbx', 'I60P', 10000, false, 100, 1, 1)  // Worn Gloves
        call RegisterDestructibleDropEx('LTbx', 'I60V', 10000, false, 100, 1, 1)  // |CFFFF8C00Helm of Arenamaster|r
        call RegisterDestructibleDropEx('LTbx', 'I626', 10000, false, 100, 1, 1)  // Gloves of Strength
        call RegisterDestructibleDropEx('LTbx', 'I62A', 10000, false, 100, 1, 1)  // Helm of Strength
        call RegisterDestructibleDropEx('LTbx', 'I62E', 10000, false, 100, 1, 1)  // Axe of Strength
        call RegisterDestructibleDropEx('LTbx', 'I62F', 10000, false, 100, 1, 1)  // Staff of Strength
        call RegisterDestructibleDropEx('LTbx', 'I62I', 10000, false, 100, 1, 1)  // Belt of Intelligence
        call RegisterDestructibleDropEx('LTbx', 'I62M', 10000, false, 100, 1, 1)  // Necklace of Intelligence
        call RegisterDestructibleDropEx('LTbx', 'I62X', 10000, false, 100, 1, 1)  // Ironwood Protector
        call RegisterDestructibleDropEx('LTbx', 'I62Y', 10000, false, 100, 1, 1)  // Arcane Ward
        call RegisterDestructibleDropEx('LTbx', 'I62Z', 10000, false, 100, 1, 1)  // Dragonhide Shield
        call RegisterDestructibleDropEx('LTbx', 'I630', 10000, false, 100, 1, 1)  // Radiant Crest
        call RegisterDestructibleDropEx('LTbx', 'I634', 10000, false, 100, 1, 1)  // Frostbite Ward
        call RegisterDestructibleDropEx('LTbx', 'I63G', 10000, false, 100, 1, 1)  // Moonlit Rod
        call RegisterDestructibleDropEx('LTbx', 'I63H', 10000, false, 100, 1, 1)  // Inferno Scepter
        call RegisterDestructibleDropEx('LTbx', 'I63K', 10000, false, 100, 1, 1)  // Thunderfury Sword
        call RegisterDestructibleDropEx('LTbx', 'I63L', 10000, false, 100, 1, 1)  // Frostbite Axe
        call RegisterDestructibleDropEx('LTbx', 'I63T', 10000, false, 100, 1, 1)  // Soulreaper Halberd
        call RegisterDestructibleDropEx('LTbx', 'I63V', 10000, false, 100, 1, 1)  // Frostshard Greatsword
        call RegisterDestructibleDropEx('LTbx', 'I63X', 10000, false, 100, 1, 1)  // Celestial Crescent Blade
        call RegisterDestructibleDropEx('LTbx', 'I642', 10000, false, 100, 1, 1)  // Skullcrusher Maul
        call RegisterDestructibleDropEx('LTbx', 'I644', 10000, false, 100, 1, 1)  // Thunderhorn Warhammer
        call RegisterDestructibleDropEx('LTbx', 'I649', 10000, false, 100, 1, 1)  // Celestial Harmony Necklace
        call RegisterDestructibleDropEx('LTbx', 'I64B', 10000, false, 100, 1, 1)  // Venomweave Locket
        call RegisterDestructibleDropEx('LTbx', 'I64C', 10000, false, 100, 1, 1)  // Rune-etched Collar
        call RegisterDestructibleDropEx('LTbx', 'I64E', 10000, false, 100, 1, 1)  // Serpent's Coil Necklace
        call RegisterDestructibleDropEx('LTbx', 'I64G', 10000, false, 100, 1, 1)  // Thunderforged Band
        call RegisterDestructibleDropEx('LTbx', 'I64I', 10000, false, 100, 1, 1)  // Celestial Halo
        call RegisterDestructibleDropEx('LTbx', 'I64J', 10000, false, 100, 1, 1)  // Runebound Circlet
        call RegisterDestructibleDropEx('LTbx', 'I64M', 10000, false, 100, 1, 1)  // Bloodfire Signet
        call RegisterDestructibleDropEx('LTbx', 'I64O', 10000, false, 100, 1, 1)  // Ironheart Ring
        call RegisterDestructibleDropEx('LTbx', 'I64Q', 10000, false, 100, 1, 1)  // Thunderforged Breastplate
        call RegisterDestructibleDropEx('LTbx', 'I64V', 10000, false, 100, 1, 1)  // Frostbitten Plate
        call RegisterDestructibleDropEx('LTbx', 'I64X', 10000, false, 100, 1, 1)  // Obsidian Warplate
        call RegisterDestructibleDropEx('LTbx', 'I650', 10000, false, 100, 1, 1)  // Emberweave Robes
        call RegisterDestructibleDropEx('LTbx', 'I653', 10000, false, 100, 1, 1)  // Runebound Silk Tunic
        call RegisterDestructibleDropEx('LTbx', 'I659', 10000, false, 100, 1, 1)  // Cloak of Shadowsong
        call RegisterDestructibleDropEx('LTbx', 'I65R', 10000, false, 100, 1, 1)  // Hammer of the Ancients
        call RegisterDestructibleDropEx('LTbx', 'I65S', 10000, false, 100, 1, 1)  // Gleaming Plate Armor
        call RegisterDestructibleDropEx('LTbx', 'I65V', 10000, false, 100, 1, 1)  // Celestial Robes
        call RegisterDestructibleDropEx('LTbx', 'I665', 10000, false, 100, 1, 1)  // Dragonhide Cloak of the Serpent
        call RegisterDestructibleDropEx('LTbx', 'I669', 10000, false, 100, 1, 1)  // Tattered Leather Gloves
        call RegisterDestructibleDropEx('LTbx', 'I66A', 10000, false, 100, 1, 1)  // Tattered Leather Shoulderpads
        call RegisterDestructibleDropEx('LTbx', 'I66D', 10000, false, 100, 1, 1)  // Tattered Leather Belt
        call RegisterDestructibleDropEx('LTbx', 'I66I', 10000, false, 100, 1, 1)  // Sargoth's Ichor
        call RegisterDestructibleDropEx('LTbx', 'I68O', 10000, false, 100, 1, 1)  // Bronze Boots
        call RegisterDestructibleDropEx('LTbx', 'I68U', 10000, false, 100, 1, 1)  // Silvered Bronze Helmet
        call RegisterDestructibleDropEx('LTbx', 'I68V', 10000, false, 100, 1, 1)  // Silvered Bronze Breastplate
        call RegisterDestructibleDropEx('LTbx', 'I68W', 10000, false, 100, 1, 1)  // Iron Helmet
        call RegisterDestructibleDropEx('LTbx', 'I68Y', 10000, false, 100, 1, 1)  // Iron Breastplate
        call RegisterDestructibleDropEx('LTbx', 'I692', 10000, false, 100, 1, 1)  // Iron Leggings
        call RegisterDestructibleDropEx('LTbx', 'I69D', 10000, false, 100, 1, 1)  // Healing Rain
        call RegisterDestructibleDropEx('LTbx', 'I69I', 10000, false, 100, 1, 1)  // Fire Shock
        call RegisterDestructibleDropEx('LTbx', 'I69T', 10000, false, 100, 1, 1)  // Bloodlust
        call RegisterDestructibleDropEx('LTbx', 'I69U', 10000, false, 100, 1, 1)  // Ghost Wolf
        call RegisterDestructibleDropEx('LTbx', 'I6AC', 10000, false, 100, 1, 1)  // Frost Shock
        call RegisterDestructibleDropEx('LTbx', 'I6AD', 10000, false, 100, 1, 1)  // Nature Shock
        call RegisterDestructibleDropEx('LTbx', 'I6AF', 10000, false, 100, 1, 1)  // Rejuvenation
        call RegisterDestructibleDropEx('LTbx', 'I6AI', 10000, false, 100, 1, 1)  // Spiritmender
        call RegisterDestructibleDropEx('LTbx', 'I6AM', 10000, false, 100, 1, 1)  // Ancestral Ward
        call RegisterDestructibleDropEx('LTbx', 'I6AN', 10000, false, 100, 1, 1)  // Supply Crate
        call RegisterDestructibleDropEx('LTbx', 'I6CK', 10000, false, 100, 1, 1)  // Whirlwind
        call RegisterDestructibleDropEx('LTbx', 'I001', 10000, false, 100, 1, 1)  // Earth Crystal
        call RegisterDestructibleDropEx('LTbx', 'I004', 10000, false, 100, 1, 1)  // Wind Crystal
        call RegisterDestructibleDropEx('LTbx', 'I009', 10000, false, 100, 1, 1)  // Spirit Link
        call RegisterDestructibleDropEx('LTbx', 'I00B', 10000, false, 100, 1, 1)  // Wind Shear
        call RegisterDestructibleDropEx('LTbx', 'I00J', 10000, false, 100, 1, 1)  // The One Ring
        call RegisterDestructibleDropEx('LTbx', 'stwp', 10000, false, 100, 1, 1)  // Unknown Item (stwp)
        call RegisterDestructibleDropEx('LTbx', 'vamp', 10000, false, 100, 1, 1)  // Unknown Item (vamp)
        call RegisterDestructibleDropEx('LTbx', 'wneg', 10000, false, 100, 1, 1)  // Unknown Item (wneg)
        call RegisterDestructibleDropEx('LTbx', 'rej6', 10000, false, 100, 1, 1)  // Greater Scroll of Replenishment (old)
        call RegisterDestructibleDropEx('LTbx', 'I608', 10000, false, 100, 1, 1)  // Tome of God
        call RegisterDestructibleDropEx('LTbx', 'I60A', 10000, false, 100, 1, 1)  // Tome of Eternal Agility
        call RegisterDestructibleDropEx('LTbx', 'I60B', 10000, false, 100, 1, 1)  // Tome of Eternal Intelligence
        call RegisterDestructibleDropEx('LTbx', 'I611', 10000, false, 100, 1, 1)  // Camp Fire
        call RegisterDestructibleDropEx('LTbx', 'I624', 10000, false, 100, 1, 1)  // Jin'Zun Healing Ward
        call RegisterDestructibleDropEx('LTbx', 'I6C3', 10000, false, 100, 1, 1)  // Water Shield
        call RegisterDestructibleDropEx('LTbx', 'I00N', 10000, false, 100, 1, 1)  // Gutcleanser Elixir
        call RegisterDestructibleDropEx('LTbx', 'I6A3', 10000, false, 100, 1, 1)  // I6A3
        call RegisterDestructibleDropEx('LTbx', 'I6AO', 10000, false, 100, 1, 1)  // I6AO
        call RegisterDestructibleDropEx('LTbx', 'I69H', 10000, false, 100, 1, 1)  // I69H
        call RegisterDestructibleDropEx('LTbx', 'I69X', 10000, false, 100, 1, 1)  // I69X
        call RegisterDestructibleDropEx('LTbx', 'I69L', 10000, false, 100, 1, 1)  // I69L
        call RegisterDestructibleDropEx('LTbx', 'I00A', 10000, false, 100, 1, 1)  // I00A
        call RegisterDestructibleDropEx('LTbx', 'I69Q', 10000, false, 100, 1, 1)  // I69Q

        // LTcr (Level 1-5) -> loot table 'Destructible Level 1-5'
        call RegisterDestructibleDropEx('LTcr', 'olig', 10000, false, 100, 1, 1)  // Unknown Item (olig)
        call RegisterDestructibleDropEx('LTcr', 'ofir', 10000, false, 100, 1, 1)  // Unknown Item (ofir)
        call RegisterDestructibleDropEx('LTcr', 'hbth', 10000, false, 100, 1, 1)  // Unknown Item (hbth)
        call RegisterDestructibleDropEx('LTcr', 'rugt', 10000, false, 100, 1, 1)  // Unknown Item (rugt)
        call RegisterDestructibleDropEx('LTcr', 'rump', 10000, false, 100, 1, 1)  // Unknown Item (rump)
        call RegisterDestructibleDropEx('LTcr', 'gcel', 10000, false, 100, 1, 1)  // Unknown Item (gcel)
        call RegisterDestructibleDropEx('LTcr', 'plcl', 10000, false, 100, 1, 1)  // Unknown Item (plcl)
        call RegisterDestructibleDropEx('LTcr', 'I602', 10000, false, 100, 1, 1)  // Light Boots
        call RegisterDestructibleDropEx('LTcr', 'I60G', 10000, false, 100, 1, 1)  // Unknown Item (I60G)
        call RegisterDestructibleDropEx('LTcr', 'I60M', 10000, false, 100, 1, 1)  // Rusty Kitchen Knive
        call RegisterDestructibleDropEx('LTcr', 'I60P', 10000, false, 100, 1, 1)  // Worn Gloves
        call RegisterDestructibleDropEx('LTcr', 'I60V', 10000, false, 100, 1, 1)  // |CFFFF8C00Helm of Arenamaster|r
        call RegisterDestructibleDropEx('LTcr', 'I626', 10000, false, 100, 1, 1)  // Gloves of Strength
        call RegisterDestructibleDropEx('LTcr', 'I62A', 10000, false, 100, 1, 1)  // Helm of Strength
        call RegisterDestructibleDropEx('LTcr', 'I62E', 10000, false, 100, 1, 1)  // Axe of Strength
        call RegisterDestructibleDropEx('LTcr', 'I62F', 10000, false, 100, 1, 1)  // Staff of Strength
        call RegisterDestructibleDropEx('LTcr', 'I62I', 10000, false, 100, 1, 1)  // Belt of Intelligence
        call RegisterDestructibleDropEx('LTcr', 'I62M', 10000, false, 100, 1, 1)  // Necklace of Intelligence
        call RegisterDestructibleDropEx('LTcr', 'I62X', 10000, false, 100, 1, 1)  // Ironwood Protector
        call RegisterDestructibleDropEx('LTcr', 'I62Y', 10000, false, 100, 1, 1)  // Arcane Ward
        call RegisterDestructibleDropEx('LTcr', 'I62Z', 10000, false, 100, 1, 1)  // Dragonhide Shield
        call RegisterDestructibleDropEx('LTcr', 'I630', 10000, false, 100, 1, 1)  // Radiant Crest
        call RegisterDestructibleDropEx('LTcr', 'I634', 10000, false, 100, 1, 1)  // Frostbite Ward
        call RegisterDestructibleDropEx('LTcr', 'I63G', 10000, false, 100, 1, 1)  // Moonlit Rod
        call RegisterDestructibleDropEx('LTcr', 'I63H', 10000, false, 100, 1, 1)  // Inferno Scepter
        call RegisterDestructibleDropEx('LTcr', 'I63K', 10000, false, 100, 1, 1)  // Thunderfury Sword
        call RegisterDestructibleDropEx('LTcr', 'I63L', 10000, false, 100, 1, 1)  // Frostbite Axe
        call RegisterDestructibleDropEx('LTcr', 'I63T', 10000, false, 100, 1, 1)  // Soulreaper Halberd
        call RegisterDestructibleDropEx('LTcr', 'I63V', 10000, false, 100, 1, 1)  // Frostshard Greatsword
        call RegisterDestructibleDropEx('LTcr', 'I63X', 10000, false, 100, 1, 1)  // Celestial Crescent Blade
        call RegisterDestructibleDropEx('LTcr', 'I642', 10000, false, 100, 1, 1)  // Skullcrusher Maul
        call RegisterDestructibleDropEx('LTcr', 'I644', 10000, false, 100, 1, 1)  // Thunderhorn Warhammer
        call RegisterDestructibleDropEx('LTcr', 'I649', 10000, false, 100, 1, 1)  // Celestial Harmony Necklace
        call RegisterDestructibleDropEx('LTcr', 'I64B', 10000, false, 100, 1, 1)  // Venomweave Locket
        call RegisterDestructibleDropEx('LTcr', 'I64C', 10000, false, 100, 1, 1)  // Rune-etched Collar
        call RegisterDestructibleDropEx('LTcr', 'I64E', 10000, false, 100, 1, 1)  // Serpent's Coil Necklace
        call RegisterDestructibleDropEx('LTcr', 'I64G', 10000, false, 100, 1, 1)  // Thunderforged Band
        call RegisterDestructibleDropEx('LTcr', 'I64I', 10000, false, 100, 1, 1)  // Celestial Halo
        call RegisterDestructibleDropEx('LTcr', 'I64J', 10000, false, 100, 1, 1)  // Runebound Circlet
        call RegisterDestructibleDropEx('LTcr', 'I64M', 10000, false, 100, 1, 1)  // Bloodfire Signet
        call RegisterDestructibleDropEx('LTcr', 'I64O', 10000, false, 100, 1, 1)  // Ironheart Ring
        call RegisterDestructibleDropEx('LTcr', 'I64Q', 10000, false, 100, 1, 1)  // Thunderforged Breastplate
        call RegisterDestructibleDropEx('LTcr', 'I64V', 10000, false, 100, 1, 1)  // Frostbitten Plate
        call RegisterDestructibleDropEx('LTcr', 'I64X', 10000, false, 100, 1, 1)  // Obsidian Warplate
        call RegisterDestructibleDropEx('LTcr', 'I650', 10000, false, 100, 1, 1)  // Emberweave Robes
        call RegisterDestructibleDropEx('LTcr', 'I653', 10000, false, 100, 1, 1)  // Runebound Silk Tunic
        call RegisterDestructibleDropEx('LTcr', 'I659', 10000, false, 100, 1, 1)  // Cloak of Shadowsong
        call RegisterDestructibleDropEx('LTcr', 'I65R', 10000, false, 100, 1, 1)  // Hammer of the Ancients
        call RegisterDestructibleDropEx('LTcr', 'I65S', 10000, false, 100, 1, 1)  // Gleaming Plate Armor
        call RegisterDestructibleDropEx('LTcr', 'I65V', 10000, false, 100, 1, 1)  // Celestial Robes
        call RegisterDestructibleDropEx('LTcr', 'I665', 10000, false, 100, 1, 1)  // Dragonhide Cloak of the Serpent
        call RegisterDestructibleDropEx('LTcr', 'I669', 10000, false, 100, 1, 1)  // Tattered Leather Gloves
        call RegisterDestructibleDropEx('LTcr', 'I66A', 10000, false, 100, 1, 1)  // Tattered Leather Shoulderpads
        call RegisterDestructibleDropEx('LTcr', 'I66D', 10000, false, 100, 1, 1)  // Tattered Leather Belt
        call RegisterDestructibleDropEx('LTcr', 'I66I', 10000, false, 100, 1, 1)  // Sargoth's Ichor
        call RegisterDestructibleDropEx('LTcr', 'I68O', 10000, false, 100, 1, 1)  // Bronze Boots
        call RegisterDestructibleDropEx('LTcr', 'I68U', 10000, false, 100, 1, 1)  // Silvered Bronze Helmet
        call RegisterDestructibleDropEx('LTcr', 'I68V', 10000, false, 100, 1, 1)  // Silvered Bronze Breastplate
        call RegisterDestructibleDropEx('LTcr', 'I68W', 10000, false, 100, 1, 1)  // Iron Helmet
        call RegisterDestructibleDropEx('LTcr', 'I68Y', 10000, false, 100, 1, 1)  // Iron Breastplate
        call RegisterDestructibleDropEx('LTcr', 'I692', 10000, false, 100, 1, 1)  // Iron Leggings
        call RegisterDestructibleDropEx('LTcr', 'I69D', 10000, false, 100, 1, 1)  // Healing Rain
        call RegisterDestructibleDropEx('LTcr', 'I69I', 10000, false, 100, 1, 1)  // Fire Shock
        call RegisterDestructibleDropEx('LTcr', 'I69T', 10000, false, 100, 1, 1)  // Bloodlust
        call RegisterDestructibleDropEx('LTcr', 'I69U', 10000, false, 100, 1, 1)  // Ghost Wolf
        call RegisterDestructibleDropEx('LTcr', 'I6AC', 10000, false, 100, 1, 1)  // Frost Shock
        call RegisterDestructibleDropEx('LTcr', 'I6AD', 10000, false, 100, 1, 1)  // Nature Shock
        call RegisterDestructibleDropEx('LTcr', 'I6AF', 10000, false, 100, 1, 1)  // Rejuvenation
        call RegisterDestructibleDropEx('LTcr', 'I6AI', 10000, false, 100, 1, 1)  // Spiritmender
        call RegisterDestructibleDropEx('LTcr', 'I6AM', 10000, false, 100, 1, 1)  // Ancestral Ward
        call RegisterDestructibleDropEx('LTcr', 'I6AN', 10000, false, 100, 1, 1)  // Supply Crate
        call RegisterDestructibleDropEx('LTcr', 'I6CK', 10000, false, 100, 1, 1)  // Whirlwind
        call RegisterDestructibleDropEx('LTcr', 'I001', 10000, false, 100, 1, 1)  // Earth Crystal
        call RegisterDestructibleDropEx('LTcr', 'I004', 10000, false, 100, 1, 1)  // Wind Crystal
        call RegisterDestructibleDropEx('LTcr', 'I009', 10000, false, 100, 1, 1)  // Spirit Link
        call RegisterDestructibleDropEx('LTcr', 'I00B', 10000, false, 100, 1, 1)  // Wind Shear
        call RegisterDestructibleDropEx('LTcr', 'I00J', 10000, false, 100, 1, 1)  // The One Ring
        call RegisterDestructibleDropEx('LTcr', 'stwp', 10000, false, 100, 1, 1)  // Unknown Item (stwp)
        call RegisterDestructibleDropEx('LTcr', 'vamp', 10000, false, 100, 1, 1)  // Unknown Item (vamp)
        call RegisterDestructibleDropEx('LTcr', 'wneg', 10000, false, 100, 1, 1)  // Unknown Item (wneg)
        call RegisterDestructibleDropEx('LTcr', 'rej6', 10000, false, 100, 1, 1)  // Greater Scroll of Replenishment (old)
        call RegisterDestructibleDropEx('LTcr', 'I608', 10000, false, 100, 1, 1)  // Tome of God
        call RegisterDestructibleDropEx('LTcr', 'I60A', 10000, false, 100, 1, 1)  // Tome of Eternal Agility
        call RegisterDestructibleDropEx('LTcr', 'I60B', 10000, false, 100, 1, 1)  // Tome of Eternal Intelligence
        call RegisterDestructibleDropEx('LTcr', 'I611', 10000, false, 100, 1, 1)  // Camp Fire
        call RegisterDestructibleDropEx('LTcr', 'I624', 10000, false, 100, 1, 1)  // Jin'Zun Healing Ward
        call RegisterDestructibleDropEx('LTcr', 'I6C3', 10000, false, 100, 1, 1)  // Water Shield
        call RegisterDestructibleDropEx('LTcr', 'I00N', 10000, false, 100, 1, 1)  // Gutcleanser Elixir
        call RegisterDestructibleDropEx('LTcr', 'I6A3', 10000, false, 100, 1, 1)  // I6A3
        call RegisterDestructibleDropEx('LTcr', 'I6AO', 10000, false, 100, 1, 1)  // I6AO
        call RegisterDestructibleDropEx('LTcr', 'I69H', 10000, false, 100, 1, 1)  // I69H
        call RegisterDestructibleDropEx('LTcr', 'I69X', 10000, false, 100, 1, 1)  // I69X
        call RegisterDestructibleDropEx('LTcr', 'I69L', 10000, false, 100, 1, 1)  // I69L
        call RegisterDestructibleDropEx('LTcr', 'I00A', 10000, false, 100, 1, 1)  // I00A
        call RegisterDestructibleDropEx('LTcr', 'I69Q', 10000, false, 100, 1, 1)  // I69Q

    endfunction

    private function Init takes nothing returns nothing
        // Destructible drop registration delayed to allow ItemLootDestructibles to initialize
        call TimerStart(CreateTimer(), 0.03, false, function RegisterAllDestructibleDrops)
    endfunction

endlibrary
