//===========================================================================
// ItemLootDefinitionsDestructible.j
// Generated by WC3ItemManager - DO NOT EDIT MANUALLY
// Generated: 2026-07-03 11.50.42
//===========================================================================

library ItemLootDefinitionsDestructible initializer Init requires ItemLootDestructibles

    private function RegisterAllDestructibleDrops takes nothing returns nothing
        call DestroyTimer(GetExpiredTimer())

        // === DESTRUCTIBLE LEVELS (for Generic drops) ===
        // RegisterDestructibleLevel(destructibleTypeId, level)

        call RegisterDestructibleLevel('B60J', 1)  // Stash (Basic 1-5)
        call RegisterDestructibleLevel('B60K', 1)  // Stash (Metallic 1-5)
        call RegisterDestructibleLevel('B60L', 1)  // Stash (Basic 5-10)
        call RegisterDestructibleLevel('B60M', 1)  // Stash (Basic 10-15)
        call RegisterDestructibleLevel('B60N', 1)  // Stash (Basic 15-20)
        call RegisterDestructibleLevel('B60O', 1)  // Stash (Basic 20-25)
        call RegisterDestructibleLevel('B60P', 1)  // Stash (Basic 25-30)
        call RegisterDestructibleLevel('B60Q', 1)  // Stash (Tribal 1-5)
        call RegisterDestructibleLevel('B60R', 1)  // Stash (Basic2 1-5)
        call RegisterDestructibleLevel('B60S', 1)  // Stash (Ancient 1-5)
        call RegisterDestructibleLevel('B60T', 1)  // Stash (Basic2 5-10)
        call RegisterDestructibleLevel('B60U', 1)  // Stash (Basic2 10-15)
        call RegisterDestructibleLevel('B60V', 1)  // Stash (Basic2 15-20)
        call RegisterDestructibleLevel('B60W', 1)  // Stash (Basic2 20-25)
        call RegisterDestructibleLevel('B60X', 1)  // Stash (Basic2 25-30)
        call RegisterDestructibleLevel('B60Y', 1)  // Stash (Ancient 5-10)
        call RegisterDestructibleLevel('B60Z', 1)  // Stash (Ancient 10-15)
        call RegisterDestructibleLevel('B610', 1)  // Stash (Ancient 15-20)
        call RegisterDestructibleLevel('B611', 1)  // Stash (Ancient 20-25)
        call RegisterDestructibleLevel('B612', 1)  // Stash (Ancient 25-30)
        call RegisterDestructibleLevel('B614', 1)  // Stash (Tribal 10-15)
        call RegisterDestructibleLevel('B615', 1)  // Stash (Tribal 15-20)
        call RegisterDestructibleLevel('B616', 1)  // Stash (Tribal 20-25)
        call RegisterDestructibleLevel('B617', 1)  // Stash (Tribal 25-30)
        call RegisterDestructibleLevel('B618', 1)  // Stash (Metallic 5-10)
        call RegisterDestructibleLevel('B619', 1)  // Stash (Metallic 10-15)
        call RegisterDestructibleLevel('B61A', 1)  // Stash (Metallic 15-20)
        call RegisterDestructibleLevel('B61B', 1)  // Stash (Metallic 20-25)
        call RegisterDestructibleLevel('B61C', 1)  // Stash (Metallic 25-30)
        call RegisterDestructibleLevel('B61D', 1)  // Stash (Quest)
        call RegisterDestructibleLevel('LTbr', 1)  // LTbr (Level 1-5)
        call RegisterDestructibleLevel('LTbs', 1)  // LTbs (Level 1-5)
        call RegisterDestructibleLevel('LTbx', 1)  // LTbx (Level 1-5)
        call RegisterDestructibleLevel('LTcr', 1)  // LTcr (Level 1-5)
        call RegisterDestructibleLevel('B01P', 6)  // B01P (Level 6-10)
        call RegisterDestructibleLevel('B01U', 6)  // B01U (Level 6-10)
        call RegisterDestructibleLevel('B01V', 6)  // B01V (Level 6-10)
        call RegisterDestructibleLevel('B01W', 6)  // B01W (Level 6-10)
        call RegisterDestructibleLevel('B02A', 10)  // B02A (Gnoll Hideout)
        call RegisterDestructibleLevel('B01Q', 11)  // B01Q (Level 11-15)
        call RegisterDestructibleLevel('B01X', 11)  // B01X (Level 11-15)
        call RegisterDestructibleLevel('B01Y', 11)  // B01Y (Level 11-15)
        call RegisterDestructibleLevel('B01Z', 11)  // B01Z (Level 11-15)
        call RegisterDestructibleLevel('B029', 15)  // B029 (Crypt)
        call RegisterDestructibleLevel('B02B', 15)  // B02B (Boom Brothers Mine)
        call RegisterDestructibleLevel('B01R', 16)  // B01R (Level 16-20)
        call RegisterDestructibleLevel('B020', 16)  // B020 (Level 16-20)
        call RegisterDestructibleLevel('B021', 16)  // B021 (Level 16-20)
        call RegisterDestructibleLevel('B022', 16)  // B022 (Level 16-20)
        call RegisterDestructibleLevel('B01S', 21)  // B01S (Level 21-25)
        call RegisterDestructibleLevel('B023', 21)  // B023 (Level 21-25)
        call RegisterDestructibleLevel('B024', 21)  // B024 (Level 21-25)
        call RegisterDestructibleLevel('B025', 21)  // B025 (Level 21-25)
        call RegisterDestructibleLevel('B01T', 26)  // B01T (Level 26-30)
        call RegisterDestructibleLevel('B026', 26)  // B026 (Level 26-30)
        call RegisterDestructibleLevel('B027', 26)  // B027 (Level 26-30)
        call RegisterDestructibleLevel('B028', 26)  // B028 (Level 26-30)

        // === DESTRUCTIBLE SPECIFIC DROPS ===
        // RegisterDestructibleDropEx(destructibleTypeId, itemTypeId, dropChance, isGuaranteed, weight, quantityMin, quantityMax)

    endfunction

    private function Init takes nothing returns nothing
        // Destructible drop registration delayed to allow ItemLootDestructibles to initialize
        call TimerStart(CreateTimer(), 0.03, false, function RegisterAllDestructibleDrops)
    endfunction

endlibrary
