/**
    VendorHumans

    Author: Valdemar
    Version: 1.0.0

    Description:
    Assigns the custom Human vendor unit types to Riverbane, Stormhaven, and
    neutral merchant roles and voice profiles.

    Credits:

    How to install:
    Import after VendorCatalogs.

    API:
    - Registers Human vendor unit types automatically during initialization.

**/
library VendorHumans initializer Init requires VendorCatalogs
    private function Register takes integer unitTypeId, integer catalogType, string profile, string voiceType returns nothing
        call VendorCatalogs_RegisterUnitType(unitTypeId, catalogType, profile)
        call VendorLines_BindUnitTypeVoiceType(unitTypeId, voiceType)
        if profile == VL_VENDOR_PROFILE_HUMAN_RIVERBANE_MALE or profile == VL_VENDOR_PROFILE_HUMAN_RIVERBANE_FEMALE then
            call Reputation_RegisterUnitTypeFaction(unitTypeId, "Riverbane")
        elseif profile == VL_VENDOR_PROFILE_HUMAN_STORMHAVEN_MALE or profile == VL_VENDOR_PROFILE_HUMAN_STORMHAVEN_FEMALE then
            call Reputation_RegisterUnitTypeFaction(unitTypeId, "Stormhaven")
        else
            call Reputation_RegisterUnitTypeFaction(unitTypeId, "Human Citizen")
        endif
    endfunction

    private function Init takes nothing returns nothing
        // Riverbane merchants.
        call Register('n035', VendorCatalogs_VENDOR_CATALOG_WEAPONS, VL_VENDOR_PROFILE_HUMAN_RIVERBANE_MALE, VL_HUMAN_MALE_1_TYPE)
        call Register('n039', VendorCatalogs_VENDOR_CATALOG_ARMOR, VL_VENDOR_PROFILE_HUMAN_RIVERBANE_MALE, VL_HUMAN_MALE_2_TYPE)
        call Register('n03A', VendorCatalogs_VENDOR_CATALOG_SHIELDS, VL_VENDOR_PROFILE_HUMAN_RIVERBANE_MALE, VL_HUMAN_MALE_1_TYPE)
        call Register('n03E', VendorCatalogs_VENDOR_CATALOG_MINER, VL_VENDOR_PROFILE_HUMAN_RIVERBANE_MALE, VL_HUMAN_MALE_2_TYPE)
        call Register('n03G', VendorCatalogs_VENDOR_CATALOG_ALCHEMY_SUPPLIES, VL_VENDOR_PROFILE_HUMAN_RIVERBANE_MALE, VL_HUMAN_MALE_1_TYPE)
        call Register('n03H', VendorCatalogs_VENDOR_CATALOG_BLACKSMITHING_SUPPLIES, VL_VENDOR_PROFILE_HUMAN_RIVERBANE_MALE, VL_HUMAN_MALE_2_TYPE)
        call Register('n03L', VendorCatalogs_VENDOR_CATALOG_LEATHERWORKING_SUPPLIES, VL_VENDOR_PROFILE_HUMAN_RIVERBANE_MALE, VL_HUMAN_MALE_1_TYPE)
        call Register('n03M', VendorCatalogs_VENDOR_CATALOG_MINING_SUPPLIES, VL_VENDOR_PROFILE_HUMAN_RIVERBANE_MALE, VL_HUMAN_MALE_2_TYPE)
        call Register('n03N', VendorCatalogs_VENDOR_CATALOG_SKINNING_SUPPLIES, VL_VENDOR_PROFILE_HUMAN_RIVERBANE_MALE, VL_HUMAN_MALE_1_TYPE)
        call Register('n03P', VendorCatalogs_VENDOR_CATALOG_QUARTERMASTER, VL_VENDOR_PROFILE_HUMAN_RIVERBANE_MALE, VL_HUMAN_MALE_2_TYPE)

        // Stormhaven merchants.
        call Register('n03D', VendorCatalogs_VENDOR_CATALOG_FISHER, VL_VENDOR_PROFILE_HUMAN_STORMHAVEN_MALE, VL_HUMAN_MALE_1_TYPE)
        call Register('n03F', VendorCatalogs_VENDOR_CATALOG_COOK, VL_VENDOR_PROFILE_HUMAN_STORMHAVEN_MALE, VL_HUMAN_MALE_2_TYPE)
        call Register('n03I', VendorCatalogs_VENDOR_CATALOG_COOKING_SUPPLIES, VL_VENDOR_PROFILE_HUMAN_STORMHAVEN_MALE, VL_HUMAN_MALE_1_TYPE)
        call Register('n03J', VendorCatalogs_VENDOR_CATALOG_ENCHANTING_SUPPLIES, VL_VENDOR_PROFILE_HUMAN_STORMHAVEN_MALE, VL_HUMAN_MALE_2_TYPE)
        call Register('n03K', VendorCatalogs_VENDOR_CATALOG_FISHING_SUPPLIES, VL_VENDOR_PROFILE_HUMAN_STORMHAVEN_MALE, VL_HUMAN_MALE_1_TYPE)
        call Register('n03R', VendorCatalogs_VENDOR_CATALOG_REAGENTS, VL_VENDOR_PROFILE_HUMAN_STORMHAVEN_MALE, VL_HUMAN_MALE_2_TYPE)
        call Register('n03S', VendorCatalogs_VENDOR_CATALOG_FOOD_AND_DRINK, VL_VENDOR_PROFILE_HUMAN_STORMHAVEN_MALE, VL_HUMAN_MALE_1_TYPE)

        // Neutral and travelling merchants.
        call Register('n03B', VendorCatalogs_VENDOR_CATALOG_ARENA, VL_VENDOR_PROFILE_HUMAN_NEUTRAL_MALE, VL_HUMAN_MALE_1_TYPE)
        call Register('n03C', VendorCatalogs_VENDOR_CATALOG_TRAVELLING, VL_VENDOR_PROFILE_HUMAN_NEUTRAL_MALE, VL_HUMAN_MALE_2_TYPE)
        call Register('n03O', VendorCatalogs_VENDOR_CATALOG_PROFESSION_SUPPLIES, VL_VENDOR_PROFILE_HUMAN_NEUTRAL_MALE, VL_HUMAN_MALE_1_TYPE)
        call Register('n03Q', VendorCatalogs_VENDOR_CATALOG_RANDOMIZED_GOODS, VL_VENDOR_PROFILE_HUMAN_NEUTRAL_MALE, VL_HUMAN_MALE_2_TYPE)
        call Register('n03T', VendorCatalogs_VENDOR_CATALOG_POTIONS, VL_VENDOR_PROFILE_HUMAN_NEUTRAL_MALE, VL_HUMAN_MALE_1_TYPE)
        call Register('n03U', VendorCatalogs_VENDOR_CATALOG_RARE_GOODS, VL_VENDOR_PROFILE_HUMAN_NEUTRAL_MALE, VL_HUMAN_MALE_2_TYPE)
        call Register('n03V', VendorCatalogs_VENDOR_CATALOG_ADVENTURING_SUPPLIES, VL_VENDOR_PROFILE_HUMAN_NEUTRAL_MALE, VL_HUMAN_MALE_1_TYPE)

        // Female Riverbane merchants.
        call Register('n04O', VendorCatalogs_VENDOR_CATALOG_WEAPONS, VL_VENDOR_PROFILE_HUMAN_RIVERBANE_FEMALE, VL_HUMAN_FEMALE_1_TYPE)
        call Register('n04P', VendorCatalogs_VENDOR_CATALOG_ARMOR, VL_VENDOR_PROFILE_HUMAN_RIVERBANE_FEMALE, VL_HUMAN_FEMALE_2_TYPE)
        call Register('n04Q', VendorCatalogs_VENDOR_CATALOG_SHIELDS, VL_VENDOR_PROFILE_HUMAN_RIVERBANE_FEMALE, VL_HUMAN_FEMALE_1_TYPE)
        call Register('n04R', VendorCatalogs_VENDOR_CATALOG_MINER, VL_VENDOR_PROFILE_HUMAN_RIVERBANE_FEMALE, VL_HUMAN_FEMALE_2_TYPE)
        call Register('n04S', VendorCatalogs_VENDOR_CATALOG_ALCHEMY_SUPPLIES, VL_VENDOR_PROFILE_HUMAN_RIVERBANE_FEMALE, VL_HUMAN_FEMALE_1_TYPE)
        call Register('n04T', VendorCatalogs_VENDOR_CATALOG_BLACKSMITHING_SUPPLIES, VL_VENDOR_PROFILE_HUMAN_RIVERBANE_FEMALE, VL_HUMAN_FEMALE_2_TYPE)
        call Register('n04U', VendorCatalogs_VENDOR_CATALOG_LEATHERWORKING_SUPPLIES, VL_VENDOR_PROFILE_HUMAN_RIVERBANE_FEMALE, VL_HUMAN_FEMALE_1_TYPE)
        call Register('n04V', VendorCatalogs_VENDOR_CATALOG_MINING_SUPPLIES, VL_VENDOR_PROFILE_HUMAN_RIVERBANE_FEMALE, VL_HUMAN_FEMALE_2_TYPE)
        call Register('n04W', VendorCatalogs_VENDOR_CATALOG_SKINNING_SUPPLIES, VL_VENDOR_PROFILE_HUMAN_RIVERBANE_FEMALE, VL_HUMAN_FEMALE_1_TYPE)
        call Register('n04X', VendorCatalogs_VENDOR_CATALOG_QUARTERMASTER, VL_VENDOR_PROFILE_HUMAN_RIVERBANE_FEMALE, VL_HUMAN_FEMALE_2_TYPE)

        // Female Stormhaven merchants.
        call Register('n04Y', VendorCatalogs_VENDOR_CATALOG_FISHER, VL_VENDOR_PROFILE_HUMAN_STORMHAVEN_FEMALE, VL_HUMAN_FEMALE_1_TYPE)
        call Register('n04Z', VendorCatalogs_VENDOR_CATALOG_COOK, VL_VENDOR_PROFILE_HUMAN_STORMHAVEN_FEMALE, VL_HUMAN_FEMALE_2_TYPE)
        call Register('n050', VendorCatalogs_VENDOR_CATALOG_COOKING_SUPPLIES, VL_VENDOR_PROFILE_HUMAN_STORMHAVEN_FEMALE, VL_HUMAN_FEMALE_1_TYPE)
        call Register('n051', VendorCatalogs_VENDOR_CATALOG_ENCHANTING_SUPPLIES, VL_VENDOR_PROFILE_HUMAN_STORMHAVEN_FEMALE, VL_HUMAN_FEMALE_2_TYPE)
        call Register('n052', VendorCatalogs_VENDOR_CATALOG_FISHING_SUPPLIES, VL_VENDOR_PROFILE_HUMAN_STORMHAVEN_FEMALE, VL_HUMAN_FEMALE_1_TYPE)
        call Register('n053', VendorCatalogs_VENDOR_CATALOG_REAGENTS, VL_VENDOR_PROFILE_HUMAN_STORMHAVEN_FEMALE, VL_HUMAN_FEMALE_2_TYPE)
        call Register('n054', VendorCatalogs_VENDOR_CATALOG_FOOD_AND_DRINK, VL_VENDOR_PROFILE_HUMAN_STORMHAVEN_FEMALE, VL_HUMAN_FEMALE_1_TYPE)

        // Female neutral and travelling merchants.
        call Register('n055', VendorCatalogs_VENDOR_CATALOG_ARENA, VL_VENDOR_PROFILE_HUMAN_NEUTRAL_FEMALE, VL_HUMAN_FEMALE_1_TYPE)
        call Register('n056', VendorCatalogs_VENDOR_CATALOG_TRAVELLING, VL_VENDOR_PROFILE_HUMAN_NEUTRAL_FEMALE, VL_HUMAN_FEMALE_2_TYPE)
        call Register('n057', VendorCatalogs_VENDOR_CATALOG_PROFESSION_SUPPLIES, VL_VENDOR_PROFILE_HUMAN_NEUTRAL_FEMALE, VL_HUMAN_FEMALE_1_TYPE)
        call Register('n058', VendorCatalogs_VENDOR_CATALOG_RANDOMIZED_GOODS, VL_VENDOR_PROFILE_HUMAN_NEUTRAL_FEMALE, VL_HUMAN_FEMALE_2_TYPE)
        call Register('n059', VendorCatalogs_VENDOR_CATALOG_POTIONS, VL_VENDOR_PROFILE_HUMAN_NEUTRAL_FEMALE, VL_HUMAN_FEMALE_1_TYPE)
        call Register('n05A', VendorCatalogs_VENDOR_CATALOG_RARE_GOODS, VL_VENDOR_PROFILE_HUMAN_NEUTRAL_FEMALE, VL_HUMAN_FEMALE_2_TYPE)
        call Register('n05B', VendorCatalogs_VENDOR_CATALOG_ADVENTURING_SUPPLIES, VL_VENDOR_PROFILE_HUMAN_NEUTRAL_FEMALE, VL_HUMAN_FEMALE_1_TYPE)

        // Tavern and arcane specialists.
        call Register('n05C', VendorCatalogs_VENDOR_CATALOG_BARTENDER, VL_VENDOR_PROFILE_HUMAN_STORMHAVEN_MALE, VL_HUMAN_MALE_2_TYPE)
        call Register('n05D', VendorCatalogs_VENDOR_CATALOG_BARTENDER, VL_VENDOR_PROFILE_HUMAN_RIVERBANE_FEMALE, VL_HUMAN_FEMALE_2_TYPE)
        call Register('n05E', VendorCatalogs_VENDOR_CATALOG_BARTENDER, VL_VENDOR_PROFILE_HUMAN_NEUTRAL_FEMALE, VL_HUMAN_FEMALE_1_TYPE)
        call Register('n05K', VendorCatalogs_VENDOR_CATALOG_ARCANIST, VL_VENDOR_PROFILE_HUMAN_STORMHAVEN_MALE, VL_HUMAN_MALE_1_TYPE)
    endfunction
endlibrary
