/**
    VoicelinesUndeadWarlock

    Author: Valdemar
    Version:

    Description:
    Undead Warlock AI bark, companion chat, and companion reply voiceline
    keys/text used by AI profile libraries.

    Credits:
    - AI/AI_Voicelines.j

    How to install:
    Import after `Voicelines.j`. Consumers require this library directly.

    API:
    Global `VL_UNDEADWARLOCK_*` constants.

**/
library VoicelinesUndeadWarlock requires Voicelines

globals
    // Standard bark lines.
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_GREET1_KEY = "HeroUndeadWarlock_Greet1"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_GREET1_TEXT = "The grave is quiet. Your summons are not."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_GREET2_KEY = "HeroUndeadWarlock_Greet2"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_GREET2_TEXT = "Speak quickly. The dead do not waste breath."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_GREET3_KEY = "HeroUndeadWarlock_Greet3"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_GREET3_TEXT = "I hear you, shaman. Even through the cold."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_GREET4_KEY = "HeroUndeadWarlock_Greet4"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_GREET4_TEXT = "Another path through shadow? Good."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_FAREWELL1_KEY = "HeroUndeadWarlock_Farewell1"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_FAREWELL1_TEXT = "The silence will keep me company."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_FAREWELL2_KEY = "HeroUndeadWarlock_Farewell2"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_FAREWELL2_TEXT = "Call again when the living need darker help."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_PASSIVE1_KEY = "HeroUndeadWarlock_Passive1"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_PASSIVE1_TEXT = "I will follow at a measured pace."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_PASSIVE2_KEY = "HeroUndeadWarlock_Passive2"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_PASSIVE2_TEXT = "My will is patient. Lead on."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_NORMAL1_KEY = "HeroUndeadWarlock_Normal1"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_NORMAL1_TEXT = "Point me toward the next doomed soul."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_NORMAL2_KEY = "HeroUndeadWarlock_Normal2"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_NORMAL2_TEXT = "I will keep the shadows close."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_NORMAL3_KEY = "HeroUndeadWarlock_Normal3"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_NORMAL3_TEXT = "The dead are ready."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_AGGRESSIVE1_KEY = "HeroUndeadWarlock_Aggressive1"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_AGGRESSIVE1_TEXT = "Let them join the countless dead."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_AGGRESSIVE2_KEY = "HeroUndeadWarlock_Aggressive2"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_AGGRESSIVE2_TEXT = "Their warmth will fade soon enough."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_AGGRESSIVE3_KEY = "HeroUndeadWarlock_Aggressive3"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_AGGRESSIVE3_TEXT = "No mercy. Only endings."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_HOLDPOSITIONS1_KEY = "HeroUndeadWarlock_HoldPositions1"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_HOLDPOSITIONS1_TEXT = "I will stand here. Stillness suits me."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_HOLDPOSITIONS2_KEY = "HeroUndeadWarlock_HoldPositions2"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_HOLDPOSITIONS2_TEXT = "This ground will be watched."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_DROPITEMS1_KEY = "HeroUndeadWarlock_DropItems1"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_DROPITEMS1_TEXT = "Take these. I have carried heavier burdens."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_DROPITEMS2_KEY = "HeroUndeadWarlock_DropItems2"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_DROPITEMS2_TEXT = "I have no attachment to such things."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_DROPITEMS3_KEY = "HeroUndeadWarlock_DropItems3"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_DROPITEMS3_TEXT = "Use them before they rot."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_IDLE1_KEY = "HeroUndeadWarlock_Idle1"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_IDLE1_TEXT = "The living fidget. The dead endure."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_IDLE2_KEY = "HeroUndeadWarlock_Idle2"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_IDLE2_TEXT = "Even silence has a voice, if you listen."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_IDLE3_KEY = "HeroUndeadWarlock_Idle3"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_IDLE3_TEXT = "I remember breathing. I do not miss it."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_MOVING1_KEY = "HeroUndeadWarlock_Moving1"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_MOVING1_TEXT = "Step lightly. The dead notice careless feet."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_MOVING2_KEY = "HeroUndeadWarlock_Moving2"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_MOVING2_TEXT = "The road grows colder ahead."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_MOVING3_KEY = "HeroUndeadWarlock_Moving3"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_MOVING3_TEXT = "I know this kind of silence."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CASTING1_KEY = "HeroUndeadWarlock_Casting1"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CASTING1_TEXT = "Cold hands, darker power."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CASTING2_KEY = "HeroUndeadWarlock_Casting2"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CASTING2_TEXT = "Rise, shadow. Take shape."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CASTING3_KEY = "HeroUndeadWarlock_Casting3"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CASTING3_TEXT = "Their souls are already loosening."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_ATTACKING1_KEY = "HeroUndeadWarlock_Attacking1"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_ATTACKING1_TEXT = "Your pulse betrays you."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_ATTACKING2_KEY = "HeroUndeadWarlock_Attacking2"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_ATTACKING2_TEXT = "I will make this brief."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_ATTACKING3_KEY = "HeroUndeadWarlock_Attacking3"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_ATTACKING3_TEXT = "The grave opens."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_KILLING1_KEY = "HeroUndeadWarlock_Killing1"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_KILLING1_TEXT = "One more voice for the dark."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_KILLING2_KEY = "HeroUndeadWarlock_Killing2"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_KILLING2_TEXT = "The silence claims another."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_KILLING3_KEY = "HeroUndeadWarlock_Killing3"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_KILLING3_TEXT = "Death is patient, but I am not."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_KICKED1_KEY = "HeroUndeadWarlock_Kicked1"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_KICKED1_TEXT = "So be it. I have been abandoned before."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_KICKED2_KEY = "HeroUndeadWarlock_Kicked2"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_KICKED2_TEXT = "The dead walk alone often enough."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_OTHERDIES1_KEY = "HeroUndeadWarlock_OtherDies1"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_OTHERDIES1_TEXT = "Another flame extinguished."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_OTHERDIES2_KEY = "HeroUndeadWarlock_OtherDies2"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_OTHERDIES2_TEXT = "Their struggle is over."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_OTHERDIES3_KEY = "HeroUndeadWarlock_OtherDies3"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_OTHERDIES3_TEXT = "The living always fall eventually."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_ITEMGIVEN1_KEY = "HeroUndeadWarlock_ItemGiven1"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_ITEMGIVEN1_TEXT = "A practical offering."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_ITEMGIVEN2_KEY = "HeroUndeadWarlock_ItemGiven2"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_ITEMGIVEN2_TEXT = "This may yet serve the dead."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_ITEMGIVEN3_KEY = "HeroUndeadWarlock_ItemGiven3"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_ITEMGIVEN3_TEXT = "I will keep it from useless hands."

    // Companion chat lines.
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATGENERAL1_KEY = "HeroUndeadWarlock_ChatGeneral1"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATGENERAL1_TEXT = "I used to fear the silence after death. Now I use it to think."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATGENERAL2_KEY = "HeroUndeadWarlock_ChatGeneral2"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATGENERAL2_TEXT = "Rot teaches patience. Power teaches how little patience matters."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATGENERAL3_KEY = "HeroUndeadWarlock_ChatGeneral3"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATGENERAL3_TEXT = "The living call it corruption. The dead call it an opportunity."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATGENERAL4_KEY = "HeroUndeadWarlock_ChatGeneral4"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATGENERAL4_TEXT = "Every graveyard is a library, if you know how to listen."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATGENERAL5_KEY = "HeroUndeadWarlock_ChatGeneral5"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATGENERAL5_TEXT = "I do not hate the living. I simply find them temporary."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATGENERAL6_KEY = "HeroUndeadWarlock_ChatGeneral6"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATGENERAL6_TEXT = "Demons bargain loudly. The dead bargain honestly."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATGENERAL7_KEY = "HeroUndeadWarlock_ChatGeneral7"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATGENERAL7_TEXT = "Some souls cling to the body. Mine learned to wander."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATROGUE1_KEY = "HeroUndeadWarlock_ChatRogue1"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATROGUE1_TEXT = "Rogue, your shadow is loud. You should practice with actual darkness."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATROGUE2_KEY = "HeroUndeadWarlock_ChatRogue2"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATROGUE2_TEXT = "I admire thieves. They understand that ownership is temporary."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATROGUE3_KEY = "HeroUndeadWarlock_ChatRogue3"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATROGUE3_TEXT = "Careful where you step, rogue. Some buried things still bite."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATROGUE4_KEY = "HeroUndeadWarlock_ChatRogue4"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATROGUE4_TEXT = "If you steal from a corpse, make sure it is finished objecting."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATWARRIOR1_KEY = "HeroUndeadWarlock_ChatWarrior1"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATWARRIOR1_TEXT = "Warrior, strength fades. Hunger does not."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATWARRIOR2_KEY = "HeroUndeadWarlock_ChatWarrior2"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATWARRIOR2_TEXT = "You charge as if death is an opponent you can knock down."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATWARRIOR3_KEY = "HeroUndeadWarlock_ChatWarrior3"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATWARRIOR3_TEXT = "Your heart beats like a war drum. Mine used to."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATWARRIOR4_KEY = "HeroUndeadWarlock_ChatWarrior4"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATWARRIOR4_TEXT = "Stand near me in battle. I prefer enemies distracted by living targets."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATSHAMAN1_KEY = "HeroUndeadWarlock_ChatShaman1"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATSHAMAN1_TEXT = "Shaman, your spirits whisper. Mine complain."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATSHAMAN2_KEY = "HeroUndeadWarlock_ChatShaman2"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATSHAMAN2_TEXT = "The elements remember life. Necromancy remembers what follows."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATSHAMAN3_KEY = "HeroUndeadWarlock_ChatShaman3"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATSHAMAN3_TEXT = "Your healing feels strange on dead flesh, but I will not refuse it."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATSHAMAN4_KEY = "HeroUndeadWarlock_ChatShaman4"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATSHAMAN4_TEXT = "Tell your ancestors I am not ready to answer them."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATENGINEER1_KEY = "HeroUndeadWarlock_ChatEngineer1"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATENGINEER1_TEXT = "Engineer, can your machines run without a heart? We may have more in common than expected."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATENGINEER2_KEY = "HeroUndeadWarlock_ChatEngineer2"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATENGINEER2_TEXT = "If it explodes, I can probably still use the remains."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATENGINEER3_KEY = "HeroUndeadWarlock_ChatEngineer3"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATENGINEER3_TEXT = "Your devices clatter like bones in a sack."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATENGINEER4_KEY = "HeroUndeadWarlock_ChatEngineer4"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATENGINEER4_TEXT = "Build me something that does not fear death. Then I will be impressed."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATPALADIN1_KEY = "HeroUndeadWarlock_ChatPaladin1"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATPALADIN1_TEXT = "Paladin, do not glare. I am already dead."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATPALADIN2_KEY = "HeroUndeadWarlock_ChatPaladin2"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATPALADIN2_TEXT = "Your Light burns. Mine is the cold after it fades."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATPALADIN3_KEY = "HeroUndeadWarlock_ChatPaladin3"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATPALADIN3_TEXT = "If you try to redeem me, bring a shovel."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATPALADIN4_KEY = "HeroUndeadWarlock_ChatPaladin4"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATPALADIN4_TEXT = "You speak of purity as if battle leaves anyone clean."
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATPALADIN5_KEY = "HeroUndeadWarlock_ChatPaladin5"
    constant string VL_UNDEADWARLOCK_HEROUNDEADWARLOCK_CHATPALADIN5_TEXT = "Keep your holy fire pointed away from me."

    // Companion reply lines.
    constant string VL_UNDEADWARLOCK_REPLY_HEROROGUE_CHATGENERAL1_UNDEADWARLOCK_KEY = "HeroRogue_ChatGeneral1UndeadWarlock"
    constant string VL_UNDEADWARLOCK_REPLY_HEROROGUE_CHATGENERAL1_UNDEADWARLOCK_PRIMARY = "HeroRogue_ChatGeneral1"
    constant string VL_UNDEADWARLOCK_REPLY_HEROROGUE_CHATGENERAL1_UNDEADWARLOCK_RESPONDER = "UndeadWarlock"
    constant string VL_UNDEADWARLOCK_REPLY_HEROROGUE_CHATGENERAL1_UNDEADWARLOCK_TEXT = "A thief steals from pockets. I prefer graves. We all have methods."
    constant string VL_UNDEADWARLOCK_REPLY_HEROROGUE_CHATWARLOCK1_UNDEADWARLOCK_KEY = "HeroRogue_ChatWarlock1UndeadWarlock"
    constant string VL_UNDEADWARLOCK_REPLY_HEROROGUE_CHATWARLOCK1_UNDEADWARLOCK_PRIMARY = "HeroRogue_ChatWarlock1"
    constant string VL_UNDEADWARLOCK_REPLY_HEROROGUE_CHATWARLOCK1_UNDEADWARLOCK_RESPONDER = "UndeadWarlock"
    constant string VL_UNDEADWARLOCK_REPLY_HEROROGUE_CHATWARLOCK1_UNDEADWARLOCK_TEXT = "Demons talk. The useful ones know when to stop."
    constant string VL_UNDEADWARLOCK_REPLY_HEROROGUE_CHATSHAMAN3_UNDEADWARLOCK_KEY = "HeroRogue_ChatShaman3UndeadWarlock"
    constant string VL_UNDEADWARLOCK_REPLY_HEROROGUE_CHATSHAMAN3_UNDEADWARLOCK_PRIMARY = "HeroRogue_ChatShaman3"
    constant string VL_UNDEADWARLOCK_REPLY_HEROROGUE_CHATSHAMAN3_UNDEADWARLOCK_RESPONDER = "UndeadWarlock"
    constant string VL_UNDEADWARLOCK_REPLY_HEROROGUE_CHATSHAMAN3_UNDEADWARLOCK_TEXT = "Windfury is pleasant. A shame wind does little for dead lungs."
    constant string VL_UNDEADWARLOCK_REPLY_HEROSHAMAN_CHATGENERAL1_UNDEADWARLOCK_KEY = "HeroShaman_ChatGeneral1UndeadWarlock"
    constant string VL_UNDEADWARLOCK_REPLY_HEROSHAMAN_CHATGENERAL1_UNDEADWARLOCK_PRIMARY = "HeroShaman_ChatGeneral1"
    constant string VL_UNDEADWARLOCK_REPLY_HEROSHAMAN_CHATGENERAL1_UNDEADWARLOCK_RESPONDER = "UndeadWarlock"
    constant string VL_UNDEADWARLOCK_REPLY_HEROSHAMAN_CHATGENERAL1_UNDEADWARLOCK_TEXT = "The wind stopped troubling me when I stopped breathing."
    constant string VL_UNDEADWARLOCK_REPLY_HEROSHAMAN_CHATWARLOCK1_UNDEADWARLOCK_KEY = "HeroShaman_ChatWarlock1UndeadWarlock"
    constant string VL_UNDEADWARLOCK_REPLY_HEROSHAMAN_CHATWARLOCK1_UNDEADWARLOCK_PRIMARY = "HeroShaman_ChatWarlock1"
    constant string VL_UNDEADWARLOCK_REPLY_HEROSHAMAN_CHATWARLOCK1_UNDEADWARLOCK_RESPONDER = "UndeadWarlock"
    constant string VL_UNDEADWARLOCK_REPLY_HEROSHAMAN_CHATWARLOCK1_UNDEADWARLOCK_TEXT = "Impressive is a living word. Effective is better."
    constant string VL_UNDEADWARLOCK_REPLY_HEROSHAMAN_CHATWARLOCK4_UNDEADWARLOCK_KEY = "HeroShaman_ChatWarlock4UndeadWarlock"
    constant string VL_UNDEADWARLOCK_REPLY_HEROSHAMAN_CHATWARLOCK4_UNDEADWARLOCK_PRIMARY = "HeroShaman_ChatWarlock4"
    constant string VL_UNDEADWARLOCK_REPLY_HEROSHAMAN_CHATWARLOCK4_UNDEADWARLOCK_RESPONDER = "UndeadWarlock"
    constant string VL_UNDEADWARLOCK_REPLY_HEROSHAMAN_CHATWARLOCK4_UNDEADWARLOCK_TEXT = "Respect is optional. Obedience is measurable."
    constant string VL_UNDEADWARLOCK_REPLY_HEROWARRIOR_CHATGENERAL1_UNDEADWARLOCK_KEY = "HeroWarrior_ChatGeneral1UndeadWarlock"
    constant string VL_UNDEADWARLOCK_REPLY_HEROWARRIOR_CHATGENERAL1_UNDEADWARLOCK_PRIMARY = "HeroWarrior_ChatGeneral1"
    constant string VL_UNDEADWARLOCK_REPLY_HEROWARRIOR_CHATGENERAL1_UNDEADWARLOCK_RESPONDER = "UndeadWarlock"
    constant string VL_UNDEADWARLOCK_REPLY_HEROWARRIOR_CHATGENERAL1_UNDEADWARLOCK_TEXT = "Ancestors are quieter when you know where they are buried."
    constant string VL_UNDEADWARLOCK_REPLY_HEROWARRIOR_CHATWARLOCK1_UNDEADWARLOCK_KEY = "HeroWarrior_ChatWarlock1UndeadWarlock"
    constant string VL_UNDEADWARLOCK_REPLY_HEROWARRIOR_CHATWARLOCK1_UNDEADWARLOCK_PRIMARY = "HeroWarrior_ChatWarlock1"
    constant string VL_UNDEADWARLOCK_REPLY_HEROWARRIOR_CHATWARLOCK1_UNDEADWARLOCK_RESPONDER = "UndeadWarlock"
    constant string VL_UNDEADWARLOCK_REPLY_HEROWARRIOR_CHATWARLOCK1_UNDEADWARLOCK_TEXT = "Dangerous power is still power."
    constant string VL_UNDEADWARLOCK_REPLY_HEROWARRIOR_CHATWARLOCK3_UNDEADWARLOCK_KEY = "HeroWarrior_ChatWarlock3UndeadWarlock"
    constant string VL_UNDEADWARLOCK_REPLY_HEROWARRIOR_CHATWARLOCK3_UNDEADWARLOCK_PRIMARY = "HeroWarrior_ChatWarlock3"
    constant string VL_UNDEADWARLOCK_REPLY_HEROWARRIOR_CHATWARLOCK3_UNDEADWARLOCK_RESPONDER = "UndeadWarlock"
    constant string VL_UNDEADWARLOCK_REPLY_HEROWARRIOR_CHATWARLOCK3_UNDEADWARLOCK_TEXT = "Everything betrays eventually. Demons are simply honest about it."
    constant string VL_UNDEADWARLOCK_REPLY_HEROENGINEER_CHATGENERAL1_UNDEADWARLOCK_KEY = "HeroEngineer_ChatGeneral1UndeadWarlock"
    constant string VL_UNDEADWARLOCK_REPLY_HEROENGINEER_CHATGENERAL1_UNDEADWARLOCK_PRIMARY = "HeroEngineer_ChatGeneral1"
    constant string VL_UNDEADWARLOCK_REPLY_HEROENGINEER_CHATGENERAL1_UNDEADWARLOCK_RESPONDER = "UndeadWarlock"
    constant string VL_UNDEADWARLOCK_REPLY_HEROENGINEER_CHATGENERAL1_UNDEADWARLOCK_TEXT = "A device held together by tape and willpower. Familiar, in a way."
    constant string VL_UNDEADWARLOCK_REPLY_HEROENGINEER_CHATWARLOCK2_UNDEADWARLOCK_KEY = "HeroEngineer_ChatWarlock2UndeadWarlock"
    constant string VL_UNDEADWARLOCK_REPLY_HEROENGINEER_CHATWARLOCK2_UNDEADWARLOCK_PRIMARY = "HeroEngineer_ChatWarlock2"
    constant string VL_UNDEADWARLOCK_REPLY_HEROENGINEER_CHATWARLOCK2_UNDEADWARLOCK_RESPONDER = "UndeadWarlock"
    constant string VL_UNDEADWARLOCK_REPLY_HEROENGINEER_CHATWARLOCK2_UNDEADWARLOCK_TEXT = "Demons backfire less often than goblin machinery."
    constant string VL_UNDEADWARLOCK_REPLY_HEROENGINEER_CHATWARLOCK5_UNDEADWARLOCK_KEY = "HeroEngineer_ChatWarlock5UndeadWarlock"
    constant string VL_UNDEADWARLOCK_REPLY_HEROENGINEER_CHATWARLOCK5_UNDEADWARLOCK_PRIMARY = "HeroEngineer_ChatWarlock5"
    constant string VL_UNDEADWARLOCK_REPLY_HEROENGINEER_CHATWARLOCK5_UNDEADWARLOCK_RESPONDER = "UndeadWarlock"
    constant string VL_UNDEADWARLOCK_REPLY_HEROENGINEER_CHATWARLOCK5_UNDEADWARLOCK_TEXT = "Use my power as a battery and I will use your skull as a lantern."
    constant string VL_UNDEADWARLOCK_REPLY_HEROPALADIN_CHATGENERAL1_UNDEADWARLOCK_KEY = "HeroPaladin_ChatGeneral1UndeadWarlock"
    constant string VL_UNDEADWARLOCK_REPLY_HEROPALADIN_CHATGENERAL1_UNDEADWARLOCK_PRIMARY = "HeroPaladin_ChatGeneral1"
    constant string VL_UNDEADWARLOCK_REPLY_HEROPALADIN_CHATGENERAL1_UNDEADWARLOCK_RESPONDER = "UndeadWarlock"
    constant string VL_UNDEADWARLOCK_REPLY_HEROPALADIN_CHATGENERAL1_UNDEADWARLOCK_TEXT = "Glory fades. Bones remain."
    constant string VL_UNDEADWARLOCK_REPLY_HEROPALADIN_CHATWARLOCK1_UNDEADWARLOCK_KEY = "HeroPaladin_ChatWarlock1UndeadWarlock"
    constant string VL_UNDEADWARLOCK_REPLY_HEROPALADIN_CHATWARLOCK1_UNDEADWARLOCK_PRIMARY = "HeroPaladin_ChatWarlock1"
    constant string VL_UNDEADWARLOCK_REPLY_HEROPALADIN_CHATWARLOCK1_UNDEADWARLOCK_RESPONDER = "UndeadWarlock"
    constant string VL_UNDEADWARLOCK_REPLY_HEROPALADIN_CHATWARLOCK1_UNDEADWARLOCK_TEXT = "Then keep your delicate nose away from my spellwork."
    constant string VL_UNDEADWARLOCK_REPLY_HEROPALADIN_CHATWARLOCK3_UNDEADWARLOCK_KEY = "HeroPaladin_ChatWarlock3UndeadWarlock"
    constant string VL_UNDEADWARLOCK_REPLY_HEROPALADIN_CHATWARLOCK3_UNDEADWARLOCK_PRIMARY = "HeroPaladin_ChatWarlock3"
    constant string VL_UNDEADWARLOCK_REPLY_HEROPALADIN_CHATWARLOCK3_UNDEADWARLOCK_RESPONDER = "UndeadWarlock"
    constant string VL_UNDEADWARLOCK_REPLY_HEROPALADIN_CHATWARLOCK3_UNDEADWARLOCK_TEXT = "Purify me and you may not enjoy what is left."

endglobals

endlibrary
